### ISSUE TITLE
scalapbc fails because of unknown `option csharp_namespace`

### ISSUE THREAD

**Issue by dvtomas** [scalapb/ScalaPB#1012]
We are using protobuf for IPC between Scala and C#. We'd like to specify a C# version namespace, but scalapbc chokes on that:

Foo.proto
```proto
syntax = 'proto2';

option csharp_namespace = "Foo";
```

```
$ scalapbc -v2.6.1 --scala_out=flat_package,retain_source_code_info,no_lenses:../scala/ Foo.proto
Foo.proto:3:8: Option "csharp_namespace" unknown.
```

The option should be IMHO silently ignored.

**Comment by thesamet** [comment]
Hi @dvtomas , the error is coming from protoc. Perhaps v2.6.1 does not support this option. Can you try using a more recent version?

**Comment by dvtomas** [comment]
Thanks, removing the `-v` switch helped, I don't even remember why I put it in the first place :-)
