### ISSUE TITLE
can't build using Mac M1 arm

### ISSUE THREAD

**Issue by johnynek** [scalapb/ScalaPB#1024]
When using the azul JVM (jdk8) on a new Mac M1 chip, I get:

```
 error occurred while compiling protobuf files: Unsupported platform: protoc-3.11.4-osx-aarch_64.exe
```

I gather protoc is a transitive dependency that is packaged in a jar.

This was with `"com.thesamet.scalapb" %% "compilerplugin" % "0.10.9"`

**Comment by thesamet** [comment]
Hi @johnynek , recent versions of sbt-protoc download a precompiled protoc from maven (artifacts are here: https://repo1.maven.org/maven2/com/google/protobuf/protoc/). Unfortunately, upstream isn't publishing for osx-aarch_64 (see 
protocobuffers/protobuf#8062). You should be able to build protobuf from source, or install a binary through other means, and 
set `PB.protocExecutable := file("/path/to/protoc")` in the project's sbt settings.

**Comment by thesamet** [comment]
Reopening - I think think is going to get increasingly reported, so perhaps we should have a better error message and instructions for Mac M1 ARM users.

**Comment by johnynek** [comment]
Thanks for replying. One issue with setting a custom path is that complicates your build: CI probably won't have that path. I guess some fancy sbt stuff can switch it out, but honestly I have minimized the amount of sbt I've learned over the years.

**Comment by thesamet** [comment]
Assuming CI isn't a Mac M1, you could try to customize it only when it's Mac M1 ARM:

```
PB.protocExecutable := (if (sbtprotoc.SystemDetection.detectedClassifier=="osx-aarch_64") "/some/path" else PB.protocExecutable.value)
```

I haven't verified that this `osx-aarch_64` is the precise string that is returned by `detectedClassifier` so try printing that value and see what you get.

**Comment by lhohan-cb** [comment]
Also running into this error. However I do not seem to have the `PB.protocExecutable` setting available.

Do you have any idea what could be the cause?

We are using fs2-grpc which seems to be using these version of the scalpb plugin:
https://github.com/fiadliel/fs2-grpc/blob/c598fd3429411f3cb66e8cb0edb610346edd9682/project/plugins.sbt

Any help is kindly appreciated.

**Comment by thesamet** [comment]
hi @lhohan-cb , please update to the latest version of sbt-protoc (currently 1.0.1), there is an example of `PB.protocExecutable` in this section of the docs: https://github.com/thesamet/sbt-protoc#additional-options

**Comment by johnynek** [comment]
It's not quite that simple. Most users will want to support building on M1 as well as non-M1. In the non-M1 case, you will want to use the default approach to make CI and life easier for those not on M1.

So I guess we need some configuration to switch based on detecting the arch we are on.

**Comment by thesamet** [comment]
> It's not quite that simple. Most users will want to support building on M1 as well as non-M1. In the non-M1 case, you will want to use the default approach to make CI and life easier for those not on M1.

I believe we addressed this concern in the [previous comment](https://github.com/scalapb/ScalaPB/issues/1024#issuecomment-753662905) - overriding PB.protocExecutable conditionally on the detected platform is fairly straightforward.

**Comment by johnynek** [comment]
Indeed, I overlooked that.

**Comment by lhohan-cb** [comment]
> hi @lhohan-cb , please update to the latest version of sbt-protoc (currently 1.0.1), there is an example of `PB.protocExecutable` in this section of the docs: https://github.com/thesamet/sbt-protoc#additional-options

Thanks @thesamet 

Since I was using this through fs2-grpc I could update this plugin to 0.9.0-M1 which had the version of sbt-protoc I required 😅 .

I had to change your example above code a little:

```
 PB.protocExecutable := (
       if (protocbridge.SystemDetector.detectedClassifier()=="osx-aarch_64")
         file("/usr/local/bin/protoc") // to change if needed, this is where protobuf manual compilation put it for me
       else
         PB.protocExecutable.value
       )
```

**Comment by elbaulp** [comment]
I'm facing the same issue, but I am using `scalapbc` as a standalone plugin, I'm getting:

```
bin/0.11.0/scalapbc-0.11.0/bin/scalapbc \
  // options here...
Error fetching artifacts:
https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.15.6/protoc-3.15.6-osx-aarch_64.exe: not found: https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.15.6/protoc-3.15.6-osx-aarch_64.exe
```

Is there any way of specifying the arch?

**Comment by thesamet** [comment]
@elbaulp Until [Protocol Buffers provides a binary for Mac M1 Arm](https://github.com/protocolbuffers/protobuf/issues/8062), you have to build protoc from source. With ScalaPBC you can pass the path to your protoc with `--protoc=/path/to/protoc`.

**Comment by elbaulp** [comment]
@thesamet thanks!

**Comment by nurikk** [comment]
> @elbaulp Until [Protocol Buffers provides a binary for Mac M1 Arm](https://github.com/protocolbuffers/protobuf/issues/8062), you have to build protoc from source. With ScalaPBC you can pass the path to your protoc with `--protoc=/path/to/protoc`.


`--protoc` has to one of the first parameters in args

Not working
```
args = [
        protoFile, "--scala_out=grpc:${protoDestDir}",
        "--protoc=/opt/homebrew/bin/protoc",
]
```
Working
```
 args = [
                "--protoc=/opt/homebrew/bin/protoc",
                protoFile, "--scala_out=grpc:${protoDestDir}"
        ]
```

**Comment by thesamet** [comment]
@nurikk Correct. ScalaPBC processes the command line as long as there are parameters that it recognizes. When it encounters a parameter it doesn't recognize (such as `protoc` parameters), or `--`, it forwards from that point onwards to `protoc`.

**Comment by nurikk** [comment]
> @nurikk Correct. ScalaPBC processes the command line as long as there are parameters that it recognizes. When it encounters a parameter it doesn't recognize (such as `protoc` parameters), or `--`, it forwards from that point onwards to `protoc`.

yeah, it took me a while to figure out this fact,  I just updated to save some ones time :)

**Comment by thesamet** [comment]
protoc version 3.17.3 is shipped with a binary that is identical to the x86_64 binary, but can be run on M1 Arm using Rosetta compatibility mode. Can one of you that have access to M1 ARM try to set `PB.protocVersion := "3.17.3"` in their project and confirm whether it works?

**Comment by siddharthvp** [comment]
> protoc version 3.17.3 is shipped with a binary that is identical to the x86_64 binary, but can be run on M1 Arm using Rosetta compatibility mode. Can one of you that have access to an M1 Mac try set `PB.protocVersion := "3.17.3"` in their project and confirm whether it works?

Still fails with `download failed: com.google.protobuf#protoc;3.15.6!protoc.exe(protoc-binary)` despite setting protocVersion as 3.17.3.  Using sbt-protoc v1.0.3 and scalapb compiler-plugin v0.11.4.

**Comment by thesamet** [comment]
@siddharthvp It looks like the `PB.protocVersion` is not applied in the project which reports the error (given that it tries to download version `3.15.6` in the error you reported. Without seeing the `build.sbt`, it is hard to tell where the problem is. Perhaps you can try on a vanilla project created with:

```
sbt new scalapb/scalapb-template.g8
```

Then, in the generated `build.sbt`, add:

```
PB.protocVersion := "3.17.3"
```

**Comment by johnynek** [comment]
Just to report back, adding `PB.protocVersion := "3.17.3"` as one of the `.settings(...)` in my build worked for me on an M1.

Thanks!

**Comment by thesamet** [comment]
Perfect, thanks for confirming, @johnynek .

**Comment by github-brice-jaglin** [comment]
Following up in https://github.com/thesamet/sbt-protoc/pull/279

**Comment by basicobject** [comment]
Adding this updated plugin did the work for me

addSbtPlugin("com.thesamet" % "sbt-protoc" % "1.0.6")

**Comment by benckx** [comment]
> Adding this updated plugin did the work for me
> 
> addSbtPlugin("com.thesamet" % "sbt-protoc" % "1.0.6")

Thanks, this worked for me.

Is there a link to check what's the latest version of the plugin, and which version of `protoc-3.x.x-osx-aarch_64.exe` it uses? Trying to change the version with `Compile / PB.protocVersion := "-v3.17.3"` wouldn't work for me, but upgrading `sbt-protoc` picked up `protoc-3.19.2-osx-aarch_64.exe` automatically.

**Comment by thesamet** [comment]
Latest version of the plugin: https://github.com/thesamet/sbt-protoc/tags
The specific version of protoc it will pick up by default isn't documented outside the source code (good suggestion though!). I am not sure why setting it specifically `PB.protocVersion` didn't work for you - it will be useful if you can file a new issue with a minimal example showing that the setting is ignored.

**Comment by yonatanomer** [comment]
Hi Nadav

both the sandalone scalapbc and the SBT plugin shows `Error fetching artifacts` even when passing explicit path:

**scalapbc:**
`./scalapbc -v3.5.1 --scala_out=./generated ./protobuf/protos.proto --protoc=/opt/homebrew/Cellar/protobuf/21.9_1/bin/protoc      
Error fetching artifacts:
https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.5.1/protoc-3.5.1-osx-aarch_64.exe: not found: https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.5.1/protoc-3.5.1-osx-aarch_64.exe
`

**sbt plugin**
`
PB.protocExecutable := (
  if (protocbridge.SystemDetector.detectedClassifier() == "osx-aarch_64") {
    print("osx-aarch_64") // i can see compile is reaching here
    file("/opt/homebrew/Cellar/protobuf/21.9_1/bin/protoc")
  } else
    PB.protocExecutable.value
)

`
