### ISSUE TITLE
Option to not automatically compile

### ISSUE THREAD

**Issue by acjay** [scalapb/ScalaPB#104]
Because my proto files rarely change, I would prefer to manually trigger compilation and keep my generated classes under source control. This is what I do for Slick's `genTables`. Is there a way to accomplish this? If not, I'd like to request this feature.

**Comment by thesamet** [comment]
In that case, instead of the SBT plugin, you can use spbc (https://trueaccord.github.io/ScalaPB/) and generate manually only when you need.

Let me know if this does (or does not) resolve your issue. Adding support for this mode of operation would require changing sbt-protobuf as well.

**Comment by acjay** [comment]
Ah yeah, that should do it. I'll try to figure out how to wrap this in a simple SBT task withing my own `Build.sbt`.

**Comment by acjay** [comment]
Perhaps you can help me figure this out -- I only have one `.proto` file with no includes, I've got the ScalaPB SBT plugin set up with `protoc-jar`. This seems a bit better than manually installing `spbc`, because SBT will get all the dependencies in place. `spbc` seems straighforward enough in its arguments, but how would I invoke it, installed via SBT, in a custom task?

**Comment by thesamet** [comment]
It should be a combination of http://www.scala-sbt.org/0.13.5/docs/Extending/Commands.html and http://www.scala-sbt.org/0.13/docs/Process.html - though it's probably better to ask this over stackoverflow.

I am going to keep this issue open, since it would be nice to support this use case with the sbt plugin eventually.

**Comment by acjay** [comment]
Just to clarify, I've used `Process` before, my question would be how to get the path to `spbc` executable, as installed by SBT.

**Comment by acjay** [comment]
StackOverflow question here: http://stackoverflow.com/questions/36827692/manually-invoke-scalapb-compiler-in-an-sbt-task

**Comment by acjay** [comment]
Just wanted to check if you had any thoughts on my follow-up question. Your suggestion would work great if I installed scalapbc manually, but I'm not sure how to do it with the dependencies managed purely by SBT. I edited my question with what I've got so far.

**Comment by acjay** [comment]
FYI, there's a blog post that just came out that probably does what I'm trying http://www.cakesolutions.net/teamblogs/protocol-buffers-and-scala-microservices. I haven't tried it yet, myself, though.

**Comment by thesamet** [comment]
With sbt-protoc, if wanting to manage the generated code under source control (though not recommended),  you can include this `build.sbt`:

```
PB.targets in Compile := Seq(
  scalapb
    .gen(grpc = true, flatPackage = true) -> baseDirectory.value / "src/main/scala-protos"
)
```

**Comment by zallesov** [comment]
I ran into similar problem. I want to generate protobufs on demand. Like `sbt gen_protos`
But all the examples I find attach the generation to the compile step. It causes issues on the CI server that compiles the code.

How can I just create an sbt task that does only that?

**Comment by thesamet** [comment]
In `build.sbt`, tell ScalaPB to generate files into a subdirectory of scalaSource (so the `compile` command sees them):

```
PB.targets in Compile := Seq(
  scalapb.gen() -> (scalaSource in Compile).value / "protos"
)
```
**NOTE:** ScalaPB will delete the directory each time you regenerate (so unneeded files get removed, for example when you rename a message). Therefore it's important to generate to a _subdirectory_ of your source directory, so it doesn't delete your source!

Then, remove ScalaPB source generator so it doesn't run automatically:
```
sourceGenerators in Compile -= (PB.generate in Compile).taskValue
```

From this point, you are managing when this generator runs.  In SBT, run `protocGenerate` whenever you want ScalaPB to generate.

**Comment by zallesov** [comment]
Thank you for quick reply. I did try what you suggested. There are few problems with that.
I still have my generated code put inside `target/scala-2.11/src_managed/main` although the `(scalaSource in Compile).value / "protos"` is pointing to the folder under src/. How can I specify the output folder?

`sourceGenerators in Compile -= (PB.generate in Compile).taskValue` seems like there is no `-=` and I could not google anything that replace it.
