### ISSUE TITLE
Duration can not have negative nanos

### ISSUE THREAD

**Issue by piyo7** [scalapb/ScalaPB#1068]
In ScalaPB 0.10.11, negative nanos field of Duration is not valid.

```scala
import com.google.protobuf.duration.Duration
import scala.math.Ordered.orderingToOrdered
Duration(0, 0) > Duration(-1, -2)
```

```
requirement failed: Duration Duration(-1,-2,UnknownFieldSet(Map())) is not valid.
java.lang.IllegalArgumentException: requirement failed: Duration Duration(-1,-2,UnknownFieldSet(Map())) is not valid.
```

According to Google's specification, nanos can actually be a negative value.

> Signed fractions of a second at nanosecond resolution of the span of time. Durations less than one second are represented with a 0 `seconds` field and a positive or negative `nanos` field. For durations of one second or more, a non-zero value for the `nanos` field must be of the same sign as the `seconds` field. Must be from -999,999,999 to +999,999,999 inclusive.

https://github.com/protocolbuffers/protobuf/blob/v3.14.0/src/google/protobuf/duration.proto

If it is a bug, I will create a pull request to fix [DurationCompanionMethods.scala](https://github.com/scalapb/ScalaPB/blob/master/scalapb-runtime/src/main/scala/scalapb/DurationCompanionMethods.scala).

**Comment by thesamet** [comment]
Yes, a fix will be welcome. Note that if we allow negative nanos, the Duration would have to be normalized before being compared for ordering. There are reference implementation here: https://github.com/protocolbuffers/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/TimeUtil.java and https://github.com/protocolbuffers/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/Durations.java
