### ISSUE TITLE
can't make a class with a package that matches option java_package in proto file

### ISSUE THREAD

**Issue by cozima0210** [scalapb/ScalaPB#1081]
Hi @thesamet. I created an issue below, but the cause seems to be in this repo.
https://github.com/phiSgr/gatling-grpc/issues/46
I want to know why the class will be created in the different package that indicates in proto file. Is this bug?
Thanks.

**Comment by thesamet** [comment]
Hi @cozima0210 , the file names are appended by default to the package. See flat_package for a way to override this: https://scalapb.github.io/docs/customizations - this can be done through a file-level option, or applied to an entire package through package-scoped option.

**Comment by cozima0210** [comment]
@thesamet I solved it! Thaks a lot!!

**Comment by phiSgr** [comment]
It's disappointing that, in the linked issue, I already pointed to the `flat_package` flag used by akka grpc. The documentation linked is just one google away. Yet OP chose to open an issue right away. Behaviour pattern like this really demoralizes open-source contributors from writing documentations. What good are docuementations if they are not read?

Also, if it were directed at me, I would take offense at low effort questions like "did you write a bug" when the question should be "did i have a misunderstanding of how your code works".
