### ISSUE TITLE
Feature request: Support proto3 optionals

### ISSUE THREAD

**Issue by jschumacher-dexcom** [scalapb/ScalaPB#1097]
Support for optionals was added back to proto3 recently:
https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0

The following proto schema fails to compile with ScalaPB 0.11.0-M7
```protobuf
message MyMessage {
  optional uint32 my_number = 1;
}
```

**Comment by thesamet** [comment]
proto3 optionals are supported. Can you clarify how does it fail? Are you passing the correct experimental flag to protoc using PB.protocOptions?

**Comment by jschumacher-dexcom** [comment]
Ahh, thank you-- that did it.  I should have noticed the error message: `receiver.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.`. In the latest version of protoc, the `--experimental_allow_proto3_optional` flag is no longer required.

**Comment by wb14123** [comment]
Hi @jschumacher-dexcom , I'm trying to use optional with proto3 as well but get a different error:

```
grpc-api.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-jvm_1 hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--jvm_1_out: 
```

My dependency versions are like this:

```
libraryDependencies ++= Seq(
  "com.thesamet.scalapb" %% "compilerplugin" % "0.11.3"
)

addSbtPlugin("com.thesamet" % "sbt-protoc" % "1.0.4")
addSbtPlugin("com.lightbend.akka.grpc" % "sbt-akka-grpc" % "2.0.0")
```

I set protoc version and add experimental flag in build.sbt but without luck:

```
PB.protocVersion := "3.15.0"
Compile / PB.protocOptions := Seq("--experimental_allow_proto3_optional")
```

Though the error is different, could you still share how did you config it to resolve this issue? Thanks!

**Comment by thesamet** [comment]
This is due to akka-grpc not supporting proto3 optionals. It is a trivial change for akka-grpc since it doesn't interact with individual fields. I sent the following PR to akka-grpc: https://github.com/akka/akka-grpc/pull/1379
