### ISSUE TITLE
Add an option to skip the generation of the `getXYZ` methods on the fields

### ISSUE THREAD

**Issue by tOverney** [scalapb/ScalaPB#1098]
When generating the scala classes for the proto messages;
If a field is optional it currently always generate a get method that relies on the default value:
https://github.com/scalapb/ScalaPB/blob/master/compiler-plugin/src/main/scala/scalapb/compiler/ProtobufGenerator.scala#L1329

These methods are not very Scala idiomatic and add unneeded options;
For my use case it would be nice to skip their generation to avoid them being available at all and ensure optionality is always handled explicitely.

Would a PR adding an general option to always skip generating these getters be accepted if I endeavoured in it?
If so, where would be the best place to add this option? as one of the scalapb.gen(...) ?

**Comment by tOverney** [comment]
One point is that those gets are currently used in the lenses' logic so maybe they should still be generated but with a private[xyz] scope so that they don't leak

**Comment by thesamet** [comment]
Hi @tOverney , thanks for making this feature request and offering to work on a PR. Yes, we can definitely have something like this accepted. The new option should be a file-level option, so users can apply it an en entire package through package-scoped option.

As you noted, `lenses` relies on the getters, so when the `no_lenses` is specified, the getters should not be generated at all to avoid an unused method warning for the getters. I suggest to call this new file-level option `no_getters` and add it in `scalapb.proto` in similar fashion to `no_lenses` stating the logic described above that involves `no_lenses`.

We are avoiding exposing options that affect the generated code interface through external generator parameters, so there's no need to wire the new option all the way up to `scalapb.gen`. (see [FAQ](https://scalapb.github.io/docs/faq#why-a-certain-customization-is-not-available-as-a-global-generator-parameter)).

**Comment by thesamet** [comment]
[This section](https://github.com/scalapb/ScalaPB/blob/master/CONTRIBUTING.md#modifying-scalapbproto) of the contributing doc will also be helpful if you are not familiar with the flow for updating scalapb.proto.

**Comment by thesamet** [comment]
Hi @tOverney , are you still interested in working on this enhancement?

**Comment by tOverney** [comment]
hey @thesamet still something I'm intereste in and want to tackle, to be perfectly honest I have not started to tackle it :(
