### ISSUE TITLE
Add versionScheme for sbt 1.5.0

### ISSUE THREAD

**Issue by saeltz** [scalapb/ScalaPB#1102]
sbt `1.5.0` is released soon and brings eviction-errors instead of eviction-warnings based on `versionScheme` and also nudges library authors to add `versionScheme` to their `build.sbt`.

I realized the property isn't added yet and I would be willing to contribute if you agree this makes sense. I think you're using `early-semver` (still pre-1.0).

**Comment by thesamet** [comment]
Thanks for bringing this up. A PR would be welcome. Confirming that we should be on `early-semver`.
