### ISSUE TITLE
JSON parsing of overlapping oneof keys

### ISSUE THREAD

**Issue by sttawm** [scalapb/ScalaPB#1117]
Would it make sense for the JSON parser to complain if multiple fields of a oneof are defined?

Or maybe the compiler could be configured to generate code (a `Reads[T]`) that complains if the oneof is oversubscribed?

I looked into passing a custom formatter via `.registerMessageFormatter` to gain access to the e.g. `JValue`  before passing it along to the default parser, but I don't have access to a default parser, and I don't want to have to specify a writer as well.

I may be able to take a pass at it if this could be helpful to others or if there's a suggested way to handle this.

**Comment by thesamet** [comment]
I think that it would be reason to add an option for this that should be opt-in (in order to avoid breaking existing user). Can you check how this is handled in protobuf-java? If there's some pre-existing behavior then we should follow that here. A PR to address this will be welcome.

**Comment by thesamet** [comment]
Hi @sttawm , are you interested in working on this?

**Comment by sttawm** [comment]
See [this PR](https://github.com/scalapb/scalapb-json4s/pull/236)
