### ISSUE TITLE
JsonFormat cannot serialize Array[GeneratedMessage] to Json

### ISSUE THREAD

**Issue by feixie79** [scalapb/ScalaPB#1121]
I got JsonFormatException due to missing pattern matching of Array when trying to convert some generated message into json by the JsonFormat.

The cause is that generated method getFieldByNumber has following code    
`case 4 => _root_.scalapb.descriptors.PRepeated(stopIds.iterator.map(package._typemapper_stopIds.toBase(_).toPMessage).toVector)`
which convert the stopIds from Seq[String] into Array[String] 
and Array[String] is not an Iterable[GeneratedMessage]

therefore I create a PR to add pattern for matching Array[GeneratedMessage]
and convert it implicitly to Iterable by serialization 
https://github.com/scalapb/scalapb-json4s/pull/222

**Comment by thesamet** [comment]
Thanks for reporting and working on a PR. Let's ensure that we also understand the problem better by adding a test case that would fail without the fix you provided in the PR.

**Comment by thesamet** [comment]
PR merged.
