### ISSUE TITLE
scalapb error: java.lang.StackOverflowError

### ISSUE THREAD

**Issue by sudhirkumar1980** [scalapb/ScalaPB#1176]
We are having large number in .proto file. Scalapb is able to compile the .proto file having upto 172 fields. it failed with error error: java.lang.StackOverflowError if for proto file having more than 172 fields. is there any solution or workaround for it?
###maven plugin
      <plugin>
        <groupId>com.github.os72</groupId>
        <artifactId>protoc-jar-maven-plugin</artifactId>
        <version>3.11.4</version>
        <executions>
          <execution>
            <phase>generate-sources</phase>
            <goals>
              <goal>run</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <includeMavenTypes>transitive</includeMavenTypes>
          <outputTargets>
            <outputTarget>
              <type>scalapb</type>
              <outputOptions>grpc</outputOptions> 
              <pluginArtifact>com.thesamet.scalapb:protoc-gen-scala:0.11.0-M2:bat:windows</pluginArtifact>
            </outputTarget>
          </outputTargets>
        </configuration>
      </plugin>

##Error Message
[ERROR] error: java.lang.StackOverflowError

**Comment by thesamet** [comment]
Thanks for reporting. Can you provide the full exception given, and if possible a sample project that demonstrates the problem?

**Comment by thesamet** [comment]
Has the problem been resolved? Can you share more details?

**Comment by sudhirkumar1980** [comment]
i can not reproduce issue outside of one environment. seems like it is due to out of memory issue for intellij.

**Comment by thesamet** [comment]
Got it - you could try adjusting the various memory settings for the JVM in question.
