### ISSUE TITLE
Unable to match on a repeated option field in a transformation

### ISSUE THREAD

**Issue by gontard** [scalapb/ScalaPB#1177]
I am trying to write the following rule based type customization:

```proto
message SetPermission {
   required string permission = 1 [(validate.rules).string = { in: ["manage", "view"] }]
}

option (scalapb.options) = {
  scope: PACKAGE
    {
      when: {
        options: {
          [validate.rules] {
            string {
              in: ["manage", "view"]
            }
          }
        }
      }
      set: {
        [scalapb.field] {
          type: "mypackage.Permission"
        }
      }
    }
  ]
};

```

but [this exception](https://github.com/protocolbuffers/protobuf/blob/4644980d818ec9d987f74c74b1a1d45de9ab01fd/java/core/src/main/java/com/google/protobuf/FieldSet.java#L1037-L1040) is raised during [transformation](https://github.com/scalapb/ScalaPB/blob/e368415a09a7d568ac81d8a13969fd3c05ef724f/compiler-plugin/src/main/scala/scalapb/compiler/FieldTransformations.scala#L98):

```
[info] Compiling 63 protobuf files to /home/gontard/stuff/target/scala-2.13/akka-grpc/main
--jvm_1_out: java.lang.IllegalArgumentException: hasField() can only be called on non-repeated fields.
	at com.google.protobuf.FieldSet.hasField(FieldSet.java:253)
	at com.google.protobuf.DynamicMessage.hasField(DynamicMessage.java:189)
	at scalapb.compiler.FieldTransformations$.$anonfun$matchContains$1(FieldTransformations.scala:98)
	at scalapb.compiler.FieldTransformations$.$anonfun$matchContains$1$adapted(FieldTransformations.scala:95)
  | => aat scala.collection.immutable.Map$Map1.forall(Map.scala:196)
	at scalapb.compiler.FieldTransformations$.matchContains(FieldTransformations.scala:95)
	at scalapb.compiler.FieldTransformations$.$anonfun$matchContains$1(FieldTransformations.scala:103)
	at scalapb.compiler.FieldTransformations$.$anonfun$matchContains$1$adapted(FieldTransformations.scala:95)

```

Am i doing something wrong or is it a limitation?

**Comment by thesamet** [comment]
It's a bug/limitation - we haven't defined how matching should behave for repeated fields. I wonder what the behavior should be, possibly these two conditions should be met:
1. lists are of the same size
2. if elements are scalar, lists need to be equal
3. if elements are messages, corresponding elements need to satisfy `matchContains`

It might make sense to change (3) to ask for strict equality. I am not sure if there's a case for that in scalapb-validate.

Looks like you've found the relevant code - will you be interested in working on a PR?

**Comment by gontard** [comment]
Thanks for your answer.

> It's a bug/limitation - we haven't defined how matching should behave for repeated fields. 
👌 

I wonder what the behavior should be, possibly these two conditions should be met:
> 
> 1. lists are of the same size
> 2. if elements are scalar, lists need to be equal
> 3. if elements are messages, corresponding elements need to satisfy `matchContains`

👍 

> 
> It might make sense to change (3) to ask for strict equality. I am not sure if there's a case for that in scalapb-validate.
> 

I don't have any use case in mind.

> Looks like you've found the relevant code - will you be interested in working on a PR?

Yes. I will try to find some time.
A few questions:
 - is there something to do for the others matching modes (`EXACT`, `PRESENCE`)?
 - i found some [transformations](https://github.com/scalapb/ScalaPB/blob/master/e2e/src/main/protobuf/transformations/field_transformations.proto) in e2e tests but i don't understand how they are verified.

**Comment by thesamet** [comment]
> is there something to do for the others matching modes (EXACT, PRESENCE)?

I believe `EXACT`'s implementation remains unchanged. `PRESENCE` seem to have a similar bug, I think that for repeated fields, it needs to compare non-emptiness and not recurse.

> i found some transformations in e2e tests but i don't understand how they are verified.

The `PRESENCE` and `CONTAINS` matches are tested [here](https://github.com/scalapb/ScalaPB/blob/master/compiler-plugin/src/test/scala/scalapb/compiler/FieldTransformationsSpec.scala#L428-L515). It's outside e2e so much faster iteration time.
