### ISSUE TITLE
toString, name behavior of enums values when enum_strip_prefix: true

### ISSUE THREAD

**Issue by nitsh** [scalapb/ScalaPB#1201]
Context : 
Google protobuf style guide for enums suggests to add prefix to enums to help avoid conflicts of value names of enums defined in the same file : https://developers.google.com/protocol-buffers/docs/style#enums

In case of .NET code generation, this style is recognized and the prefix is stripped from the enum values in the generated code : https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/protobuf-enums
and the `toString` returns without the prefix.

To achieve the same with scalapb we use `enum_strip_prefix: true` but the `toString` returns the value name from the proto definition along with the prefix. 

Current behavior : 
For the following enum proto with enum_strip_prefix: true , 

```
enum FooBar {
  FOO_BAR_UNSPECIFIED = 0;
  FOO_BAR_FIRST_VALUE = 1;
  FOO_BAR_SECOND_VALUE = 2;
}
```

the generated scala code is , 
```
case object FIRST_VALUE extends FooBar {
  val value = 1
  val index = 1
  val name = "FOO_BAR_FIRST_VALUE" // matching the proto name

  override def toString = name // for reference from the GeneratedEnum trait
}
```

So, `FIRST_VALUE.name == FIRST_VALUE.toString == "FOO_BAR_FIRST_VALUE"`

Expected Behavior : 
`FIRST_VALUE.name == FIRST_VALUE.toString == "FIRST_VALUE"`

I'm assuming that the users who configure `enum_strip_prefix: true` would usually expect string_prefix applied on `toString` and `name` as well.

**Comment by thesamet** [comment]
Hi @nitsh , changing the behavior of `name` and `toString` to return the prefixed name would be a breaking change (other libraries already assume that it always matches the proto name). The fix I submitted above will let you retrieve the Scala name of the field through the descriptor. See [example usage here](https://github.com/scalapb/ScalaPB/blob/3ca07090973d7d81e075d25956a135efef6a7a63/e2e/src/test/scala/EnumOptions2Spec.scala#L18) and [proto definition](https://github.com/scalapb/ScalaPB/blob/3ca07090973d7d81e075d25956a135efef6a7a63/e2e/src/main/protobuf/enum_options2.proto#L13).
