### ISSUE TITLE
google.protobuf.Duration being mapped to Option[...]

### ISSUE THREAD

**Issue by yhvicey** [scalapb/ScalaPB#1203]
`google.protobuf.Duration` from `google/protobuf/duration.proto` being mapped to `Option[com.google.protobuf.duration.Duration]`, rather than `com.google.protobuf.duration.Duration` directly. I assume this message type should be non-nullable?
And is there any way to override this behavior to map `google.protobuf.Duration` in .proto to `com.google.protobuf.duration.Duration` directly in .scala?

**Comment by thesamet** [comment]
Hi @yhvicey , message types in proto3 are always optional. To avoid the option box you can [set the `no_box` option on a field](https://scalapb.github.io/docs/customizations#message-level-custom-type-and-boxing). You can also have this option set throughout your project by using field transformations. [This example](https://scalapb.github.io/docs/transformations#example-customizing-third-party-types) shows how to set a different option (custom type) for all fields of a given type.

**Comment by thesamet** [comment]
To summarize, add a file like this under src/main/protobuf/options.proto:

```
syntax = "proto2";

package change.to.your.package;  // CHANGE THIS

import "scalapb/scalapb.proto";

option (scalapb.options) = {
  scope: PACKAGE
  field_transformations : [
    {
      when : {
        type: TYPE_MESSAGE
        type_name: ".google.protobuf.Duration"
      }
      set : {[scalapb.field] {no_box : true }}
    }
  ]
};
```

**Comment by yhvicey** [comment]
Thanks @thesamet , `[(scalapb.field).no_box = true]` solve the issue for me.
BTW, seems `package.proto` with package-scope options is not working for Maven plugin, is this expected?

**Comment by thesamet** [comment]
> BTW, seems package.proto with package-scope options is not working for Maven plugin, is this expected?

This is expected to work with maven as long as the package.proto file is passed to protoc/scalapb along with the other proto files.

**Comment by yhvicey** [comment]
I created a minimal reproable [maven project](https://github.com/scalapb/ScalaPB/files/6886562/Repro.zip), within it I set `flat_package: true` and `scope: PACKAGE`, and if I execute `mvn clean protoc-jar:run` against this project, the generated message still have its containing file as part of its package name:
![image](https://user-images.githubusercontent.com/8000820/127177995-c9a52456-102c-45ad-9320-e52e54431bd4.png)
Could you please help take a look if there's any mis-configuration? Should I create a separate thread about this?

**Comment by thesamet** [comment]
@yhvicey the package name in `package.proto` and `ShouldBeFlatted.proto` are different. Package-scoped options are applied only in the scope of the package they are defined in and its subpackages.

**Comment by yhvicey** [comment]
They are same in my given sample:
![image](https://user-images.githubusercontent.com/8000820/127190072-8bdc4e72-75f8-41e5-b091-89408bedb5e2.png)

**Comment by thesamet** [comment]
It seems that there is a limitation for working with package-scoped option related to protoc-jar-maven-plugin. It appears to be invoking protoc for each file separately, rather than for all sources at once. So, when `ShouldBeFlatted.proto` is processed, it isn't aware of `package.proto`. To get around it, you could `import "package.proto"` in each source file.

I filed this issue with the plugin to check if there are other workarounds: https://github.com/os72/protoc-jar-maven-plugin/issues/110
