### ISSUE TITLE
Update resvered keyword list for Scala 3

### ISSUE THREAD

**Issue by rgueldem** [scalapb/ScalaPB#1226]
There are a few new reserved keywords in Scala 3, see list here: https://dotty.epfl.ch/docs/internals/syntax.html#keywords. The generated scala code can be invalid if it contains any of these. One of our schemas is using the term `open` in an enum, resulting in a syntax error.

Updating https://github.com/scalapb/ScalaPB/blob/428cd7139ed3e48566ee43339524bd41fcae9732/compiler-plugin/src/main/scala/scalapb/compiler/DescriptorImplicits.scala#L1106 might  resolve this issue. 

Thanks!

**Comment by thesamet** [comment]
Thanks, will you be able to send a PR?
