### ISSUE TITLE
Disable unknown fields via protoc option

### ISSUE THREAD

**Issue by moonkev** [scalapb/ScalaPB#1229]
Hello

Currently by default unknownFields are included in generated code.   This is of course a reasonable default and in accordance with how other protoc plugins (i.e. Java) work.  In a project that I work on however, we turn this off using the scalapb file level option `preserve_unknown_fields`.  We do this as we also expose our protobufs in graphql via Caliban library, and do not want unknownFields field exposed.  Also, we compile our protos to python and also pass them to other teams using go and C# so they either need to be given scalapb.proto or remove it from the protos we pass them each time.  I was curious if it is possible to add `preserve_unknown_fields` as a top level option to pass to the protoc command, in the same fashion that for example `flat_package` is.  This way we could disable it by default globally without having to include scalapb.proto in our files.  Thanks by the way for the awesome library, we have be using it for a couple years now, it has been awesome for us!

**Comment by thesamet** [comment]
Hi @moonkev , see this [FAQ](https://scalapb.github.io/docs/faq#why-a-certain-customization-is-not-available-as-a-global-generator-parameter). My suggestion is to add a new directory in your Scala project (say `src/main/protobuf-scala`) for the package-scoped options proto file, and put it in here. This would be the only place in your project where referencing `scalapb.proto` is permitted, and your main proto directory (`src/main/protobuf`) will be `scalapb.proto`-free. In your project config add a setting `Compile / PB.protoSources += file((Compile / sourceDirectory).value + "/protobuf-scala")` 

The proto file in `src/main/protobuf-scala` could look like this:

```
// src/main/protobuf-scala/scala.proto
package a.b.c; // must match the top-level package of your protos!
 
import "scalapb/scalapb.proto";
option (scalapb.options) = {
  scope: PACKAGE
  flat_package: true
  preserve_unknown_fields: false
  // more options...
};
```

**Comment by moonkev** [comment]
Thank you very much @thesamet!  This works perfectly for our needs.  My apologies, not sure how I missed this from the documentation.
