### ISSUE TITLE
When using ProtoSQL.udf on Databricks 7.3 LTS (Spark 3.0.1, Scala 2.12) cluster, encounter java.lang.VerifyError

### ISSUE THREAD

**Issue by Matt-S6** [scalapb/ScalaPB#1271]
When following along with the UDF example in the scalapb docs, https://scalapb.github.io/docs/sparksql#udfs, I encountered a `java.lang.VerifyError: class frameless.functions.Spark2_4_LambdaVariable overrides final method genCode`. This can be reproduced with additive-only modifications here: https://github.com/thesamet/sparksql-scalapb-test/pull/4. Am I doing something incorrectly here?

edit: ran this on a Databricks 7.3 LTS (Spark 3.0.1, Scala 2.12) cluster image.

**Comment by thesamet** [comment]
Hi @Matt-S6 , I wasn't able to reproduce the issue with Spark 3.0.1 and the PR you provided. From the exception you quoted, it seems that Spark 2.4 is involved in your environment. Please see the version compatibility matrix here: https://scalapb.github.io/docs/sparksql/#setting-up-your-project

**Comment by Matt-S6** [comment]
Hmm, I saw that and was very confused. The databricks cluster version is for spark 3.0.1, though their "7.3 LTS" equivalent package isn't identical to open-source spark 3.0. I'll try and reproduce this with the open source spark and go from there. Thanks for verifying on your machine... stay tuned.

**Comment by Matt-S6** [comment]
Following up here, confirmed your experience @thesamet, running open source spark 3.0.1 succeeds. So it seems to be something special about how databricks optimizes it's proprietary spark version. I'll poke them about it. In the meantime, I suppose my only short-term option is to drop down to spark 2.4 or run spark on aws EMR. What's the plan for releasing a scalapb version for spark 3.1 or 3.2 in case there's fixes in those versions?

**Comment by Matt-S6** [comment]
Just to verify that's `sparksql-scalapb-0.11.0` not `sparksql-scalapb-0.11.0-RC1` , correct?

**Comment by thesamet** [comment]
Correct.

**Comment by Matt-S6** [comment]
We're jumping down the rabbit hole now... running `sbt clean && sbt assembly` on the master branch of `sparksql-scalapb-test` with only the following lines changed in `build.sbt` 
```
libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % "3.1.2" % "provided",
  "org.apache.spark" %% "spark-sql" % "3.1.2" % "provided",
  "com.thesamet.scalapb" %% "sparksql-scalapb" % "0.11.0"
)
```
Issues the following compiler errors:
```
...
[info] compiling 5 Scala sources to /home/mdavis/sparksql-scalapb-test/target/scala-2.12/classes ...
[error] /home/mdavis/sparksql-scalapb-test/target/scala-2.12/src_managed/main/com/example/protos/demo/Person.scala:120:102: type HasBuilder is not a member of package scalapb
[error] object Person extends scalapb.GeneratedMessageCompanion[com.example.protos.demo.Person] with scalapb.HasBuilder[com.example.protos.demo.Person] {
[error]                                                                                                      ^
[error] /home/mdavis/sparksql-scalapb-test/target/scala-2.12/src_managed/main/com/example/protos/demo/Person.scala:121:113: type HasBuilder is not a member of package scalapb
[error]   implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.example.protos.demo.Person] with scalapb.HasBuilder[com.example.protos.demo.Person] = this
[error]                                                                                                                 ^
[error] /home/mdavis/sparksql-scalapb-test/src/main/scala/RunDemo.scala:22:56: could not find implicit value for evidence parameter of type scalapb.GeneratedMessageCompanion[com.example.protos.demo.Person]
[error]     val personsDF: DataFrame = ProtoSQL.createDataFrame(spark, testData)
[error]                                                        ^
[error] /home/mdavis/sparksql-scalapb-test/target/scala-2.12/src_managed/main/com/example/protos/demo/Address.scala:74:104: type HasBuilder is not a member of package scalapb
[error] object Address extends scalapb.GeneratedMessageCompanion[com.example.protos.demo.Address] with scalapb.HasBuilder[com.example.protos.demo.Address] {
[error]                                                                                                        ^
[error] /home/mdavis/sparksql-scalapb-test/target/scala-2.12/src_managed/main/com/example/protos/demo/Address.scala:75:114: type HasBuilder is not a member of package scalapb
[error]   implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.example.protos.demo.Address] with scalapb.HasBuilder[com.example.protos.demo.Address] = this
[error]                                                                                                                  ^
[error] /home/mdavis/sparksql-scalapb-test/target/scala-2.12/src_managed/main/com/example/protos/demo/Person.scala:180:98: could not find implicit value for parameter cmp: scalapb.GeneratedMessageCompanion[com.example.protos.demo.Address]
[error]             __addresses += _root_.scalapb.LiteParser.readMessage[com.example.protos.demo.Address](_input__)
[error]                                                                                                  ^
[error] 6 errors found
[error] (Compile / compileIncremental) Compilation failed
```

**Comment by thesamet** [comment]
You also need to update the ScalaPB version to 0.11.x (latest is 0.11.6) in `project/scalapb.sbt`, clean and rebuild.

**Comment by Matt-S6** [comment]
updated to 9.1 LTS (Spark 3.1.2, Scala 2.12), scalapb 0.11.6, sparksql-scalapb 0.11.0, but same outputs. Works on local open source spark, but fails with `java.lang.VerifyError: class frameless.functions.Spark2_4_LambdaVariable overrides final method genCode` on databricks cluster.

**Comment by Matt-S6** [comment]
another follow up: looks like things work when just using the Dataset/DataFrame api (rather than the ProtoSQL.udf). 
```
val parsedDF = binaryDS
      .select(F.col("value"))
      .as[Array[Byte]]
      .map(Person.parseFrom(_))
```
Works fine on databricks cluster.

**Comment by Matt-S6** [comment]
I've identified work-around for our use-case using dataset api and joining original dataframe via unique identifier. Inefficient, but it'll work for now. Full example can be found here: https://github.com/Matt-S6/sparksql-scalapb-test/blob/1290718a329296b6f5475a2e4b332a68a56ae4c0/src/main/scala/RunDemo.scala
Looking forward to getting to the bottom of this with the folks from databricks and any updates to the frameless functions (thanks for putting in the ticket @thesamet). Leaving this issue closed as I don't believe there's any todo's for the scalapb repo at this time.

**Comment by thesamet** [comment]
It turns out Frameless already supports Spark 3.2 and it now ships with artifacts for each supported version of Spark (3.0, 3.1, 3.2). I'll set up sparksql-scalapb to cross-compile and publish in a similar way so it's easier to pick the Spark/ScalaPB combination you need.
