### ISSUE TITLE
[ScalaPB-Json4s] Make Default 'ignoringUnknownFields' = 'true'

### ISSUE THREAD

**Issue by micmorris** [scalapb/ScalaPB#1277]
When receiving an additional field because of a forward-compatible change that a client has not adopted yet, the client will fail with `Cannot find field: ...`. This is because ['ignoringUnknownFields' defaults to 'false'](https://github.com/scalapb/scalapb-json4s/blob/master/src/main/scala/scalapb/json4s/JsonFormat.scala#L477). 

This makes the JSON client not forwards-compatible by-default.

It also seems weird given that `unknownFields` for models are created by the code generator by-default.

**Comment by thesamet** [comment]
Thanks for the feedback. The default behavior is modeled after the JSON spec for protobuf at https://developers.google.com/protocol-buffers/docs/proto3#json_options:

> Ignore unknown fields: Proto3 JSON parser should reject unknown fields by default but may provide an option to ignore unknown fields in parsing.

**Comment by micmorris** [comment]
(First of all, I'm a big fan, thanks for all your work on this project! it's easily one of my favorite Scala libraries ❤️ )

Ok it is technically in-line with the Proto spec...

However, it was still very shocking when I shipped what I expected was a forward-compatible change (adding an optional field in a response) and then 100% of my requests were failing deser on the caller because the field was being sent back.

Honestly, I was expecting this on by-default because the permissive nature of clients is a big selling point of using Proto. At minimum, it would be good to put a warning about forwards-compatibility in the docs to be searchable. 🙏 

Ideally with an example snippet, I was trying to figure out `Printers` and `Parsers` when their API was actually really simple in the end. Here's an example I used:

```scala
import scalapb._
import scalapb.json4s.{Parser, Printer}

import scala.util.Try

trait ProtoJsonProtocol {

  val pbJsonPrinter: Printer = new Printer()
  val pbJsonParser: Parser = new Parser().ignoringUnknownFields

  implicit class ProtoSerializer[T <: GeneratedMessage](proto: T) {
    def protoToJson: String = {
      pbJsonPrinter.print(proto)
    }
  }

  implicit class ProtoDeserializer(protoJson: String) {
    def jsonToProto[T <: GeneratedMessage: GeneratedMessageCompanion]: T =
      pbJsonParser.fromJsonString[T](protoJson)

    def jsonToMaybeProto[T <: GeneratedMessage: GeneratedMessageCompanion]: Try[T] =
      Try(protoJson.jsonToProto)
  }

}
```

**Comment by thesamet** [comment]
Thanks Michael. I'd assume the spec designers wanted to have new solutions throw an error in presence of unknown fields rather than having the error silently ignored (with the data permanently lost), so developers can detect that early (like in your case) and update the setting when being informed of the possibility of information loss...

I brought the docs up to par with all the parser docs we currently support: https://github.com/scalapb/ScalaPB/commit/90bf24e200c63527a7fa0b5518423da60e4b7691
