### ISSUE TITLE
enum_strip_prefix = true, don’t remove prefix from generated field name value

### ISSUE THREAD

**Issue by edenrose** [scalapb/ScalaPB#1319]
Hey, 
I'm trying to remove the protobuf enum prefix from the generated enum by specifying the `option (scalapb.options).enum_strip_prefix = true;`  but it seems to leave the prefix in the generated name field :\

for example : 

`
option (scalapb.options).enum_strip_prefix = true;
option (scalapb.options).enum_value_naming = CAMEL_CASE;

enum Food {
    FOOD_PIZZA = 1;
    FOOD_ICE_CREAM = 2;
}

object Food  {
  
   (1) // I expect :
   case object Pizza extends Food {
       val value = 1;
       val name = "Pizza"
  }

   (2) // But get:
   case object Pizza extends Food {
       val value = 1;
       val name = "FOOD_PIZZA"
  }
}
`
Is there a a way to get (1) ?

**Comment by thesamet** [comment]
Hi Eden, see explanation and solution here: https://github.com/scalapb/ScalaPB/issues/1201
