### ISSUE TITLE
Imports stated in transformers are not added to grpc classes. 

### ISSUE THREAD

**Issue by borissmidt** [scalapb/ScalaPB#1332]
when i include transformers like:
it seems that the models pick up the imports of the converters properly but any service generated source file does not pick up this import statement.

package com.restore
option (scalapb.options) = {
  scope: PACKAGE
  import: "com.restore.protobuf.ProtobufConversions.{durationToProto, periodToProto, frequencyToProto, powerToProto, energyToProto, intervalToJoda, timestampToJoda}"

so in the generated sources i see in all source under of package com.restorean

import com.restore.protobuf.ProtobufConversions.{durationToProto, periodToProto, frequencyToProto, powerToProto, energyToProto, intervalToJoda, timestampToJoda}

but for the Service files (ending with Grpc) the import is missing causing my build to fail.

i'm using the 11.9 version of scalapb

**Comment by borissmidt** [comment]
@thesamet Do you have a timeframe for when these changes will be released?

**Comment by thesamet** [comment]
@borissmidt 0.11.10 is on its way.

**Comment by borissmidt** [comment]
Cool, thank you :)
