### ISSUE TITLE
Add package names for other languages

### ISSUE THREAD

**Issue by regiskuckaertz** [scalapb/ScalaPB#1334]
Hi there!

We've been using zio-grpc to build an API that we intend to expose to our clients, with the intent to publish the IDL so they can generate their own API clients. I tried building a go example but it failed because the scalapb proto file did not have a `go_package` option.

Could the following options be added: `csharp_namespace`, `go_package`, `php_namespace` and `ruby_package`?

Happy to raise a PR myself, just need to know what values would make sense?

**Comment by thesamet** [comment]
Hi @regiskuckaertz , yes, I'm fine with this. Can you send a PR?
