### ISSUE TITLE
Validation skipping not always possible

### ISSUE THREAD

**Issue by 11Dimensions** [scalapb/ScalaPB#1358]
When referencing an 3rd party protobuf that does not use validation and defines its own package properties it is not possible to use the validation `skip` feature due to package properties already being defined by the 3rd pary. 

An example of this is `proto-google-common-protos-scalapb` where settings are defined for the `google` package but no validations are defined.
Using this package in a project that uses validation and refers to this results in the following error
```object TimeOfDayValidator is not a member of package com.google.type.timeofday```

Since we cannot use `skip` without colliding with the 3rd party there is currently no way to specify a boundary to stop validation of 3rd party protos.

A minimal example can be found [here](https://github.com/11Dimensions/simple-scalapb-project)

**Comment by thesamet** [comment]
I am thinking of possible solutions to this. One of which is to allow multiple package-scoped options per package. However, before adding this complexity, if it would be a reasonable in your use case to add a `skip` at the sub-package level for each `google` package you are using. For example, for `google.type` you can place a file called `options-google-type.proto`:

```
syntax = "proto2";

import "scalapb/scalapb.proto";
import "scalapb/validate.proto";

package google.type;

option (scalapb.options) = {
  scope: PACKAGE
  [scalapb.validate.file] { skip: true }
};
```

**Comment by 11Dimensions** [comment]
This solves my problem I think in a way that multiple packaged scoped options would. And this seems like a clean enough work around as well.
FMI what is the semantic difference between using `package google.type` and `package google`?

**Comment by thesamet** [comment]
It means that the options apply to the package `google` and all its subpackages. When using `google.type` the options are for that package and its subpackages. I am not sure if this is what you wanted to know, if not please clarify.
