### ISSUE TITLE
Service with preamble broken in v0.11.10

### ISSUE THREAD

**Issue by andrew-teirney** [scalapb/ScalaPB#1367]
Upon updating to v0.11.10 I encountered a number of errors in the form "... is already defined ..."

I believe the fix that was implemented for #1332 introduced a bug that results in the preamble being emitted for services files, in addition to the single message file emitted with `single_file: true`.

This can result in multiple definitions of types, and other side effects depending on what the preamble contains.

**Comment by thesamet** [comment]
Thanks for reporting. The fix above makes preamble only appear in message files and not in service files. I also suggest that if you have definitions, move them to a separate file in your Scala source directory and only have imports in the generated code.
