### ISSUE TITLE
`uint64` generates a `Long` which can't represent everything a `uint64` can

### ISSUE THREAD

**Issue by benthecarman** [scalapb/ScalaPB#1368]
In one of the protos I am using it has a `uint64 chan_id = 2`, which when generated creates `chanId: _root_.scala.Long = 0L`.

However I have a `chanId` of `18114587244887524324` which can't be represented by `Long` and thus isn't able to be passed in. Ideally this should be made to be something like `BigInteger`.

**Comment by thesamet** [comment]
Hi @benthecarman , this is consistent with the Java protobuf implementation (see https://developers.google.com/protocol-buffers/docs/proto3#scalar):

> In Java, unsigned 32-bit and 64-bit integers are represented using their signed counterparts, with the top bit simply being stored in the sign bit.

For your specific use case, you can make ScalaPB use `BigInteger` by taking advantage of ScalaPB custom types: https://scalapb.github.io/docs/customizations/#custom-types

Using [field transformation](https://scalapb.github.io/docs/transformations), you can make it apply by default for all long fields.

**Comment by benthecarman** [comment]
Thanks!

**Comment by benthecarman** [comment]
Do you know any examples of this, keep finding bugs in my own impl

**Comment by thesamet** [comment]
Hi @benthecarman , can you give an example of the uint32 test fails? Response may be delayed as I'm out of town.

**Comment by benthecarman** [comment]
I was just using Unt32.max - 1
