### ISSUE TITLE
Feature request: add the ability to change the name of a rpc function

### ISSUE THREAD

**Issue by benthecarman** [scalapb/ScalaPB#1402]
I am trying to use a proto file that has an rpc function called `close` which overlaps with akka's grpc close function. Ideally I could add something to rename this function to something else so I can get around this issue.

Me I posted this question gitter @thesamet told me:

> Hi @benthecarman , no, there isn't [the ability to do that]. Feel free to file a feature request in scalapb repo on github, please indicate if you're available to work on the PR. It shouldn't be hard to implement by adding an extension of MethodOptions and following existing patterns in the project.

I am likely unavailable to do this but would love if someone else could! Could offer a small bitcoin bounty for it :)

**Comment by thesamet** [comment]
Thanks for reporting, @benthecarman . This sounds like an akka-grpc issue then, which is develoepd by a different team. Can you file a new issue, include the error you are getting, in the akka-grpc project at https://github.com/akka/akka-grpc/issues

**Comment by benthecarman** [comment]
I still think this could be a useful feature

**Comment by thesamet** [comment]
I agree, since you are using akka-grpc (not ScalaPB's built-in grpc support) you need this feature implemented in akka-grpc so the issue/feature request belongs there. The solution is likely to involve a change to scalapb.proto and descriptor implicits within this project and I'll be happy to support this part.
