### ISSUE TITLE
[proposal] Allow Custom Generator Options

### ISSUE THREAD

**Issue by Joshua-Scurr** [scalapb/ScalaPB#1440]
In some cases, it would be beneficial to be able to supply custom options when generating code.

# An Example

We have a custom SBT plugin that uses ScalaPB to compile ProtoBuf files into both Scala and OpenAPI JSON; we use this within a separate project, where we specify the `.proto` files to be compiled. Within the OpenAPI specification, there is a field specifying the version of the API:

```json
{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "...",
    "description" : "...",
    "version" : "1.0.0"
  },
  ...
}
```

At present, we have to manually update it, by modifying the source of the plugin, recompiling it, then then using that to generate the API spec. We would like to cut out this time-consuming and error-prone process, and to provide the generator plugin with the current API version each time it is used.

# Miscellaneous Details

It is possible to obtain build information from SBT within a Scala source file with, eg. `BuildInfo.version`. We have investigated using this, but it (unsurprisingly) takes the version used by the custom generator plugin, and not the project containing the ProtoBuf, resulting in incorrect versions, so this is not suitable.

`GeneratorOption.scala` defines a number of `GeneratorOption` case objects, which can be use to control certain aspects of generation. It might be possible to allow extension of this for custom options?

It is unfortunately not practical for us to combine the generator plugin into the project containing the ProtoBuf; this would otherwise solve the problem.

We have a number of case classes which define the various aspects of the OpenAPI spec:

```scala
final case class OpenApi(
  ...
  info: Info,
  ...
)

final case class Info(
  ...
  version: String
  ...
)
```

**Comment by thesamet** [comment]
Hi @Joshua-Scurr ,
I read the write up a few times and trying to make sure I understand the problem you are trying to solve. Here's what I got: you generate an OpenAPI JSON file using your own protoc plugin, and you want the generated file to include a version number that is known to SBT. It is possible to pass custom parameters to protoc plugins through sbt-protoc. If you follow [writing custom plugins](https://scalapb.github.io/docs/writing-plugins/) look for `request.parameters` to see how these can become available in your code generator.

**Comment by Joshua-Scurr** [comment]
That sounds correct; thanks you - I will have a look at that this morning

**Comment by regiskuckaertz** [comment]
@thesamet it looks like indeed this is turned into a closed vocabulary of parameters, here:

https://github.com/scalapb/ScalaPB/blob/3188058f2d348298c1d4ce93f582a59a9dae486e/compiler-plugin/src/main/scala/scalapb/compiler/GeneratorParams.scala#L30-L56

do you think we could change `GeneratorParams` to:

```
case class GeneratorParams(
    javaConversions: Boolean = false,
    flatPackage: Boolean = false,
    grpc: Boolean = false,
    singleLineToProtoString: Boolean = false,
    asciiFormatToString: Boolean = false,
    lenses: Boolean = true,
    retainSourceCodeInfo: Boolean = false,
    customOptions: List[String] = Nil
)
```
... then all the unrecognized options end up in `customOptions` and do not generate an error?

**Comment by thesamet** [comment]
The success type of `fromStringCollectUnrecognized` is a `(GeneratorParams, Seq[String])`. The `Seq[String]` represents all the options that are not ScalaPB options, for third-party code generators to process further.

**Comment by Joshua-Scurr** [comment]
That looks to have been the answer. Many thanks!
