### ISSUE TITLE
Efficiently convert bytes to strings

### ISSUE THREAD

**Issue by jCalamari** [scalapb/ScalaPB#1484]
In ScalaPB, what's the best way of converting message A to message B, knowing that message A can contain thousands of elements? Ideally, I would like to just pass the bytes from A to B without copying/looping.

```proto
message A {
  repeated bytes a_strings = 1;
}
```

```proto
message B {
  repeated string b_strings = 1;
}
```

Naive approach would look as follows, however there is just too much copying/looping:

```scala
val a: A = ...
val b: B = B(a.a_strings.map(ByteString.copyFromUtf8))
```

**Comment by thesamet** [comment]
Context would be more helpful to answer this since you haven't stated where `A` comes from and how you want to use the `B`s. A few thoughts:
1. `A` and `B` have the same binary representation. So if you have `A` available in binary forms, just parse it using `B.parseFrom` and then you get efficiency by not instantiating `A`s.
2. Don't create messages of type `B`, convert the bytes to string at the time of access. You could add a base trait to `A` that has a method like `def getString(index: Int): String = ByteString.copyFromUtf8(a_strings(i))`

**Comment by jCalamari** [comment]
Hi @thesamet,

thanks for prompt response! `A` message comes from [API response](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor.proto#L59) and there is no way to avoid creating `A` message. Sadly `A` and `B` don't have the same binary representation (I formed the example wrong), they have many more fields and their field IDs don't match. Since I am working with akka-grpc ecosystem, delaying creation of `B` is not an option. Is there a way to create instance of `B`  just by providing bytes for `b_strings` field?

**Comment by thesamet** [comment]
Do you own the proto for `B`? If so, you can leave the proto type as bytes, but similar to (2) above add a base trait that converts to strings only what you need. Then, the creation of this field is just assigning the same reference of `Seq[ByteString]`.

**Comment by jCalamari** [comment]
> Do you own the proto for `B`? If so, you can leave the proto type as bytes, but similar to (2) above add a base trait that converts to strings only what you need. Then, the creation of this field is just assigning the same reference of `Seq[ByteString]`.

This sounds promising. What would happen to already compiled clients who would expect `repeated string` but got `repeated bytes`?

**Comment by thesamet** [comment]
The binary representation is the same. Running clients will not be impacted when this change rolls out to a server.

**Comment by jCalamari** [comment]
> The binary representation is the same. Running clients will not be impacted when this change rolls out to a server.

Worked like a charm, thank you very much for your prompt responses!
