### ISSUE TITLE
Protobuf map with message as value won't compile

### ISSUE THREAD

**Issue by oscar-broman** [scalapb/ScalaPB#1500]
```protobuf
message Foo {
  double a = 1;
  double b = 2;
}

message Bar {
  map<string, Foo> test_map = 1;
}
```

Output:
```
[error] -- [E008] Not Found Error: [...]/Bar.scala:221:144
[error] 221 |      _root_.scalapb.TypeMapper[Bar.TestMapEntry, (_root_.scala.Predef.String, Foo)](__m => (__m.key, __m.getValue))(__p => Bar.TestMapEntry(__p._1, Some(__p._2)))
[error]     |value getValue is not a member of Bar.TestMapEntry - did you mean __m.withValue?
[error] one error found
```

**Comment by thesamet** [comment]
Hey @oscar-broman , sorry for the late response. I missed the notification. I am not able to reproduce the problem on a vanilla project created with `sbt new scalapb/scalapb-template.g8` - the scenario you reporting is fairly basic and well covered under our tests, so I assume it's a local issue or missing information.  Can you share an entire minimal project reproducing this?

**Comment by thesamet** [comment]
I was able to reproduce it. Will take a closer look soon.
