### ISSUE TITLE
Custom target directory breaks incremental compilation

### ISSUE THREAD

**Issue by oscar-broman** [scalapb/ScalaPB#1561]
1. Clone this repo: https://github.com/oscar-broman/scalapb-issue-1561
2. Run `sbt compile` - that should compile just fine
3. Run `sbt compile` once more - now an error should occur

Note that the only special thing about the repo is [this line](https://github.com/oscar-broman/scalapb-issue-1561/blob/c4633cfd5c033a5fbe40c983464eb7d5e04adb4d/build.sbt#L5).

**Comment by thesamet** [comment]
I was able to reproduce. The error I am seeing is:

```
test.proto:3:1: Import "scalapb/scalapb.proto" was not found or had errors.
```

From initial investigation, it looks like `protocUnpackDependencies` either doesn't extract or immediately deletes `scalapb.proto`. It would be great if someone can continue to investigate.
