### ISSUE TITLE
JSON serialization of Any message fails when the message has a special JSON representation

### ISSUE THREAD

**Issue by oridag** [scalapb/ScalaPB#1612]
The `Any` JSON printer assumes that the json representation of the concrete message is a `JObject` and it then adds the special field `@type` to that `JObject`, but when the concrete message has a non-object representation (e.g. `Timestamp`, `Value`) it fails with something like 
```
java.lang.IllegalStateException: Message of type type.googleapis.com/google.protobuf.Value emitted non-object JSON: JNull
```

For reference, the way the Java implementation handles it is by nesting the whole message in an inner field named "value" e.g.:
```
{
  "f": {
    "@type": "type.googleapis.com/google.protobuf.Timestamp",
    "value": "1970-01-01T00:00:00Z"
  }
}
```

**Comment by thesamet** [comment]
Hi @oridag , I [added a test](https://github.com/scalapb/scalapb-json4s/commit/2afe38f58a5119f8d33a49f6fb625ac36602ddc8) with your example and wasn't able to reproduce it. It looks like both serialization and deserialization of Timestamps work in the Java format you described above. I believe this has been fixed earlier this year  2023 in scalapb-json4s 0.12.1 - are you on it?

**Comment by oridag** [comment]
@thesamet you are totally right, I was on 12.0 and it seems to be working correctly with 12.1, sorry!
I'll be closing this now
