### ISSUE TITLE
scalapb grpc runtime & InProcessTransport

### ISSUE THREAD

**Issue by hugebdu** [scalapb/ScalaPB#1614]
Hello codegen wizards.

Any plans/thoughts on skipping the serialization completely like in [java-grpc](https://github.com/grpc/grpc-java/blob/master/protobuf-lite/src/main/java/io/grpc/protobuf/lite/ProtoLiteUtils.java#L171-L181) in case the [InProcessTransport](https://github.com/grpc/grpc-java/blob/master/inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java) is used?

**Comment by thesamet** [comment]
This wasn't on my list - PR will be welcome!

**Comment by hugebdu** [comment]
@thesamet thanks for your quick response.
I can give it a try.
May I ask which IDE you're using? `CONTIBUTING.md` does not mention anything about it.
I tried using IntelliJ IDEA, however seems like [it has a problem with sbt-projectmatrix](https://github.com/sbt/sbt-projectmatrix/issues/25)

**Comment by hugebdu** [comment]
@thesamet Thanks!

**Comment by thesamet** [comment]
@hugebdu Sorry for missing the question up there - but I use VS Code with Metals.
