### ISSUE TITLE
Unrecognized enum serialized as int

### ISSUE THREAD

**Issue by jessebutterfield** [scalapb/ScalaPB#1619]
When upgrading scalapb-json4s from 0.12.0 to 0.12.1 unknown enums switch from being serialized as strings to numbers which breaks our type assumptions. In version 0.12.0, for an enum called Gender an unknown enum would serialize like `{"gender":"UNKNOWN_ENUM_VALUE_Gender_99"}` while in 0.12.1 it serializes as `{"gender":99}` which then is unexpectedly of type number rather than string.

**Comment by thesamet** [comment]
Hi @jessebutterfield , thanks for reporting. This is an intended change to conform to the [official protobuf implementation](https://github.com/protocolbuffers/protobuf/blob/5ce86a675ea4cfc9dcfc54a9be6141ea6bc371b6/conformance/binary_json_conformance_suite.cc#L2297-L2303). 

Is it possible for you to update your project(s) to conform to the standard? If not, I'd be open for a PR that would add a flag that will hold the previous behavior (which would be removed in the 0.13.x series)

**Comment by jessebutterfield** [comment]
> Is it possible for you to update your project(s) to conform to the standard? If not, I'd be open for a PR that would add a flag that will hold the previous behavior (which would be removed in the 0.13.x series)

Interesting. Thanks for the quick response. I'm sure we can figure something out. I guess we'll either find a way to make them union types or filter out the unrecognized responses.
