### ISSUE TITLE
Type Mismatch Error with `asRecognized` in versions 0.11.14 and 0.11.15

### ISSUE THREAD

**Issue by Gor027** [scalapb/ScalaPB#1637]
A type mismatch error occurs with `asRecognized` method on an enum value generated from a .proto file. The error message indicates that there is a requirement for `RecognizedType` when it is expected to return `Recognized`.

### Example .proto file

```Protobuf
syntax = "proto3";

message Request {
    message Target {
        enum Kind {
            UNSPECIFIED = 0;
            // Other enum values ...
        }

        Kind kind = 3;
    }

    Target target = 1;
}
```

### The generated Scala code

```Scala
trait GeneratedEnum extends Any with Product with Serializable {
  type EnumType <: GeneratedEnum

  def value: Int

  def index: Int

  def name: String

  override def toString = name

  def companion: GeneratedEnumCompanion[EnumType]

  def isUnrecognized: Boolean = false

  def javaValueDescriptor: JavaDescriptors.EnumValueDescriptor =
    companion.javaDescriptor.getValues().get(index)

  def scalaValueDescriptor: _root_.scalapb.descriptors.EnumValueDescriptor =
    companion.scalaDescriptor.values(index)
}

// ... unrelated generated code

object Request extends ... {
  object Target extends ... {
    sealed abstract class Kind(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
      type EnumType = Kind
      def isUnspecified: _root_.scala.Boolean = false
      def companion: _root_.scalapb.GeneratedEnumCompanion[Kind] = Request.Target.Kind
      final def asRecognized: _root_.scala.Option[Request.Target.Kind.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[Request.Target.Kind.Recognized])
    }

    object Kind extends _root_.scalapb.GeneratedEnumCompanion[Kind] {
      sealed trait Recognized extends Kind
      implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[Kind] = this
      
      @SerialVersionUID(0L)
      case object UNSPECIFIED extends Kind(0) with Kind.Recognized {
        val index = 0
        val name = "UNSPECIFIED"
        override def isUnspecified: _root_.scala.Boolean = true
      }
    }
  }
}
```

### Compilation Error

```
/some/path/File.scala:100:19: incompatible type in overriding
[error] def asRecognized: Option[Request.Target.Kind.UNSPECIFIED.RecognizedType] (defined in trait GeneratedEnum)
[error]   with final def asRecognized: Option[Request.Target.Kind.Recognized] (defined in class Kind);
[error]  found   : Option[Request.Target.Kind.Recognized]
[error]  required: Option[Request.Target.Kind.UNSPECIFIED.RecognizedType]
[error]       case object UNSPECIFIED extends Kind(0) with Kind.Recognized {
```

The compiler requires `RecognizedType` which is weird as such a type or a similar one was not present in the generated code or the overall project codebase.

### Notes

This issue has been observed in the context of a project using gRPC services. The compiler does not complain with version 0.11.13 and below, however, those versions contain vulnerabilities that cannot be tolerated in the project.
The issue is related to #1489. Perhaps @xuwei-k has better insight on the issue.

**Comment by thesamet** [comment]
I tried to reproduce this in 705a9aa, though it works locally (currently waiting on CI). Is it possible you haven't regenerated the code after bumping up the version? Try `clean` inside `sbt`.

**Comment by Gor027** [comment]
I called `sbt clean` before each local build, but every time it complained requiring `RecognizedType` which does not exist in the codebase including the generated code. It fails with the same error in CI which does not involve build caches. Is it possible that the code generation can be affected by other libraries or plugins like `sbt-protoc` or `zio-grpc-codegen`?

**Comment by Gor027** [comment]
Fixed it by explicitly importing `compilerplugin` version `0.11.15`. I found that earlier `0.11.8` was used which caused incompatibility when I upgraded `scalapb-runtime-grpc` to version 0.11.15.
Sorry for the noise.
