### ISSUE TITLE
remove with* methods form generated code in favor of .copy

### ISSUE THREAD

**Issue by cvogt** [scalapb/ScalaPB#164]
WDYT?

Also see https://trueaccord.github.io/ScalaPB/generated-code.html

**Comment by nadavsr** [comment]
In proto2 and for messages in proto3, `p.withX(y)` is equivalent to `p.copy(x=Some(y))`, so the former is arguably nicer (and can't be removed without breaking people's work). What's the concern with the with* methods?

**Comment by cvogt** [comment]
Here is my view. Let me know what you think:

I know that this is will only make a small difference on it's own. But I think every place like this we can simplify in the Scala ecosystem is a small win and adds up. Knowledge re-use is ultra powerful and one of the reasons we love FP. Re-use of concepts and apis.

Here my abstract blabber applies like this: This implements an alternative non-standard way of doing this, when there is already .copy as the idiomatic Scala way of doing this, right? I am under the impression that this makes code and apis harder to work with. People who know Scala well will wonder about the semantic difference to .copy when reading code (if they can guess the vague meaning from the name). Scala newbies will potentially learn something less useful than .copy or redundant to .copy (if they know it already), while they could have used that energy on something else. Both groups have to learn and maintain this library specific api, while there is a general purpose one. We use many libraries and the mental budget for remembering library specific things is limited. (Java converts may welcome this more familiar api, but may miss the chance to learn the more useful .copy ;)).

Math took this idea to the extreme and has many symbols that have no meaning on their own. But standardizing their meaning across the mathematic community around the world makes it work. Hard to pick up at first, but very re-usable. I wouldn't go as far and say names don't matter. But if there is a decent standard name, let's use that (.copy) and not call it something else (with*), because it may (subjectively) seem nicer.

I know I am a bit of a purist in this regard. I am totally fine if you see it differently, but wanted to at least make sure the idea of removing redundancy from the api is considered. And I love this quote:

> Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.

:)

**Comment by thesamet** [comment]
Thanks, I see your argument. I still think the `withX(y)` methods add some useful convenience, especially in presence of `Option`s (similar argument to why lenses are useful), and I am hesitant to break existing users' code.

**Comment by cvogt** [comment]
fair enough :)

**Comment by ngbinh** [comment]
is it a way to have this option enabled under an option? Our models contribute to a significant portion of the final JS size on our web app.

**Comment by thesamet** [comment]
@ngbinh , the fast optimizer is supposed to remove unused code - doesn't that happen?

**Comment by ngbinh** [comment]
I am not really sure about that. Will check and report back here. One thing we know for sure is our protobuf models increase our final fullOpt JS size significantly.

**Comment by thesamet** [comment]
Would be happy to explore how to reduce code size, though removing unused code shouldn't have an impact with full optimization in JS. If you can take a look and try to get an assessment of what's taking more space that could be helpful. You can also try to removing lenses (`no_lenses` option)

**Comment by ngbinh** [comment]
We already use `no_lenses` on the JS size
