### ISSUE TITLE
Support Scala 3.4 type wildcards

### ISSUE THREAD

**Issue by saeltz** [scalapb/ScalaPB#1662]
ScalaPB works just fine up to Scala 3.3.3. Yesterday, I was hunting down a bug in Chimney (https://github.com/scalalandio/chimney/issues/479) and wanted to check if it still exists in Scala 3.4.

After updating [my branch](https://github.com/moia-oss/teleproto/tree/chimney2) to Scala 3.4 compiling the tests started failing because some protos are compiled into Scala as well. Scala 3.4 deprecated the underscore syntax for type wildcards (https://github.com/scala/scala3/pull/18813). With fatal warnings enabled, one gets the warnings below:

```
[error] -- Error: /teleproto/target/scala-3.4.0/src_managed/test/scalapb/io/moia/migration/migration/V3.scala:71:106 
[error] 71 |  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
[error]    |                                                                                                          ^
[error]    |`_` is deprecated for wildcard arguments of types: use `?` instead
[error]    |This construct can be rewritten automatically under -rewrite -source 3.4-migration.
```

The rewrite isn't an option here since we're talking about target files.

Do you have plans to fix this issue? I don't fell comfortable disabling fatal warnings.

**Comment by thesamet** [comment]
Please search for `scala3_sources` at https://scalapb.github.io/docs/customizations/ - the option is available as a generator parameter or package option.

**Comment by saeltz** [comment]
Thanks! I totally missed that configuration option. Solved it via `scalapb.gen(scala3Sources = true)`.
