### ISSUE TITLE
Shade protobuf-java dependency

### ISSUE THREAD

**Issue by Dao007forever** [scalapb/ScalaPB#167]
Other dependencies (in our case Kinesis-client) depend on a specific version of protobuf-java, which we can't change. It'd be great if we can provide a shade version for the generated code and a shaded ScalaPB-runtime which uses a shaded version of protobuf-java.

**Comment by thesamet** [comment]
Is this something you can do within your own build? We do something similar for SparkSQL and we shade our fat jar like this http://trueaccord.github.io/ScalaPB/sparksql.html

**Comment by Dao007forever** [comment]
As we don't use Sbt, another way of doing this in ScalaPbc as an option would be great.

**Comment by thesamet** [comment]
The shading step should be performed at the application's site when building a fat jar - not by individual library publisher. The reason is that anything that depends on ScalaPB (including software we have no control over) would have to be shaded in order to work with the shaded version.
