### ISSUE TITLE
JsonFormat.toJsonString omits authorisation string in the output JSON

### ISSUE THREAD

**Issue by mattiapitossi** [scalapb/ScalaPB#1681]
Hi all, I'm encountering an issue with the `JsonFormat.toJsonString` method from the `scalapb-json4s` library where it does not parse certain protobuf events correctly. Specifically, it seems to omit the `role` field with the value "authorisation" from the resulting JSON.

**To Reproduce**
1. Use `JsonFormat.toJsonString` to serialize the following protobuf object to JSON:
protostring:
    
    ```{
       authorisations {
      operator {
        username: "name"
      }
      role: authorisation
    }
    authorisations {
      operator {
        username: name"
      }
      role: confirmation
    }}
    ```

2. The resulting JSON is missing the "authorisation" role:

    ```
      {
        "authorisations": [
          {
            "operator": {
              "username": "name"
            },
            "role": "confirmation"
          },
          {
            "operator": {
              "username": "name"
            }
          }
        ]
      }
    ```
    
If I try to use "authorisation" it always disappear, no matter the position.

**Expected behavior**
The expected output should retain all roles as specified in the original protobuf object, including the "authorisation" role.

**Actual behavior**
The `role` field with the value "authorisation" is omitted from the output.

**Environment:**
- Library version: [0.12.1]
- Scala version: [2.13.13]

Thanks!

**Comment by thesamet** [comment]
Hi @mattiapitossi , does `confirmation` happen to be the default value of the enum - that means has value `0` in the proto definition?

If so, this is up to spec: https://protobuf.dev/programming-guides/proto3/#json
> When generating JSON-encoded output from a protocol buffer, if a protobuf field has the default value and if the field doesn’t support field presence, it will be omitted from the output by default. An implementation may provide options to include fields with default values in the output.

The library provides an option to print default values which is documented here: https://scalapb.github.io/docs/json/#more-printing-and-parsing-options

Hope this helps - if not, please provide the proto definition and code to reproduce.

**Comment by mattiapitossi** [comment]
Yes, that was the issue, now it works. 

Many thanks @thesamet for the quick and helpful response!
