### ISSUE TITLE
pin to protobuf 3.x

### ISSUE THREAD

**Issue by pjfanning** [scalapb/ScalaPB#1697]
I'm a committer to Apache Pekko gRPC and we are sticking to protobuf 3.

https://github.com/grpc/grpc-java/issues/11015 summarises the reasons we are sticking.

Pekko gRPC codegen module is built on top of ScalaPB.

Would it be possible to have ScalaPB stick with protobuf 3? Or alternatively, could you keep 0.11.x for protobuf 3 and 0.12.x for protobuf 4?

**Comment by thesamet** [comment]
That's the plan. 0.11.x will stick to protobuf 3, and 0.12.x will be on protobuf 4.
