### ISSUE TITLE
Publish new Maven release for v0.11.16

### ISSUE THREAD

**Issue by pkwarren** [scalapb/ScalaPB#1700]
We package ScalaPB for Buf here: https://github.com/bufbuild/plugins/tree/main/plugins/community/scalapb-scala. There appears to be a new release v0.11.16 available, however we're not seeing the protoc plugin published at the normal location (https://repo1.maven.org/maven2/com/thesamet/scalapb/protoc-gen-scala/0.11.16/protoc-gen-scala-0.11.16-unix.sh).

Is there a second step required to publish artifacts to Maven central?

**Comment by thesamet** [comment]
There was a failure in the release process of 0.11.16 and not all artifacts
have been published. I will take a look later.

**Comment by thesamet** [comment]
Please skip 0.11.16. Released 0.11.17

**Comment by pkwarren** [comment]
0.11.17 worked great - thanks!
