### ISSUE TITLE
Spark 3.5: NoSuchMethodErorr

### ISSUE THREAD

**Issue by CrawFishFiesta** [scalapb/ScalaPB#1714]
I'm using `Scala 2.12.15` and `Spark 3.5.0`.

I'm currently getting this error.
`NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.objects.StaticInvoke.<init>(Ljava/lang/Class;Lorg/apache/spark/sql/types/DataType;Ljava/lang/String;Lscala/collection/Seq;Lscala/collection/Seq;ZZZ)V`

This is an excerpt of  my build.sbt file containing relevant references to scalapb:
```
libraryDependencies ++= Seq(
...
  "com.thesamet.scalapb" %% "sparksql35-scalapb0_11"% "1.0.4",
  "com.thesamet.scalapb" %% "scalapb-runtime" % scalapb.compiler.Version.scalapbVersion % "protobuf"
)

assembly / assemblyShadeRules := Seq(
  ShadeRule.rename("com.google.protobuf.**" -> "shadeproto.@1").inAll,
  ShadeRule.rename("scala.collection.compat.**" -> "shadecompat.@1").inAll,
  ShadeRule.rename("shapeless.**" -> "shadeshapeless.@1").inAll
)

Compile / PB.targets := Seq(
  scalapb.gen() -> (Compile / sourceManaged).value / "scalapb"
)
```

This an excerpt from my plugins.sbt file.
```
addSbtPlugin("com.thesamet" % "sbt-protoc" % "1.0.7")
libraryDependencies += "com.thesamet.scalapb" %% "compilerplugin" % "0.11.14"
```

Per the [sparksql-scalapb docs](https://scalapb.github.io/docs/sparksql#using-sparksql-scalapb) I have imported `scalapb.spark.Implicits` instead of `spark.implicits._`

Wondering if anyone has any advice on what I could be doing incorrectly.

**Comment by CrawFishFiesta** [comment]
I think I figured out my issue.  I was running the code base on databricks 14.3LTS.

Once I made the spark-session lazy things started working.

**Comment by kewitschka** [comment]
@CrawFishFiesta How exactly did you fix the error? Could you please share a code example?
