### ISSUE TITLE
Support -Ykind-projector:underscores compiler option

### ISSUE THREAD

**Issue by artembakhanov** [scalapb/ScalaPB#1727]
### Overview
The sbt plugin generated code currently cannot be compiled with `-Ykind-projector:underscores` compiler option (Scala 3).

### Expected behaviour
Code compiles without errors.

### Steps to reproduce

In your Scala 3 project add this to build.sbt:

```scala
ThisBuild / scalacOptions += "-Ykind-projector:underscores"
```

Example log

```
[error] 127 |  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
[error]     |                                                                                    ^^
[error]     |                                          ']' expected, but '<:' found
```

**Comment by thesamet** [comment]
Thanks for submitting this issue. It seems like this would be of little use for most users until Scala 3 forces this change. I'd reconsider implementing this at a future time. If your project requires this compiler flag, I suggest recompiling the generated source code in a dedicated subproject that uses default scala compiler settings.
