### ISSUE TITLE
Get scalaPB json support for a scalajs supported json library like upickle

### ISSUE THREAD

**Issue by LogicalTime** [scalapb/ScalaPB#175]
I would be nice to have a Json option that works with ScalaPB and Scalajs. I made an issue over at upickle to see if contributors over there like the idea:
https://github.com/lihaoyi/upickle-pprint/issues/173

**Comment by thesamet** [comment]
There is some support of json4s and Scala.js - but I haven't tried to play with it. We already have methods that return a `JObject` in https://github.com/trueaccord/scalapb-json4s/blob/master/src/main/scala/com/trueaccord/scalapb/json/JsonFormat.scala

**Comment by ngbinh** [comment]
@LogicalTime what specifically are you looking for? We are using Scalapb with http://circe.io/ and no complain here.

**Comment by thesamet** [comment]
@ngbinh Interesting - can you share the code that converts between ScalaPB messages to JSON?

**Comment by ngbinh** [comment]
@thesamet we are not actually converting ScalaPB <-> circe. We wrap hex value of protobuf message bytearray as a Json value. Roughly:

```scala
  implicit def messageEncoder[MS <: GeneratedMessage]: Encoder[MS] = {
    Encoder.instance { message =>
      val bytesString = BytesToHex.toHex(message.toByteArray)
      Json.obj("bytes" -> Json.fromString(bytesString))
    }
  }

  implicit def messageDecoder[MS <: GeneratedMessage](
    implicit companion: GeneratedMessageCompanion[MS]
  ): Decoder[MS] = {
    Decoder.instance { cursor =>
      cursor.downField("bytes").focus.flatMap(_.asString).fold[Decoder.Result[MS]] {
        Xor.Left(DecodingFailure("Invalid message", cursor.history))
      } { bytesString =>
        val bytes = BytesToHex.fromString(bytesString)
        val message = companion.parseFrom(bytes)
        Xor.Right(message)
      }
    }
  }
```

The nice thing here is even though we store some of our data as `Json` format, we can still evolve our data schema.

**Comment by thesamet** [comment]
@ngbinh It's a very good approach for schema evolution. For example, if you rename a field and redeploy the backend, the frontend doesn't have to be redeployed at the exact same time as the wire format stays the same.

**Comment by LogicalTime** [comment]
@ngbinh To answer what I am looking for is supporting the new google canonical mapping between proto3 files and json. Here is how scalapb-json4s does it. I guess I should just use them as a model and make a upickle one then all the dependencies will be ScalaJs friendly. I can think of a few fun uses for that. The mapping looks simple enough for scalapb-json4s, just need to produce one for upickle using it as a template methinks:
https://github.com/trueaccord/scalapb-json4s/blob/master/src/main/scala/com/trueaccord/scalapb/json/JsonFormat.scala

**Comment by xuwei-k** [comment]
https://github.com/xuwei-k/scalapb-playjson

I have released scalapb-playjson 0.5.0 with scala-js support :)

**Comment by thesamet** [comment]
Thanks for working on this @xuwei-k . I've been spending time on getting it to work with Circe. It would be nice to find a way to get a single core implementation that is applied to each of the many JSON libraries that are around. I looked into Jawn but it has no ScalaJS support.

**Comment by ngbinh** [comment]
@xuwei-k @thesamet what are the benefits of having `scalapb` and the json libraries connected here? Does it allow us to do something more efficient than just having `circe` derive the `case classes` generated from `protobuf`?

**Comment by thesamet** [comment]
There are specific rules of how to encode protobufs as json: https://developers.google.com/protocol-buffers/docs/proto3#json

Using the default encoders/decoders wouldn't be compliant in certain cases. Also, circe (and other libraries) can't automatically derive things like one-ofs and enums.

**Comment by thesamet** [comment]
With the various scalapb-json projects I believe this can be closed now.
