### ISSUE TITLE
Incorrect code generation for references to enums from another sbt sub-project

### ISSUE THREAD

**Issue by agemooij-reflek** [scalapb/ScalaPB#1781]
I've run into a code generation issue when trying to move part of my protobuf sources into another sbt sub-project in order to prevent them being exposed to (gRPC) client code.

I have the following sbt project setup:

```
/protos/src/main/protobuf/...
/application/src/main/protobuf/...
```

The `protos` project should publish the protobufs used by external (gRPC) clients
The `application` project uses protobuf for internal serialization, but those protobufs refer to some "common" protobufs in the `protos` project.

As long as all my protobuf sources are in the `protos` project, everything works fine.
But when I move my "internal" protobuf files into the application project I get compilation errors due to the generated code referring to various enum `UNSPECIFIED` values using incorrect code, different fro the code that was generated when everything was together in the `protos` project

Before the move:
```scala
var __changeType: my_package.v1.MagnetType.ChangeType = my_package.v1.MagnetType.ChangeType.Unspecified
```
After the move:
```scala
var __changeType: my_package.v1.MagnetType.ChangeType = my_package.v1.MagnetType.ChangeType.CHANGE_TYPE_UNSPECIFIED
```
I get this for all references to enums that are still in the "common" `protos` project and only for the `UNSPECIFIED` values, e.g. only for code that refers to the "default" enum value with field number `0`

All other references to protobuf messages in the `protos` project are correct. 

Is this a bug or is there a way to work around this?

### Protobuf sources

The original protobuf for that enum is this:
```protobuf
message MagnetType {
  enum ChangeType {
    CHANGE_TYPE_UNSPECIFIED = 0;
    CHANGE_TYPE_LOCAL = 1;
    CHANGE_TYPE_INHERITED = 2;
  }
}
```

The `package.proto`:
```protobuf
syntax = "proto3";

package ontology.v1;
option java_package = "io.reflek.ontology.v1";

import "scalapb/scalapb.proto";
import "validate/validate.proto";

option (scalapb.options) = {
  scope: PACKAGE
  flat_package: true
  enum_strip_prefix: true
  enum_value_naming: CAMEL_CASE
  retain_source_code_info: true
  preserve_unknown_fields: false
  lenses: false
  no_default_values_in_constructor: true
  scala3_sources: true
  field_transformations: [
    {
      when: {options: {[validate.rules] {message: {required: true}}}}
      set: {
        [scalapb.field] {
          required: true
        }
      }
    }
  ]
};
```

### Versions used:

- scala 3.5.2
- sbt 1.10.6

```scala
addSbtPlugin("com.thesamet" % "sbt-protoc"    % "1.0.7")

libraryDependencies ++= Seq(
  "com.thesamet.scalapb" %% "compilerplugin"           % "0.11.17",
  "com.thesamet.scalapb" %% "scalapb-validate-codegen" % "0.3.6"
)
```

**Comment by thesamet** [comment]
The application project needs to import "package.proto" from `protos/src/main/protobuf` so it's aware of the package settings. You can add another proto file that just imports `package.proto`. If you intend in the future to publish `protos` as a separate JAR you see this section to prevent the need from users to do this import manually: https://scalapb.github.io/docs/customizations/#publishing-package-scoped-options

**Comment by agemooij-reflek** [comment]
Ah, thanks a lot for the quick answer! 
I had looked through the sbt customizations section but not in the general customization section and it was hard to google for.
I'll try to send in a little doc PR on Monday to add a reference to this to the "SBT Settings" page.

@thesamet Is there a way for `scalapb` to use the same auto-detection trick it uses with jars/dependencies to fix this for cross-project sbt dependencies?

**Comment by agemooij-reflek** [comment]
The trick worked, although I do now get an irritating "import is unused" warning about the `package.proto` import.
Is there a way to turn that off?

**Comment by thesamet** [comment]
I think that having the auto-detection trick work for dependsOn would be a nice addition. In the meantime, as an alternative to copy, you could either symlink, or add to `Compile / PB.protoSources` in the application directory the path to the directory containing `package.proto` in the protos project as long as it's the only proto file under that directory so there's no duplicate code generation.

**Comment by thesamet** [comment]
In the interest of time, I'll have the issue deleted. Thanks for reporting.
