### ISSUE TITLE
Create release with protoc package version > 0.9.8

### ISSUE THREAD

**Issue by astamagnusdottir-asana** [scalapb/ScalaPB#1783]
The previous release `0.9.7` of protoc-bridge used Scala version 2.13.12, but there is an issue in the `rules_scala` [package](https://github.com/bazelbuild/rules_scala) where the Reporter classes are not minor version compatible between 2.13.12 and 2.13.13. This causes an error during compilations for projects building with a Scala version > 2.13.12.

Error from build:

```
external/io_bazel_rules_scala/src/java/io/bazel/rulesscala/scalac/deps_tracking_reporter/after_2_12_13_and_before_2_13_12/DepsTrackingReporter.java:235: error: method warning in class Reporter cannot be applied to given types;
            reporter.warning(NoPosition$.MODULE$, strictDepsReport.toString());
                    ^
  required: Position,String,List<CodeAction>
  found:    NoPosition$,String
  reason: actual and formal argument lists differ in length
```
The [issue](https://github.com/scalapb/protoc-bridge/issues/406) has been address in protoc-bridge, but as ScalaPB libraries such as compilerplugin depend on `0.9.7` the issue persists. Would it be possible to create a release or a patch of the ScalaPB libraries with the new version dependencies to support this minor version incompatibility?

**Comment by thesamet** [comment]
Doesn't the problem resolve if you include protoc-bridge 0.9.8 in your build? I could certainly cut a release, but wondering if there's a longer chain of dependency that would unnecessarily cut a release just for a dependency bump.

**Comment by astamagnusdottir-asana** [comment]
Yes true, I did I clean build and there is probably something else wrong. I will dive into it and otherwise open an issue again, thanks.
