### ISSUE TITLE
Json parser should accept snake case

### ISSUE THREAD

**Issue by thesamet** [scalapb/ScalaPB#179]
See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/scalapb/p_lLxUJYyag/IgZVz4UTBQAJ

**Comment by thesamet** [comment]
This feature is available in scalapb-json4s 0.3.0

**Comment by morpheyesh** [comment]
Unfortunately, I still get this issue in scalapb-json4s 0.3.0. Has this been fixed?

**Comment by thesamet** [comment]
You need to construct a custom parser that has "preservingProtoFieldNames=true" to get this behavior:

```
val myParser = new scalapb.json4s.Parser(preservingProtoFieldNames=true)
myParser.fromJson[MyMessage](bytes)
```
