### ISSUE TITLE
JSON Format ellides empty repeated fields

### ISSUE THREAD

**Issue by aemoncannon** [scalapb/ScalaPB#183]
Say I have this proto:
message Foo {
  repeated string bars = 1;
}

In scala:
JSONFormat.toJsonString(Foo()) => "{}"

This is surprising. I expected "{ \"bars\": [] }", which is the behavior in Google's JavaPb -> JSON serialization.

Is it perhaps because of this match, where Nil is ignored?
https://github.com/trueaccord/ScalaPB/blob/master/scalapb-runtime/shared/src/main/scala/com/trueaccord/scalapb/GeneratedMessageCompanion.scala#L80

**Comment by thesamet** [comment]
It looks like the default behavior in Google's Java PB->Json is to omit repeated fields: https://github.com/google/protobuf/blob/d58b92ae5169ba888e6b5ca91c0ec9814668fa2c/java/util/src/test/java/com/google/protobuf/util/JsonFormatTest.java#L1163

However, they have a setting called `includeDefaultValueFields` which makes it include those empty lists. It would be nice if we supported that.

**Comment by aemoncannon** [comment]
Ah hah. You are right -- I've been using includeDefaultValueFields. Maybe I'll look into adding this..

**Comment by thesamet** [comment]
I have some initial code already, would probably commit it in a few hours. Thanks though!

**Comment by aemoncannon** [comment]
Wow! That's great

**Comment by thesamet** [comment]
This is fixed in scalapb-json4s 0.1.4
