### ISSUE TITLE
Update to 3.1.0

### ISSUE THREAD

**Issue by cranst0n** [scalapb/ScalaPB#195]
Any reason protobufVersion can't be updated?

**Comment by xuwei-k** [comment]
ScalaPB has [gRPC](http://www.grpc.io/) integrations.
grpc-java 1.0.1 (latest version in 2016/11/24) depends on protobuf-java 3.0.0
http://repo1.maven.org/maven2/io/grpc/grpc-protobuf/1.0.1/grpc-protobuf-1.0.1.pom

I'm not sure compatility of protobuf 3.0.0 between 3.1.0.

**Comment by cranst0n** [comment]
Ah I missed that. The changelog makes it sound like 3.1 is a bug fix and some different JSON behavior but I forgot about grpc. Thanks!

**Comment by thesamet** [comment]
It looks like it's safe to upgrade.
