### ISSUE TITLE
Feature request: global error handler

### ISSUE THREAD

**Issue by macalinao** [scalapb/ScalaPB#201]
It would be nice to be able to call the `onError` method of the StreamObservers so we can specify error handlers for our futures.

Even better, some sort of middleware system would be nice. There's probably a way to do this but I'm not aware of it.

**Comment by thesamet** [comment]
If this issue is still relevant, can you provide more context, into what problem this would solve, and whether the behavior you are looking for is not available right now?

Since it's been awhile, I'm closing the ticket, but feel free to add comments or file another ticket.
