### ISSUE TITLE
Invalid enum name for `Unrecognized`

### ISSUE THREAD

**Issue by nykolaslima** [scalapb/ScalaPB#202]
When using scalapbc cli to compile proto files the `Unrecognized` value of enum types is being generated with an invalid name with the first letter capitalized and other letters in small case but the proto default name should be all letters upper case. https://developers.google.com/protocol-buffers/docs/proto3#enum

e.g.
```
enum Colors {
 YELLOW = 0;
 RED = 1;
}
```

This will generate the following Scala code:
```
object Colors extends com.trueaccord.scalapb.GeneratedEnumCompanion[Colors] {
  implicit def enumCompanion: com.trueaccord.scalapb.GeneratedEnumCompanion[Colors] = this
  @SerialVersionUID(0L)
  case object YELLOW extends Colors {
    val value = 0
    val index = 0
    val name = "YELLOW"
    override def isYellow: Boolean = true
  }
  @SerialVersionUID(0L)
  case object RED extends Colors {
    val value = 1
    val index = 1
    val name = "RED"
    override def isRed: Boolean = true
  }
  @SerialVersionUID(0L)
  case class Unrecognized(value: Int) extends Colors {
    val name = "UNRECOGNIZED"
    val index = -1
    override def isUnrecognized: Boolean = true
  }
}
```

Note that all defined values `yellow` and `red` have generated case classes with upper case letters but the `unrecognized` value does't use upper case letters.

My proposal is to change the generated code for `unrecognized` value to generate a case class with all upper case letters in order to have the same pattern for defined values and `unrecognized`.

What do you guys think about it?

**Comment by thesamet** [comment]
Doesn't sound to me that it's bad enough to be worth breaking existing code for our users. Happy to reconsider if there'll be strong interest.
