### ISSUE TITLE
Scala 2.12 compatible release?

### ISSUE THREAD

**Issue by pjan** [scalapb/ScalaPB#204]
Are there any timelines for this? Thanks for the great piece of software!

**Comment by xuwei-k** [comment]
ScalaPB support Scala 2.12 since 0.5.45
- http://repo1.maven.org/maven2/com/trueaccord/scalapb/scalapb-runtime_2.12/
- https://github.com/scalapb/ScalaPB/commit/9d46a2550fa9c80db7

**Comment by pjan** [comment]
Thanks @xuwei-k. Apparently I ran into #150, which I confused with 2.12 compilation not working. Closing this one.
