### ISSUE TITLE
Scala compiler error with enum constant named 'UNRECOGNIZED'

### ISSUE THREAD

**Issue by salomvary** [scalapb/ScalaPB#207]
Given this protobuf file:

```protobuf
package test;

message TestMessage {
  enum SomeEnum {
    UNRECOGNIZED = 0;
    FOO = 1;
    BAR = 2;
  }

  optional SomeEnum someEnum = 1;
}
```

I get this compile error:
```
[error] target/scala-2.12/src_managed/main/test/test/TestMessage.scala:86: method isUnrecognized is defined twice;
[error]   the conflicting method isUnrecognized was defined at line 83:9
[error]     def isUnrecognized: Boolean = false
[error]         ^

```

The relevant part of the generated code looks like this:
```scala
  sealed trait SomeEnum extends _root_.com.trueaccord.scalapb.GeneratedEnum {
    type EnumType = SomeEnum
    def isUnrecognized: Boolean = false
    def isFoo: Boolean = false
    def isBar: Boolean = false
    def isUnrecognized: Boolean = false
    def companion: _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[SomeEnum] = SomeEnum
  }
```

Versions:
```
"com.trueaccord.scalapb" %% "compilerplugin" % "0.5.45"
"com.thesamet" % "sbt-protoc" % "0.99.1"
scalaVersion := "2.12.1"
sbtVersion 0.13.9
```

**Comment by thesamet** [comment]
`Unrecognized` is reserved in ScalaPB for unrecognized values that are received in a message. Can you use a different name, for example UNKNOWN?

**Comment by salomvary** [comment]
> Can you use a different name, for example UNKNOWN?

@thesamet Thanks for the explanation. Unfortunately changing the name is not an easy option as this came up on an existing large codebase where `UNRECOGNIZED` needs to be kept for backwards compatibility.

I guess an error message explaining the situation before the Scala compiler chokes on it would be a nice improvement.

**Comment by thesamet** [comment]
We can also have ScalaPB avoid the conflict by pretending the name is something else like `Unrecognized1`

**Comment by salomvary** [comment]
You mean the reserved one generated for unrecognized values would use the alternative name instead? That sounds like a plan too!

**Comment by thesamet** [comment]
I meant the user defined one will get a different name. The generated `Unregognized` will stay with the same name.

**Comment by thesamet** [comment]
Actually, I think it's best to just not allow the name `Unrecognized`. Silently replacing it with `Unrecognized1` while keeping the built-in `isUnrecognized` is likely to lead users to write incorrect code (uses will wrongly assume `isUnregonized` is checking for their custom value and not for really undefined values).
