### ISSUE TITLE
ScalaPB working with multiple distinct projects

### ISSUE THREAD

**Issue by jon-morra-zefr** [scalapb/ScalaPB#211]
I have a situation where I have 2 projects that are compiled at different times project one has some Protocol Buffer messages and it's compilation works fine.  Project two has another message that depends upon a message in project one.  There exists a dependency on project one from within project two, but the protoc compilation doesn't work.  I'm forced to do something like this in project two's build.sbt

```
PB.includePaths in Compile += file("../commons-proto/src/main/protobuf")
```

This is not good because it assumes a relationship on disk of the source files.  Having come from a Java world recently we used to use [this](https://www.xolstice.org/protobuf-maven-plugin/) plugin that worked great for Java protos.  It did not suffer from the above issue because it has a parameters called [attachProtoSources](https://www.xolstice.org/protobuf-maven-plugin/compile-mojo.html) which handles this gracefully.

It would be very nice if this functionality was baked in to ScalaPB.

**Comment by thesamet** [comment]
The current official solution is to use `PB.includePaths in Compile` like you indicated. I think that resolving the include path automatically is going to be tricky in presence of transitive dependencies or external dependencies (protos coming from external jars). We're probably better off with an explicit `PB.includePaths` than having complex logic to collect dependencies.
