### ISSUE TITLE
Use immutable `Seq` for `repeated`

### ISSUE THREAD

**Issue by hseeberger** [scalapb/ScalaPB#227]
Currently a `repeated` field of a message gets compiled to a `scala.collection.Seq` parameter or a case class. Case classes really should be immutable, which can be broken by passing a mutable `Seq`. Therefore I suggest to use `scala.collection.immutable.Seq`.

**Comment by xuwei-k** [comment]
related https://github.com/scalapb/ScalaPB/pull/218

**Comment by thesamet** [comment]
This should be an option users can choose once #218 is implemented since making `scala.collection.immutable.Seq` the default generated type would break users' existing code:

```
scala> case class Foo(x: collection.immutable.Seq[Int])
defined class Foo

scala> Foo(Seq(3,4,5))
<console>:14: error: type mismatch;
 found   : Seq[Int]
 required: scala.collection.immutable.Seq[Int]
       Foo(Seq(3,4,5))
              ^
```

**Comment by hseeberger** [comment]
Even better if it becomes an option. But for a pre-1.0 software I personally wouldn't be surprised by breaking changes.

**Comment by rogern** [comment]
I wonder, can't this default to `immutable.Seq` if generated on >=2.13 and `collection.Seq` on earlier versions? 
A tad annoying with false positives in IDE wherever used :) 
We will configure it for now though.

**Comment by thesamet** [comment]
ScalaPB generator code is meant to be used on all supported versions of Scala, incl. Scala 3. Been trying to avoid having language-version logic in the generator, though this is something that can be considered in the future if there's a real advantage. For this one, you can set [`collection_type`](https://scalapb.github.io/docs/customizations#custom-collection-types) as a package-scoped option in your project, and alter `PB.protoSources` in sbt to include that options file only in a certain Scala versions.
