### ISSUE TITLE
Use `_root_` for application package

### ISSUE THREAD

**Issue by skylve** [scalapb/ScalaPB#228]
If you have the same `java_package` as a `message` field, scalac compilation fail.

```
option java_package = "aaa";
message Foo {
    string aaa = 1;
}
```

Could you prefix with `_root_` all generated code referencing the java_package (for example for function `mergeFrom`) ?

**Comment by thesamet** [comment]
This does not seem to happen in recent versions (tried 0.5.45 and onwards). Which version are you using?
