### ISSUE TITLE
Make option for companion object based on GeneratedMessageCompanion implicit

### ISSUE THREAD

**Issue by leandrob13** [scalapb/ScalaPB#229]
Make companion object based on GeneratedMessageCompanion implicit so it helps when we want to do typeclass implicit resolution. I have been using protobuf and I see that it can be easily used as a typeclass pattern on GeneratedMessageCompanion. Is there a way to do it now?

**Comment by xuwei-k** [comment]
ScalaPB generate `implicit def messageCompanion:`

https://github.com/scalapb/ScalaPB/blob/v0.5.47/compiler-plugin/src/main/scala/com/trueaccord/scalapb/compiler/ProtobufGenerator.scala#L940

Is this what you want? or do you want to disable implicit?

**Comment by leandrob13** [comment]
@xuwei-k You are right. I wrote a gist, I was defining a KafkaEncoder trait so I could use it as a type class so I could define which companion to use for each event I defined. Then I made two functions that took the implicit companion directly. Thanks for the tip!

https://gist.github.com/leandrob13/9c73bcabcdb71f4765808c615b530e10
