### ISSUE TITLE
The sealed trait generated for the oneof 'fuu' conflicts with another message name 'Fuu'

### ISSUE THREAD

**Issue by skylve** [scalapb/ScalaPB#232]
Currently, this code doesn't compile with ScalaPB:
```
message Xxx {
  oneof fuu {
    ...
  }

  message Fuu {
    ...
  }
}
```
and trigger `The sealed trait generated for the oneof 'fuu' conflicts with another message name 'Fuu'.`

This is a valid proto definition and works with Java compiler (didn't try with other compilers).
Luckily for me I am defining the protocol and can change either the `oneof` or `message`. It may not be the case for other users that will have to interface with a defined protocol.

I can't see any solution that would not be breaking the current API. But you may want to check this one next time you push some breaking changes.

**Comment by thesamet** [comment]
Not all valid proto definitions can be compiled to valid Scala code without introducing confusing name mangling. This is why ScalaPB gives a pretty good error message in this case.
