### ISSUE TITLE
Enable toString customizeability

### ISSUE THREAD

**Issue by Sushisource** [scalapb/ScalaPB#235]
The default toString works just fine most of the time, but esp. if you're using custom types (ex: I use a bytes field to represent UUIDs), sometimes the output is less than desirable. In my example, UUIDs get printed to the screen as some backslash-escaped bytestring.

There are a few ways to implement it - I think a simple one would maybe just be to look for an implicit function in scope with the right signature (MessageType -> String) and use that, if present.

Thanks!

**Comment by thesamet** [comment]
The output generated by `msg.toString()` is compatible with the ASCII format that the protocol  buffer implementations are using, so I wouldn't want to provide an option to break interoperability. Maybe there are other alternatives, like extending your message from a custom trait that provides `show` method as an alternative to `toString`?

**Comment by Sushisource** [comment]
Ah, I see - that makes sense. I'll take a look at using a trait to implement that.

**Comment by thesamet** [comment]
Closing. Feel free to continue the discussion here if needed.

**Comment by MikeBlink** [comment]
Following up from here: https://groups.google.com/forum/#!topic/scalapb/PxrPiV3AyG4

Would it be possible to enable some form of overriding toString? Given how toString is used by default for logging / debugging there doesn't seem to be any way of hiding certain information from logs without explicitly stripping it away before passing it down to a log (or library). 

Ascii protobuf representation would ideally be provided with some explicit function like toProtoString (similar to how JSON libraries tend to provide e.g. toJson). 

Right now the only way of achieving removal of information from logs is to override the textformat.Printer object on the classpath with a custom version which is less than ideal.

**Comment by ahjohannessen** [comment]
It would be nice to have a method a la `toStringStd` or similar that case classes normally have, logging requests in grpc is a bit over the top with current text format printer, plus typemappers are not applied in `toString`.

**Comment by jsw** [comment]
I agree with the previous commenters. It would be much more intuitive and convenient if `toString` is the standard case class `toString`, and a separate `toProtoString` is added. The 99% use case is logging these messages.

**Comment by thesamet** [comment]
Ok, listening to the users here. In 0.7.x, toString will not be overridden by ScalaPB and will give the default case class presentation. There will be a `.toProtoString` that returns the text format. If you are relying on the old behavior, you need to add `asciiFormatToString=true` to the `scalapb.gen()` in SBT, or `ascii_format_to_string` parameter to ScalaPBC.
