### ISSUE TITLE
Support for protobuf 3.2.0

### ISSUE THREAD

**Issue by pradyuman** [scalapb/ScalaPB#241]
Protobuf 3.2.0 has been released: https://github.com/google/protobuf/releases/tag/v3.2.0

Is it possible to update scalapb to support it? I'm tracking a 3.2.0 release for protoc-jar here: https://github.com/os72/protoc-jar/issues/17

**Comment by thesamet** [comment]
sbt-protoc 0.99.4 is set up to invoke protoc 3.2.0 by default.

**Comment by pradyuman** [comment]
Thanks!
