### ISSUE TITLE
JSON Serialization Provide Option to Emit Default Values

### ISSUE THREAD

**Issue by nattyddubbs** [scalapb/ScalaPB#242]
Based on the protobuf language guide, "If a field has the default value in the protocol buffer, it will be omitted in the JSON-encoded data by default to save space. An implementation may provide options to emit fields with default values in the JSON-encoded output."

AFAIK there is no option to perform this operation in ScalaPB. Can this option be added?

**Comment by thesamet** [comment]
Hi @nattyddubbs , the option is actually already available. See this test for example on how to use: 
https://github.com/scalapb/scalapb-json4s/blob/master/src/test/scala/com/trueaccord/scalapb/json/JsonFormatSpec.scala#L120

**Comment by nattyddubbs** [comment]
Thank you for the example.

**Comment by xinatcg** [comment]
link has been changed:
https://github.com/scalapb/scalapb-json4s/blob/master/src/test/scala/scalapb/json4s/JsonFormatSpec.scala

basically, there is a printer can print the default value in json

```
  def includingDefaultValueFields: Printer =
    new Printer(config.copy(isIncludingDefaultValueFields = true))

```
