### ISSUE TITLE
java_outer_classname not used

### ISSUE THREAD

**Issue by jjagged** [scalapb/ScalaPB#243]
I've got the perhaps a bit strange setup with two proto files with the same name in parallel directories. For reasons not really within my control, they have different `package`s, but the same `java_package`. This leads to me getting a compilation error `my/test/MyProto/MyProtoProto.scala: Tried to write the same file twice.` since they are named the same, and end up in the same package. I had thought the `java_outer_classname` would help with that, but apparently not. Would it be possible to use the `java_outer_classname`, if present, for avoiding this error?

```
src/
  |- main/
        |- resources/
                  |- protobuf/
                           |- dir1/
                           |     |- MyProto.proto
                           |- dir2/
                                |- MyProto.proto
```

The contents of the files:
```
syntax = "proto3";

package my.first.test;

option java_outer_classname = "MyFirstProto";
option java_package = "my.test";

message AnotherMessage {
    string msg = 1;
}
```

```
syntax = "proto3";

package my.second.test;

option java_outer_classname = "MySecondProto";
option java_package = "my.test";

message OneMessage {
    string msg = 1;
}
```

I'm using `scalapb` version `0.5.47` and `sbt-protoc` `0.99.3`

**Comment by thesamet** [comment]
`java_outer_classname` is indeed not used in Scala - there is no outer class enclosing all generated messages like in Java. How about setting a different Scala package for each file: see https://scalapb.github.io/customizations.html

**Comment by jjagged** [comment]
But there is a Scala file generated with the name `my/test/MyProto/MyProtoProto.scala`, which does not correspond to any of the messages I have defined:

```
package my.test.MyProto



object MyProtoProto {
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChJkaXIyL015UHJvdG8ucHJvdG8SDm15LnNlY29uZC50ZXN0GhVzY2FsYXBiL3NjYWxhcGIucHJvdG8iHgoKT25lTWVzc2FnZ
  RIQCgNtc2cYASABKAlSA21zZ0IrCgdteS50ZXN0Qg1NeVNlY29uZFByb3Rv4j8QCg5teS5zZWNvbmQudGVzdGIGcHJvdG8z"""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
  com.trueaccord.scalapb.Scalapb.getDescriptor()
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}
```

It is this file that collides. Could this file (and object) be named after the `java_outer_classname`?

I could of course modify the proto files to work within my service, but that would mean that we'd have to modify the other service's proto files every time the files are updated.

**Comment by thesamet** [comment]
I would like to avoid piggybacking on existing Java options while slightly changing their meaning. If using ScalaPB's package_name option is not available, I would suggest adapting a convention where the java package corresponds to the directory of the proto, ie

```
option java_package = "my.test.dir1";
```

**Comment by jjagged** [comment]
I see, and I can understand your position. I'll see if I can get the service provider to change their wicked ways, otherwise we'll adapt and overcome and live with modifying their protos. Thanks :)
