### ISSUE TITLE
Akka HTTP support

### ISSUE THREAD

**Issue by bthuillier** [scalapb/ScalaPB#247]
I currently using akka http with protobuf, I think it can be cool to add the support for everyone, I don't know where to put the code, if I have to create a specific project or it can be integrated here. The first version of the code is : 
```scala
import akka.http.scaladsl.marshalling.{PredefinedToEntityMarshallers, ToEntityMarshaller}
import akka.http.scaladsl.unmarshalling.{FromEntityUnmarshaller, Unmarshaller}
import com.trueaccord.scalapb.{GeneratedMessage, GeneratedMessageCompanion, Message}


trait ProtobufSupport {
  implicit def protobufMarshaller[T <: GeneratedMessage]: ToEntityMarshaller[T]  = PredefinedToEntityMarshallers.ByteArrayMarshaller.compose[T](r => r.toByteArray)
  implicit def protobufUnmarshaller[T <: GeneratedMessage with Message[T]](implicit companion: GeneratedMessageCompanion[T]): FromEntityUnmarshaller[T] =
    Unmarshaller.byteArrayUnmarshaller.map[T](bytes => companion.parseFrom(bytes))
}
```

I will open a PR when I have more information where to put it

**Comment by akauppi** [comment]
@bthuillier While this is cool, and getting Akka-http marshallers right often takes a bit more time than one would want, is adding this to ScalaPB itself the right choice?

Just having a StackOverflow entry might suffice? If you go that route, tag it both `akka-http` and `scalapb`.

**Comment by thesamet** [comment]
There isn't a good place to throw those lines right now since that would introduce a dependency on Akka. I feel that there isn't enough meat here for creating a project and publishing a jar just for this, so probably keeping this snippet here is the right thing for now.

**Comment by ktoso** [comment]
> I'd like to make a strong plea for the above snippet to be included in the Akka HTTP documentation as an example of how to do this. That would make it much easier for people to find.

We'd really welcome such pull request, would you be able to make one?
You could copy the https://github.com/akka/akka-http/blob/master/docs/src/main/paradox/common/json-support.md and make the same for proto support, would be a lovely contribution!

**Comment by alanbur** [comment]
Sure, once I have it working I'll see about providing a simple example, but it may be a little while before I have time to do so - feel free to nag ;-)

**Comment by micmorris** [comment]
For anyone else getting here like I did and having the top snippet not work, I posted my solution on getting this to work in the ^^above issue^^ ("#1911" on the `akka-http` project) working on the newest version of `scalapb`.

**Comment by thesamet** [comment]
Hi @ritcat14 , will respond in stackoverflow. As this is an old and closed github issue, if you believe there's a bug in ScalaPB, feel free to create a new issue.
