### ISSUE TITLE
e2e.sh does not crossbuild against Scala 2.12

### ISSUE THREAD

**Issue by mslinn** [scalapb/ScalaPB#259]
`e2e.sh` needs a line with ++2.12.1 in it:

```
#!/usr/bin/env sh
set -e
sbt ++2.10.6 compilerPlugin/publishLocal runtimeJVM/publishLocal createVersionFile \
    ++2.11.8 runtimeJVM/publishLocal grpcRuntime/publishLocal
cd e2e
sbt clean test
```

**Comment by thesamet** [comment]
e2e only tests a single Scala version at a time. The 2.10.x line building ScalaPB compiler plugin which is ran by SBT (and hence must be 2.10.x). With this new change, the version tested is provided by an environment variable. It is set up such that in Travis we will run e2e for all Scala versions we support.
