### ISSUE TITLE
Suggestion: macro based generation support

### ISSUE THREAD

**Issue by mkotsbak** [scalapb/ScalaPB#263]
Have you thought about supporting macros that generate the classes on the fly while compiling directly from the protobuf interface files?

**Comment by thesamet** [comment]
Thought about it, but never gotten to actually looked into it. Sounds worth exploring. Advantages of the generated code compared to macros are that comments from the proto files become java doc, the users can browse around and there's good IDE support.

**Comment by mkotsbak** [comment]
True, but for IntelliJ it could be solved by adding a plugin that does the lookup in the PB files.

**Comment by thesamet** [comment]
What advantage(s) do you see in moving from generated source code to compiler macros? I think it would be pretty hard to achieve feature parity. For example, it's now possible to import protos from jars that are in jars provided through libraryDependencies.

**Comment by mkotsbak** [comment]
Mostly to avoid the code generation stage and get immediate effect of changing the proto files.

**Comment by thesamet** [comment]
I like the idea in theory, and if anyone is interested in working on it I'll be happy to review a PR. I'm closing since it's unlikely to actually get done anytime soon.
