### ISSUE TITLE
Add support for gRPC-Web for Scala.Js

### ISSUE THREAD

**Issue by mkotsbak** [scalapb/ScalaPB#275]
See https://spatialos.improbable.io/games/grpc-web-moving-past-restjson-towards-type-safe-web-apis and https://github.com/improbable-eng/grpc-web

We could probably use a wrapper of https://github.com/improbable-eng/grpc-web/tree/master/ts and maybe some ideas from the TS generator: https://github.com/improbable-eng/ts-protoc-gen

**Comment by thesamet** [comment]
This probably wouldn't happen anytime soon unless a PR is submitted. If anyone is interested in working on it, please coordinate with me over the details before jumping in.

**Comment by thesamet** [comment]
Closing for the time being. This can be addressed as a custom protoc-bridge generator. @mkotsbak if you'd like to work on this and need help getting started feel free to let me know.

**Comment by thesamet** [comment]
@mkotsbak , in case this is still relevant, check out https://github.com/scalapb/scalapb-grpcweb

If you add scalapb-grpcweb to your Scala.js project you should be able to make web-grpc code using the client that is generated by ScalaPB's default gRPC code generator.

**Comment by mkotsbak** [comment]
Interesting, but it seems it is currently not type safe at all...

**Comment by thesamet** [comment]
@mkotsbak can you explain?

**Comment by mkotsbak** [comment]
Sorry, it was just the protocol itself that looked generic, thanks :)
