### ISSUE TITLE
Create package containing protobuf definitions for the gRPC gateway descriptors

### ISSUE THREAD

**Issue by Jacoby6000** [scalapb/ScalaPB#277]
Currently, if you want to use the GRPC gateway, you are forced to copy [these files](https://github.com/vyshane/grpc-scala-microservice-kit/tree/master/protobuf/src/google/api). It would be nice to have them accessible via a normal sbt dependency in some way.

**Comment by thesamet** [comment]
ScalaPB is able to import proto files that are packaged inside JARs and published on public repositories such as maven central. See "How do I generate Scala code for protos from another jar?" at https://scalapb.github.io/faq.html.

Please file a request at https://github.com/vyshane/grpc-scala-microservice-kit to publish their protos in a jar and publish it somewhere.

**Comment by thesamet** [comment]
This answer on SO may be useful for you: https://stackoverflow.com/a/44298091/97524
