### ISSUE TITLE
Compile error: method value in trait GeneratedOneof of type => Any is not defined

### ISSUE THREAD

**Issue by ngbinh** [scalapb/ScalaPB#278]
I am trying to upgrade from `0.6.0-pre2` to `0.6.0-pre4` and get this problem:

Proto message:

```
syntax = "proto3";

package role;

import "scalapb/scalapb.proto";

option (scalapb.options) = {
  flat_package: true
};

message SideMessage {
  oneof side {
    MainSideMessage main_side = 1;
    NonMainSideMessage non_main_side = 2;
  }
}

enum MainSideMessage {
  Foo = 0;
  Bar = 1;
}

enum NonMainSideMessage {
  NonFoo = 0; 
  NonBar = 1;
}
```

Generated roughly

```scala
sealed trait Side extends _root_.com.trueaccord.scalapb.GeneratedOneof {
    def isEmpty: Boolean = false
    def isDefined: Boolean = true
    def number: Int
    def isMainSide: Boolean = false
    def isNonMainSide: Boolean = false
    def mainSide: scala.Option[MainSideMessage] = None
    def nonMainSide: scala.Option[NonMainSideMessage] = None
  }
  object Side extends {
    @SerialVersionUID(0L)
    case object Empty extends SideMessage.Side {
      override def isEmpty: Boolean = true
      override def isDefined: Boolean = false
      override def number: Int = 0
    }
  
```

and  because of https://github.com/scalapb/ScalaPB/blob/master/scalapb-runtime/shared/src/main/scala/com/trueaccord/scalapb/GeneratedMessageCompanion.scala#L63 ,this generated code doesn't compile as function `value: Any` wasn't defined anywhere.

This message works fine in `0.6.0-pre2` so I believe the culprit is https://github.com/scalapb/ScalaPB/commit/13c6a1354050ede235c57d114fb67e33b40f3e2e

**Comment by thesamet** [comment]
I believe you need to regenerate the code between those two versions. Just `clean` in sbt and compile again.

**Comment by ngbinh** [comment]
Yes, you are right. Thanks
