### ISSUE TITLE
Handle dashes in proto file names

### ISSUE THREAD

**Issue by mindloaf** [scalapb/ScalaPB#287]
I am attempting to generate Scala from an external collection of proto files. The files have inconsistent use of dashes vs underscores. For example:

```
fooz_ball.proto
bar-none.proto
```

With Java generation, this isn't an issue. Suppose that they both have `java_package` names `com.foobar`, we get:

```
com.foobar.FoozBall
com.foobar.BarNone
``` 

ScalaPB uses the raw file name to create the package. The first works fine for `com.foobar.fooz_ball`, but the latter, `com.foobar.bar-none` is not valid Scala. I tried using the global `flatPackage` option, but then I ran into message naming collisions between proto files. And since the files are external, I can't set per-file Scala options on them.

My proposed solution would be to convert dashed names to underscored ones for the purposes of Scala generation.

**Comment by JStevenson599** [comment]
I had a similar issue just yesterday trying to compile my *proto definitions for use ion Python.  The compiler I was using (protoc) seemed to be getting very confused, and kept throwing "Can't find fieldID definition" errors for any parameters named using dashes.  These errors went away once I switched to using underscores,
Aren't dashes illegal in JAVA variable names?  
Seems simpler if we just stick to using lower_snake_case style for all protobuf parameter names (as in the Proto Style Guide)!
