### ISSUE TITLE
Using compilerplugin-shaded causes 'scalapb.' to be added to package name in generated code for AnnotationsProto

### ISSUE THREAD

**Issue by anurag-prakash-singh** [scalapb/ScalaPB#289]
When the 'compilerplugin-shaded' plugin is used:

addSbtPlugin("com.thesamet" % "sbt-protoc" % "0.99.8" exclude ("com.trueaccord.scalapb", "protoc-bridge_2.10"))
libraryDependencies += "com.trueaccord.scalapb" %% "compilerplugin-shaded" % "0.6.0-pre4"

it causes the following compilation error:

**[error] /Users/xxxx/Progs/scalapb-test-1/target/scala-2.12/src_managed/main/com/google/api/annotations/AnnotationsProto.scala:21: object com is not a member of package scalapb
[error]       scalapb.com.google.protobuf.descriptor.DescriptorProtoCompanion.scalaDescriptor
[error]               ^**

In the generated AnnotationsProto.scala file, I can see that 'scalapb.' has been prepended to what would otherwise have been the correct package name:

```
lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, Seq(
      com.google.api.http.HttpProto.scalaDescriptor,
      scalapb.com.google.protobuf.descriptor.DescriptorProtoCompanion.scalaDescriptor
    ))
  }
```

The correct fully qualified name of 'scalaDescriptor' is 'com.google.protobuf.descriptor.DescriptorProtoCompanion.scalaDescriptor'.

To reproduce the issue, I did the following:

1. switched over to scala 2.12.1 (I don't think this is necessary for reproducing the issue but I want to be using 2.12.x)
2. switch to the shaded plugin:

```
addSbtPlugin("com.thesamet" % "sbt-protoc" % "0.99.8" exclude ("com.trueaccord.scalapb", "protoc-bridge_2.10"))
libraryDependencies += "com.trueaccord.scalapb" %% "compilerplugin-shaded" % "0.6.0-pre4"
```
I've forked off https://github.com/thesamet/scalapb-test-1 and added the above changes in:
https://github.com/anurag-prakash-singh/scalapb-test-1/commit/ef8d2919e5bd5f402d1ae9e6c19a0757838fac68

**Comment by thesamet** [comment]
Thanks for the detailed bug report + repo. This was very helpful in getting this resolved quickly.

**Comment by anurag-prakash-singh** [comment]
Great. Thanks for your prompt attention!
