### ISSUE TITLE
JsonFormat not working with protobuf 2.x

### ISSUE THREAD

**Issue by skizzybiz** [scalapb/ScalaPB#290]
ScalaPB's supplied JsonFormat class doesn't seem to be working. It looks like the problem is that the descriptors' `getJsonName` properties aren't populated. I reproduced this with a minimal test project, which I'll attach.

```
scala> import foo.test.Foo
import foo.test.Foo

scala> val m = Foo(id = Some("abc"))
m: foo.test.Foo =
id: "abc"

scala> import com.trueaccord.scalapb.json.JsonFormat
import com.trueaccord.scalapb.json.JsonFormat

scala> JsonFormat.toJsonString(m)
res0: String = {"":"abc"}

scala> JsonFormat.fromJsonString[Foo]("""{"id":"abc"}""")
res3: foo.test.Foo =

scala> m.companion.scalaDescriptor.fields(0).asProto.getJsonName
res1: String = ""
```

**Comment by skizzybiz** [comment]
[test-scalapb.zip](https://github.com/scalapb/ScalaPB/files/1075958/test-scalapb.zip)

**Comment by skizzybiz** [comment]
[test-scalapb.zip](https://github.com/scalapb/ScalaPB/files/1075999/test-scalapb.zip)

**Comment by skizzybiz** [comment]
[test-scalapb.zip](https://github.com/scalapb/ScalaPB/files/1076001/test-scalapb.zip)

**Comment by thesamet** [comment]
You are setting `protobufVersion` to `2.5.0`. That version of protoc doesn't populate the `json_name` field and this is why the effect you are describing happens. Are you locked on 2.5.0 for a good reason? If you do, we could have ScalaPB suggest some default json name in case protoc left the thing empty.

**Comment by skizzybiz** [comment]
Ah, thank you! Let me look into whether we can switch to a more recent version.

**Comment by skizzybiz** [comment]
It looks like 2.6.1 is as far as we can upgrade, and it has the same problem. Can you make ScalaPB fill in the blanks?

**Comment by thesamet** [comment]
Fix available in scalapb-json4s 0.3.1

**Comment by skizzybiz** [comment]
That change appears to have caused a regression with extensions handling. I get errors like the following:

```
[error] /Users/joelyou/code/test-scalapb/target/scala-2.11/src_managed/main/foo/test/TestProto.scala:28: missing parameter type for expanded function ((x$1) => x$1.lengthDelimited)
[error]     _root_.com.trueaccord.scalapb.GeneratedExtension.forOptionalUnknownField(100, _.lengthDelimited)({__valueIn => __valueIn.toStringUtf8})
[error]                                                                                   ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 6 s, completed Jun 15, 2017 3:13:52 PM
```

Here's a modified version of your test case that should demonstrate the problem:

[foo.proto.txt](https://github.com/scalapb/ScalaPB/files/1079144/foo.proto.txt)

**Comment by thesamet** [comment]
Can you perform  `clean` in SBT and test again? Between 0.6.0-pre4 and 0.6.0-pre5 there were changes related to extensions that require code regeneration.

**Comment by skizzybiz** [comment]
`sbt clean` did the trick! Thanks!
