### ISSUE TITLE
Custom types conversion overhead due to duplicated calls in __computeSerializedValue()

### ISSUE THREAD

**Issue by nktpro** [scalapb/ScalaPB#294]
First of all thank you guys for creating and maintaining this project. It has become one of the most important dependencies for us.

Given this .proto file:

```
syntax = "proto3";

import "scalapb/scalapb.proto";
package test;

message Test {
  int64 foo = 1 [(scalapb.field).type = "some.custom.FooType"];
}
```

The generated case class will have this method:

```
private[this] def __computeSerializedValue(): Int = {
  var __size = 0
  if (test.Test._typemapper_foo.toBase(foo) != 0L) { __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(1, test.Test._typemapper_foo.toBase(foo)) }
  __size
}
```

Notice that `test.Test._typemapper_foo.toBase(foo)` will be called twice if the result is not the same with its default value. For complex messages with lots of custom type mappers, each being relatively expensive to convert, the compute overhead (and garbage generated) is significant. 

I'd be best to assign the result of the first call to a `val` and reuse it instead. This is actually already done properly in other places of the generated source code.

**Comment by thesamet** [comment]
Thanks for the detailed report. Would you like to send a PR?
