### ISSUE TITLE
Release 0.6.0 version

### ISSUE THREAD

**Issue by jvican** [scalapb/ScalaPB#297]
I was told that 0.6.0-pre2 can be considered as a release candidate for 0.6.0.
  
We're soon going to release Zinc 1.0.0-RC (sbt's incremental compiler, also used by Pants and other build tools) which depends on ScalaPB, and we would like to fix the scalapb dependency and be sure that we're using a stable release. This is a kind of a blocker for release.
  
I wonder, is there something missing to cut the final version of 0.6.0? Something I can help with?
  
Thanks for the quality of this library, it's really neat.

**Comment by ngbinh** [comment]
It is already released. We are using `0.6.0` at the moment.

**Comment by jvican** [comment]
@ngbinh Oh wow, I'm sorry, I asked about it and didn't get any answer in Gitter, so I thought it was not ready yet. Thanks, and closing.
