### ISSUE TITLE
Services not found in generated code on compilation

### ISSUE THREAD

**Issue by omrihq** [scalapb/ScalaPB#298]
Running into a few errors such as: 
```
type AbstractService is not a member of package com.trueaccord.scalapb.grpc
                       [error]   trait ScreenshotService extends _root_.com.trueaccord.scalapb.grpc.AbstractService {
```
and similarly with type `ServiceCompanion` when compiling. 

The version of `scalapb-runtime` is `0.5.27` and `scalapb-runtime-grpc` is `0.5.26`

**Comment by thesamet** [comment]
Looks like the version of the compilerplugin used to generate the code doesn't match the version of `scalapb-runtime-grpc` (and possibly `scalapb-runtime`). Can you make sure they all match and try again?  One way to ensure the versions match is to include grpc in the following way:

```
libraryDependencies ++= Seq(
    "io.grpc" % "grpc-netty" % com.trueaccord.scalapb.compiler.Version.grpcJavaVersion,
    "com.trueaccord.scalapb" %% "scalapb-runtime-grpc" % com.trueaccord.scalapb.compiler.Version.scalapbVersion
)
```

**Comment by omrihq** [comment]
Is there a way to see the static `com.trueaccord.scalapb.compiler.Version.*` values? I'm trying to do an experimental pants compilation with this.

**Comment by thesamet** [comment]
It is always the same version of the compilerplugin you are using (it would be `0.5.27` or `0.6.0`). If you are using scalapbc then the version of scalapbc should match the version of grpc and runtime.  It looks like the pants plugin I wrote is fixed to a version of scalapbc. Ideally the user should be able to configure it as ScalaPB gets released more often than the pants plugin.

**Comment by omrihq** [comment]
I see. It doesn't seem like there's a compilerplugin specified in any BUILD dependencies across scalapb-pants though. Is it defined elsewhere?

**Comment by thesamet** [comment]
It's a transitive dependency. There's a dependency on scalapbc which depends on compilerplugin (with the corresponding version)

**Comment by thesamet** [comment]
I believe this is resolved. Feel free to leave a comment if there's anything left to be addressed.
