### ISSUE TITLE
set default value to optional value

### ISSUE THREAD

**Issue by mehdimousavi1995** [scalapb/ScalaPB#300]
I want to set default value for optional value, here is my code 

`message Member {

    required int32 user_id = 1;
    required bool is_admin = 2;
    optional bool canSeeMessages = 5 [default = true];

}`

when i compile the code, default value in generated code is None  
how can i fix this ?

**Comment by thesamet** [comment]
This is by design. You can get the default value (`true` in this case) when you call `getCanSeeMessages`. See "Optional Fields" in https://scalapb.github.io/generated-code.html
