### ISSUE TITLE
Support custom base traits for enums

### ISSUE THREAD

**Issue by ejconlon** [scalapb/ScalaPB#304]
ScalaPB allows you to set "extends" and "companion_extends" to customize generated code for messages, but does not allow you to do the same for enums.

Practically speaking, my team noticed that scalacheck-shapeless was failing to generate Arbitrary instances for our generated enums, but we were unable to mix in a simple trait to remedy that.

Please let me know if you think this is a desirable feature, my team would be happy to help.  Thanks!

**Comment by thesamet** [comment]
Yes, a PR that implements `extends` and `companion_extends` is welcome.

**Comment by ejconlon** [comment]
Thanks.  Also, is there an objection to adding `type ValueType` to `GeneratedMessageCompanion` just like `GeneratedEnumCompanion`? It makes it easier to mix in things that refer to the message type.

**Comment by thesamet** [comment]
Sounds good.

**Comment by ruseinov** [comment]
@thesamet Hey Nadav, if you have any clues/preferences on how you want extends option for Enums implemented - please let me know. I did take a look at MessageOptions and a parser, it is not entirely straightforward, but doable.

**Comment by thesamet** [comment]
Had some time to do this myself. It will be available in ScalaPB 0.6.1. The docs are in "Custom base traits for enums" in https://scalapb.github.io/customizations.html

**Comment by ruseinov** [comment]
@thesamet got it

**Comment by ejconlon** [comment]
Thanks @thesamet @ruseinov ! Is there a target date for the release?

**Comment by thesamet** [comment]
Just released 0.6.1
