### ISSUE TITLE
JavaConversions still doesn't seem to work

### ISSUE THREAD

**Issue by gwooding** [scalapb/ScalaPB#317]
In this project:
https://github.com/thesamet/scalapb-maven-example

If I replace this line in the pom:
"<argument>-scala_out=${project.build.directory}/generated-sources/protobuf</argument>"

with this:
"<argument>--scala_out=java_conversions:${project.build.directory}/generated-sources/protobuf</argument>"

the code doesn't compile.

I get 12 errors, such as this:
/Users/georgewooding/scalapb-maven-example-2/target/generated-sources/protobuf/mvnexample/anotherexample/AnotherexampleProto.scala:12: error: object Anotherexample is not a member of package mvnexample
[ERROR]     mvnexample.Anotherexample.getDescriptor()

I'm on a large project where we use Maven (stuck with it for now), and need to compile both Scala and Java classes as we'd like to bring in the Scala classes incrementally.  Is my config wrong?  Everything else is exactly the same as the github project (on this day).

**Comment by thesamet** [comment]
When java conversions are enabled the generated Scala code references the Java protocol buffers which need to be generated too. If you're relying on scalapbc to generate the Java files as well, you need to add `--java_out=some/dir`

**Comment by gwooding** [comment]
Thanks!
