### ISSUE TITLE
grpc-stub 1.4.0 dependency

### ISSUE THREAD

**Issue by kbalyasnikov** [scalapb/ScalaPB#322]
com.trueaccord.scalapb:scalapb-runtime-grpc_2.12:0.6.* brings grpc-stub 1.4.0 dependency.

**Comment by xuwei-k** [comment]
What's the problem? Do you need grpc 1.5.0?

**Comment by kbalyasnikov** [comment]
grpc 1.5.0 is already specified by plugin but at the same time it introduces 1.4.0 dependency. To be ensured in compatibility I have to explicitly specify grpc-stub 1.5.0.

**Comment by xuwei-k** [comment]
https://github.com/scalapb/ScalaPB/tree/v0.6.2

**Comment by thesamet** [comment]
I believe this issue is now resolved. Let me know if there's still anything that needs to be looked at.
