### ISSUE TITLE
JSON conversion of Any is incorrect

### ISSUE THREAD

**Issue by holograph** [scalapb/ScalaPB#327]
This is essentially a followup on #255. Per the [Protobuf JSON spec](https://developers.google.com/protocol-buffers/docs/proto3#json) for Any, the result should be the same object contained in the Any plus a `@type` field giving the URL of the type. With the current version, Any is treated as any other `GeneratedMessage` and instead includes a `typeUrl` field and an encoded byte array `value` field, not per spec.

I've started hacking at this on [my fork](https://github.com/holograph/scalapb-json4s/commits/master), in particular adding suitable tests; unlike Value or Struct, this actually requires resolving the correct companion at runtime for reads. Since (as far as I can tell) ScalaPB doesn't have a notion of type registry, and furthermore maps generated classes to package names that don't match the proto spec, this turns out to be non-trivial, help would be appreciated...

**Comment by thesamet** [comment]
It looks like Google's implementation defines a [TypeRegistry](https://github.com/google/protobuf/blob/ba4e54724d2e6a1881c4fe88664d81fbacaf8c08/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L367) that the user has to manually initialize and provide to the parser. We can mimic this behavior, with the difference that the user initializes the TypeRegistry with a GeneratedMessageCompanion. It would be possible to traverse down to companions of messages referenced by this message using `messageCompanionForField`, but you will need to also add a method to traverse upwards to the companion of the file descriptor.

**Comment by holograph** [comment]
Took a further stab at it, the results are in my branch and I'll issue a PR shortly. There are three further concerns here:

1. Because the wrapped message (i.e. the instance of `GeneratedMessage` passed to `any.Any.pack`) isn't actually part of the generated class, we have to go through hoops to serialize the message: find companion -> unpack -> JSON-print -> add `@type` field. This is very inefficient (in memory and time) and can possibly be worked around by adjusting the generated code to include the source message on `pack`;
2. For the same reason, the message companion _must_ be registered even for serialization, which actually defeats my original reasoning for using `Any` (we have what you might consider a schema-agnostic, unidirectional Protobuf-to-JSON gateway). Encoding the original message via `pack` would solve the issue, at least for our use case;
3. I'm not very comfortable with the `FormatRegistry`, `Printer` and `Parser` divide. Specifically, both printer and parser rely on type information, but aren't actually provided by the registry. The convenience methods in `JsonFormat` assume a single registry as well. Wouldn't it make more sense to have `FormatRegistry` actually provide the parser and printer functionality?

Any and all comments welcome!

**Comment by holograph** [comment]
PR now available at https://github.com/scalapb/scalapb-json4s/pull/13

**Comment by holograph** [comment]
Thanks! I'm not quite clear on the recursive nature of the type registry, what's the use case for that?

**Comment by thesamet** [comment]
My primary reason was to follow the behavior of the Java TypeRegistry for consistency. My guess for why the official implementation does it is to make it easy to add whole projects into the recursively without enumerating each message.

**Comment by holograph** [comment]
Fair enough :-)
