### ISSUE TITLE
Possibility to compute default value

### ISSUE THREAD

**Issue by mvh77** [scalapb/ScalaPB#328]
Hi,

I'd love to see a way to generate/compute a default value at the case class level, could be defined like this:

```
message FooBar {
  required string message_id = 1 [(scalapb.field).compute_default = "java.util.UUID.randomUUID().toString"];
  ...
}
```
Thank you for a great project!

**Comment by thesamet** [comment]
While it's probably a simple change to make, it would complicate the semantics as we will have two types of default values (the one defined in the proto language and the one proposed here).

What you can do for your use case would be to extend the companion object to add a constructor that sets the field:

In your proto:
```
message FooBar {
  option (scalapb.message).companion_extends = "FooBarCompanionMixin";
  required string message_id = 1;
}
```

and in your code:

```
trait FooBarCompanionMixin {
  def apply(x: String) = FooBar(message_id=UUID.randomUUID().toString(), x=x)
}
```

If you have many message types with a message_id field, with some effort it's probably possible to define a single mixin (parameterized by the type name) that will work for all of them.
