### ISSUE TITLE
there is no `v0.6.2` tag

### ISSUE THREAD

**Issue by SethTisue** [scalapb/ScalaPB#340]
(just an oversight, I suppose?)

**Comment by thesamet** [comment]
Actually, there is: https://github.com/scalapb/ScalaPB/tree/v0.6.2  am I missing anything?

**Comment by SethTisue** [comment]
sorry for the noise

**Comment by SethTisue** [comment]
how my local clone ended up with v0.6.1 tags and v0.6.3 tags but no v0.6.2 tag I don't know but oh well, `git fetch --tags` fixed it
