### ISSUE TITLE
Compilation error when using proto from Google APIs

### ISSUE THREAD

**Issue by jayho** [scalapb/ScalaPB#344]
## Summary
I get an `object type is not a member of package com.google` error when trying to `sbt compile` a proto file from the [Google APIs](https://github.com/googleapis/googleapis).

In this case it was `money.proto` from package `google.type`. It seems that the package name causes problems as it is a Scala keyword.

## Versions
`scalaVersion=2.12.3`
`sbt.version=1.0.1`

## Operating System
`Microsoft Windows [Version 6.1.7601]`

(hence [using python](https://scalapb.github.io/sbt-settings.html#running-on-windows))

## Build Setup
See https://github.com/jayho/scalapb-mcve

I use version *0.6.0* of the compiler plugin due to issue https://github.com/scalapb/ScalaPB/issues/341

## Output
See https://gist.github.com/jayho/504d4ec178247d06d655211c35802c5a

## Expected Behaviour
generates scala code and compiles

## Actual Behaviour
compilation error

**Comment by thesamet** [comment]
Hi @jayho,

Adding `googleapis-common-protos` as a dependency marked with `"protobuf"` makes the protos inside that jar available on the search path for protoc, but it doesn't generate Scala code for them. This allows running protoc over local proto files that depend on the protos that come from the jar. However, it assumes that the Scala classes for the protos in the jar are provided somehow, possibly by a standard `libraryDependency`. One way around it, is to generate the Scala code for the third party protos at the same time you are generating code for your own protos. You can achieve this by adding this:

```
// Generate scala classes for all protos under "google/type"
PB.protoSources in Compile += PB.externalIncludePath.value / "google" / "type"

// Since protoSources is passed to the include path, and externalIncludePath is already in there
// we need to remove this extra path to prevent duplicate compilation.
￼PB.includePaths in Compile -= PB.externalIncludePath.value / "google" / "type"
```

**Comment by jayho** [comment]
Hi @thesamet,

this makes sense and works perfectly. Thanks for taking the time for a detailed explanation and the great plugin.
