### ISSUE TITLE
oneof option for mixing trait/class in the inner subtype of GeneratedOneof

### ISSUE THREAD

**Issue by mushtaq** [scalapb/ScalaPB#345]
```
oneof items  {
  option (scalapb.message).extends = "MyCustomTrait";
  BankAccount bankAccount = 1;
  CreditAccount creditAccount = 2;  
}
```
should generate the following inner trait:

```
 sealed trait Items extends _root_.com.trueaccord.scalapb.GeneratedOneof with MyCustomTrait
```

Without this I had to struggle a lot to create abstractions on top of oneof types.

**Comment by thesamet** [comment]
See usage example here: https://github.com/scalapb/ScalaPB/blob/be06c00daf57646e5714abf39c08da0f2916f449/e2e/src/main/protobuf/custom_options_use.proto#L23
