### ISSUE TITLE
Fastparse library is not binary compatible for 0.4.x

### ISSUE THREAD

**Issue by LogicalTime** [scalapb/ScalaPB#350]
I get linking errors when using scalapb and akkajs. They are on fastparse 0.4.2 and you are on 0.4.4 now. 
fastparse.all$.CharsWhile() is removed between 0.4.2 and 0.4.4.
Fastparse documentation says it's not binary compatible. Perhaps we should all them to release a binary compatible 1.0.x. Parboiled2 is released for Scalajs I believe (check out scala-uri's dependencies).

**Comment by thesamet** [comment]
Can you try forcing your project to pick 0.4.2?

**Comment by thesamet** [comment]
There's very little I can do on my end to avoid this problem. I'd suggest that you try producing an uber jar of ScalaPB with a shaded fastparse.

**Comment by LogicalTime** [comment]
At my request fastparse has released a 1.0.0 version which should be binary compatible going forward. Just update the dependency and this issue goes away.

**Comment by thesamet** [comment]
Bumped up fastparse in 160cbb8

**Comment by LogicalTime** [comment]
Excellent thank you!
