### ISSUE TITLE
Strip common enum prefixes

### ISSUE THREAD

**Issue by jsw** [scalapb/ScalaPB#353]
Has there been consideration to adding an option to strip common enum value prefixes such that

```
enum ImageSize {
  IMAGE_SIZE_SMALL = 0;
  IMAGE_SIZE_LARGE = 1;
}


enum ButtonSize {
  BUTTON_SIZE_SMALL = 0;
  BUTTON_SIZE_LARGE = 1;
}
```

would result in something like:

```
object ImageSize {
  case object SMALL extends ImageSize ...
  case object LARGE extends ImageSize ...
}


object ButtonSize {
  case object SMALL extends ButtonSize ...
  case object LARGE extends ButtonSize ...
}
```

If not, is there a better workaround for dealing with the enum scoping constraint?

**Comment by thesamet** [comment]
PR will be welcome. Probably something like: `strip_prefix="IMAGE_SIZE_"`

**Comment by jsw** [comment]
I think a global option that follows what the C# compiler does would work well

https://developers.google.com/protocol-buffers/docs/reference/csharp-generated#enum

jeff

**Comment by thesamet** [comment]
Will not do for now to keep things simple.
