### ISSUE TITLE
java_package not consistent with documented usage in java

### ISSUE THREAD

**Issue by jsw** [scalapb/ScalaPB#359]
> If the java_package option is defined, then the Scala package will be java_package.base_name where base_name is the name of the proto file without the .proto extension.

> If the java_package is undefined, but the file specifies a package name via the package keyword then the Scala package will be package.base_name.

does not seem to be consistent with 

[https://developers.google.com/protocol-buffers/docs/reference/java-generated#package](https://developers.google.com/protocol-buffers/docs/reference/java-generated#package)

I think `base_name` should be omitted from the package. I realize there is a ScalaPB option to set the package, but given `java_package` and `package` are used, I would expect the behavior to be the same as generated java code.

**Comment by thesamet-st** [comment]
The Java implementation puts all messages inside an outer class named BaseName, so ScalaPB is consistent with that in the sense that the file name becomes a part of the message fully qualified class name). 

The generated full class names are intentionally not identical so one can have both the Java and Scala files together for a gradual migration of a project.

Besides the option to customize the package name with `scala_package, there's another option called `flat_package` which would end up generating the naming scheme you suggest (dropping base_name): https://scalapb.github.io/customizations.html

**Comment by thesamet** [comment]
The Java implementation puts all messages inside an outer class named BaseName, so ScalaPB is consistent with that in the sense that the file name becomes a part of the message fully qualified class name).

The generated full class names are intentionally not identical so one can have both the Java and Scala files together for a gradual migration of a project.

Besides the option to customize the package name with scala_package, there's another option calledflat_package` which would end up generating the naming scheme you suggest (dropping base_name): https://scalapb.github.io/customizations.html

**Comment by jsw** [comment]
Thanks for the explanation, and the tip on `flat_package`. 

I also see that if `java_multiple_files = true` then it generates Java code inside the package name instead of inside an outer class. I am following google's API design guide, with the recommended options mentioned here: [https://cloud.google.com/apis/design/file_structure](https://cloud.google.com/apis/design/file_structure)

**Comment by thesamet** [comment]
The `java_multiple_files` is equivalent to `flat_package` in ScalaPB, however, if both are enabled in a project the class names will collide.

Closing this issue - let me know if there's anything that is still unaddressed.
