### ISSUE TITLE
scalapb.UdtGenerator Generates Code With Compile-Time Errors for Custom MessageOptions and FieldOptions

### ISSUE THREAD

**Issue by jeffquinn-nuna** [scalapb/ScalaPB#374]
We have a protofile that looks like this:

`meta.proto`
```
extend google.protobuf.FieldOptions {
    optional string myFieldOption = 50000;
}
extend google.protobuf.MessageOptions {
    optional string myMessageOption = 50001;
}
```

When we run the scalapb.UdtGenerator, it creates classes like this:

```
object MetaProtoUdt {
  def register(): Unit = {} // actual work happens at the constructor.

  my.package.MetaProtoUdt.register()
}
```

The problem is the method `my.package.MetaProtoUdt#register` is never generated, so this raises a compile time error.

**Comment by thesamet** [comment]
Are you generating UDTs for all the protos, including the dependency of these? For example, if you import `google/protobuf/descriptor.proto` then you need to generate UDTs for that as well.

**Comment by jeffquinn-nuna** [comment]
Ah good call. Specifically passing `google/protobuf/descriptor.proto` as a proto to be compiled to ScalaPBC worked. We were not doing that previously. Closing :)
