### ISSUE TITLE
[Question] Is Protocol Buffers 3.5.x supported?

### ISSUE THREAD

**Issue by ldionne** [scalapb/ScalaPB#380]
The README states that ScalaPB 0.6 supports up to 3.4.x; does it actually support up to 3.5.x but the README was not updated, or is there a reason why it does not support it?

**Comment by thesamet** [comment]
ScalaPB 0.6.x is compiled against Protobuf 3.4.x, but is known to work with 3.5.x as well. I updated the documentation.

**Comment by ldionne** [comment]
Thank you! I could have sent a PR, but you're very fast. :-)
