### ISSUE TITLE
Support for Scala Native

### ISSUE THREAD

**Issue by xeno-by** [scalapb/ScalaPB#387]
First of all, thank you for your work on ScalaPB. We've been using it in Scalameta to implement SemanticDB, and it's been working really well for us!

In 2018, we'd like to cross-compile our SemanticDB-based tools to Scala Native. Towards that end, we've opened tickets https://github.com/scalameta/scalameta/issues/772 and https://github.com/twitter/reasonable-scala/issues/10. The only blocker for us at the moment is `scalapb-runtime`.

Is publishing Scala Native-compatible artifacts on your roadmap?

**Comment by thesamet** [comment]
Yes, I've been thinking of doing this. The native scala replacement for Google's protobuf-java that was developed for Scala.js would come in handy.

**Comment by xeno-by** [comment]
Do you maybe have time estimates when Scala Native support may ship? If you'd like outside help, how much time would it take for someone unfamiliar with ScalaPB to see this through?

**Comment by thesamet** [comment]
I am not familiar with Scala native, so I'm not sure what the challenges are going to be. I'll take a stab at it in the next week or so to get a better idea and update here.

**Comment by xuwei-k** [comment]
https://github.com/scalapb/protobuf-scala-runtime/pull/11

**Comment by thesamet** [comment]
I published 0.7.0-rc7 which adds support for Scala Native.

**Comment by xeno-by** [comment]
@thesamet Thank you very much for your work! Is this artifact supposed to be immediately usable from the `sbt-protoc` plugin, or there are additional steps that are required for full Scala Native support there?

**Comment by xeno-by** [comment]
Here's what I tried:

1) First, I went to https://github.com/xeno-by/reasonable-scala/tree/10 - the branch of Rsc, where I'm working on adding support for SemanticDB. (The Scala Native part of the build in that branch is broken, so I'm only working in the JVM part).

2) Then, I applied the following diff to the build definition:
```diff
diff --git a/build.sbt b/build.sbt
index 0cf0a272cb..d7f26781be 100644
--- a/build.sbt
+++ b/build.sbt
@@ -96,7 +96,7 @@ lazy val rsc = crossProject(JVMPlatform, NativePlatform)
     buildInfoKeys := Seq[BuildInfoKey](
       version
     ),
-    libraryDependencies += "com.trueaccord.scalapb" %% "scalapb-runtime" % versions.scalapbVersion,
+    libraryDependencies += "com.thesamet.scalapb" %% "scalapb-runtime" % "0.7.0-rc7",
     PB.targets.in(Compile) := Seq(
       scalapb.gen(flatPackage = true) -> sourceManaged.in(Compile).value
     ),
```

3) Then, I hit `rscNative/nativeLink` and got a mixture of warnings and error messages:

```
> rscNative/nativeLink
[info] Compiling 105 Scala sources to /Users/eburmako/Projects/rsc/rsc/.native/target/scala-2.11/classes...
[error] /Users/eburmako/Projects/rsc/rsc/.native/target/scala-2.11/src_managed/main/rsc/semanticdb/Database.scala:11: class Database needs to be abstract, since method toProtoString in trait GeneratedMessage of type => String is not defined
[error] final case class Database(
[error]                  ^
[warn] /Users/eburmako/Projects/rsc/rsc/.native/target/scala-2.11/src_managed/main/rsc/semanticdb/Database.scala:13: type GeneratedMessage in package scalapb is deprecated: Please use scalapb package instead of com.trueaccord.scalapb
[warn]     ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[Database] with com.trueaccord.lenses.Updatable[Database] {
[warn]                                      ^
[warn] /Users/eburmako/Projects/rsc/rsc/.native/target/scala-2.11/src_managed/main/rsc/semanticdb/Database.scala:13: type Message in package scalapb is deprecated: Please use scalapb package instead of com.trueaccord.scalapb
[warn]     ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[Database] with com.trueaccord.lenses.Updatable[Database] {
[warn]                                                                                   ^
...
[warn] 144 warnings found
[error] 8 errors found
[error] (rscNative/compile:compileIncremental) Compilation failed
[error] Total time: 3 s, completed Jan 14, 2018 9:47:37 PM
```

Am I doing anything wrong?

**Comment by thesamet** [comment]
It looks like you were able to overcome the compilation errors by just clean and regenerating the code. The old files referenced the now deprecated classes.

The linkage errors indicate that scalapb-runtime isn't around. For Native and JS, sbt-protoc doesn't know how to automatically add it, so you need to manually add something like this into the settings of the native project:
```
libraryDependencies ++= Seq(
  "com.thesamet.scalapb" %%% "scalapb-runtime" % scalapb.compiler.Version.scalapbVersion
)
```

**Comment by xeno-by** [comment]
It works!! 🎉

**Comment by xuwei-k** [comment]
FYI, scalapb-argonaut 0.2.0-M1 released with scala-native support https://github.com/scalapb-json/scalapb-argonaut/commit/83dc89cacdcb28fae9586789ca0e162c10c7de82
