### ISSUE TITLE
Allow way to specify custom type at the message level

### ISSUE THREAD

**Issue by thesamet** [scalapb/ScalaPB#39]
When a custom type is specified at the message level, it should be applied for all references to that type.

**Comment by PerWiklander** [comment]
Will this work like a type alias then?

Today I have messages like these in my proto:

```
message OrderId {
  optional string value = 1;
}
```

I would like to make any reference to it, like:

```
message Order {
  optional OrderId id = 1;
}
```

work as if I had used:

```
message Order {
   optional string id = 1 [(scalapb.field).type = "mydomain.OrderId"];
}
```

I also don't see any reason for not generating the ```OrderId``` case class and companion object in this scenario.

**Comment by thesamet** [comment]
Duplicate of #347
