### ISSUE TITLE
Release scalapbc artifact for v0.7.0-rc7 

### ISSUE THREAD

**Issue by zackangelo** [scalapb/ScalaPB#392]
@thesamet would it be possible for you to post an artifact for scalapbc v0.7.0-rc7? Looks like it was released for RC6, but not RC7. Would like to start testing against it.

**Comment by thesamet** [comment]
@zackangelo the artifact is still not there. A bug in travis.yml that was fixed in e08dfd27b7cf99cea65ab7ff975bc6a9f1d59899 will ensure that we get it for the next RC. Let me know if you still need it for rc7.

**Comment by zackangelo** [comment]
@thesamet thanks! we just ended up building it ourselves, but will keep an eye out for rc8
