### ISSUE TITLE
Generated Scala from OpenRTB has malformed classname 

### ISSUE THREAD

**Issue by joshlemer** [scalapb/ScalaPB#394]
When compiling Google's OpenRTB protobuf files, some generated scala comes out with malformed class names which mean that those classes' Canonical Name cannot be created, which means that we cannot use them in Flink.

For example:
```scala
import com.google.openrtb.BidRequest
import org.apache.flink.api.common.typeinfo.TypeInformation
import org.apache.flink.api.scala._


object Main {

  def main(args: Array[String]): Unit = {
    println(classOf[BidRequest.Imp.Native])
    println(classOf[BidRequest.Imp.Native].getCanonicalName)
  }
}
```

gets this output:

```
class com.google.openrtb.BidRequest$Imp$Native
Exception in thread "main" java.lang.InternalError: Malformed class name
	at java.lang.Class.getSimpleName(Class.java:1330)
	at java.lang.Class.getCanonicalName(Class.java:1399)
	at scalapberror.Main$.main(Main.scala:12)
	at scalapberror.Main.main(Main.scala)
```

I have also created an example project that reproduces this error:
https://github.com/joshlemer/ScalaPBMalformedClassname

Steps to reproduce:

```
git clone https://github.com/joshlemer/ScalaPBMalformedClassname
cd ScalaPBMalformedClassname
sbt run
```

**Comment by joshlemer** [comment]
Ah indeed this returns the same error:
```scala
object A {
  object B {
    class C {

    }
  }
}
println(classOf[A.B.C].getCanonicalName)
```
As for a minimal example here is that:
```protobuf
message A {
	string a = 1;
	message B {
		string b = 1;
		message C {
			string c = 1;
		}
	}
}
```

Do you have a recommended work-around, or plan to support these nested classes in the future with maybe packages? Or are we just stuck using the generated Java instead? 

Thanks!

**Comment by thesamet** [comment]
Looks like it is indeed SI-2034. As for a workaround - it really depends on what you need the canonical name for. One alternative is getting the message full name: `A.B.C.scalaDescriptor.fullName`

**Comment by joshlemer** [comment]
Okay well I think the "work-around" we will use is to just deploy on JDK9, which seems to work fine. 

Thanks again!

**Comment by dat-vikash** [comment]
i've run into this as well when trying to deploy Flink apps on EMR. I upgraded to jdk11 and the error went away
