### ISSUE TITLE
Expose comment on FieldDescriptor

### ISSUE THREAD

**Issue by macalinao** [scalapb/ScalaPB#396]
It would be great for the `comment` of a field to be exposed in the FieldDescriptor. This might need to be done in the compiler?

**Comment by thesamet** [comment]
I have some work in progress that expose this. I am curious to know what's the use case for this feature request?

**Comment by macalinao** [comment]
GraphQL field descriptions via Sangria.

**Comment by macalinao** [comment]
https://github.com/macalinao/sangria-scalapb -- This is my project by the way. I plan on marketing it once this feature is implemented.

**Comment by macalinao** [comment]
@thesamet Have you made any progress on this?

**Comment by thesamet** [comment]
It turns out that generators omit the comments information to save on code size. We can add an option to have ScalaPB include comments in the descriptor (off by default), but that would require users to specify it when they generate their Scala code. Would that work?

**Comment by macalinao** [comment]
Yes, that would be great!

**Comment by macalinao** [comment]
Thank you so much @thesamet !!! :smile:
