### ISSUE TITLE
JS project pulls in JVM version of 'scalapb-runtime'

### ISSUE THREAD

**Issue by ngbinh** [scalapb/ScalaPB#397]
Repro here https://github.com/ngbinh/scalapbCross

```
barJS/dependencyTree
[info] Updating {file:/home/binh/works/external/scalapbCross/}barJS...
[info] Done updating.
[info] bar:bar_sjs0.6_2.12:0.1-SNAPSHOT [S]
[info]   +-com.thesamet.scalapb:scalapb-runtime_2.12:0.7.0-rc7 [S]
[info]   | +-com.google.protobuf:protobuf-java:3.5.0
[info]   | +-com.lihaoyi:fastparse_2.12:1.0.0 [S]
[info]   | | +-com.lihaoyi:fastparse-utils_2.12:1.0.0 [S]
[info]   | | | +-com.lihaoyi:sourcecode_2.12:0.1.4 [S]
[info]   | | | 
[info]   | | +-com.lihaoyi:sourcecode_2.12:0.1.4 [S]
[info]   | | 
[info]   | +-com.thesamet.scalapb:lenses_2.12:0.7.0-test2 [S]
[info]   | 
[info]   +-org.scala-js:scalajs-library_2.12:0.6.22 [S]
[info]   
```

Note that `barJS` is a `scala.js` project so it should not depend on `scalapb-runtime_2.12`

**Comment by thesamet** [comment]
This is happening since `sbt-protoc` adds a dependency on `scalapb-runtime` for all projects. It's not aware of ScalaJS so the failure happens [around here](https://github.com/thesamet/sbt-protoc/blob/c29d4d6c6074b25edda1efdabd89eddea27fe770/src/main/scala-sbt-1.0/sbtprotoc/Compat.scala#L10).

Help on this will be appreciated.

**Comment by ragazzojp** [comment]
A similar problem is related to java bindings and the scala runtime (not the scalapb-runtime). If only java bindings are compiled, so:

```scala
PB.targerts in Compile := Seq(
  PB.gens.java -> (sourceManaged in Compile).value
)
```

`scala-library` seems to be added to the dependencies, when there are no actual generated scala files.

**Comment by xuwei-k** [comment]
https://github.com/thesamet/sbt-protoc/pull/67
