### ISSUE TITLE
Case Classes not final when using oneof

### ISSUE THREAD

**Issue by rabbitonweb** [scalapb/ScalaPB#400]
I have a 

```
message Ping {
}
```
it will generate case class with `final` which makes my WartRemover happy :)

```
final case class Pong(
    ) extends com.trueaccord.scalapb.GeneratedMessage with ...
```

however if I use `OneOf` like

```
message Protocol {
    (....)
    oneof message {
       (...)        
        Pong                pong            = 5;
        (...)
    }
}
```

I will get case class *without* final modifier

```
  object Message extends {
    (...)
    @SerialVersionUID(0L)
    case class Pong(value: coop.rchain.comm.protocol.routing.Pong) extends coop.rchain.comm.protocol.routing.Protocol.Message {
```

which makes my WartRemover a saaaddd panddddaa... 

Also adding annotations described in https://scalapb.github.io/customizations.html will not work for OneOf - which I tried to use as a workaround.

I'm happy to work on PR that will fix this issue, if I could get some quick guidance of where to start (which file(s) to modify). <---- IMPORTANT :)

**Comment by thesamet** [comment]
Look for it in `ProtobufGenerator.scala`. Run `make_plugin_protos.sh` before sending the PR since the change might cause diffs in the generated source code that is checked in.

**Comment by rabbitonweb** [comment]
Awesome, let me get back to you with PR
