### ISSUE TITLE
Preserve unknown fields by default in Proto3

### ISSUE THREAD

**Issue by erinmez** [scalapb/ScalaPB#406]
According to [Enforce Unknown Fields Preservation in Proto3](https://docs.google.com/document/d/1KMRX-G91Aa-Y2FkEaHeeviLRRNblgIahbsk4wA14gRk/edit#heading=h.w8dtggryroj4) it is intended to flip the default and keep unknown fields. Apparently, this has already been made the default in [Protobuf Java 3.5.0](https://github.com/google/protobuf/releases/tag/v3.5.0). It would be great if this could be done in ScalaPB as well.

**Comment by thesamet** [comment]
Since we have had a few release candidates for 0.7 and this is potentially breaking, this will come in 0.8.x.
