### ISSUE TITLE
It is not allowed to specify the scala `Map` type when using `proto3` `map`s

### ISSUE THREAD

**Issue by franbh** [scalapb/ScalaPB#410]
It would be great if `ScalaPB` allowed us to specify which type of scala `Map` is going to be used when declaring `proto3` `map`s. Right now, it is restricted to `scala.collection.immutable.Map`, but sometimes it is [better](http://www.lihaoyi.com/post/BenchmarkingScalaCollections.html#sets-and-maps-are-slow) to use mutable `Map`s.
Namely, I'm thinking about an option like this:
`map<string, string> my_map = 1 (scalapb.field).map_type = "scala.collection.mutable.Map"`

WDYT?

**Comment by thesamet** [comment]
It makes sense to add this. Can you work on a PR? It would be worth exploring if `(scalapb.field).collection_type` could be used for this rather than adding map_type.

**Comment by franbh** [comment]
Sure, I'll try to find some free time and look into it.

**Comment by ollyw** [comment]
Any progress on support for this? I have a similar use case that I would really like to be able to specify `(scalapb.field).collection_type = "scala.collection.immutable.SortedMap"`
