### ISSUE TITLE
support for service frameworks other than gRPC

### ISSUE THREAD

**Issue by dsilvasc** [scalapb/ScalaPB#411]
Hi,

There are a number of service frameworks on top of protocol buffers other than gRPC, including Twirp:
https://twitchtv.github.io/twirp/docs/example.html
https://github.com/twitchtv/twirp#implementations-in-other-languages

Would it be possible to support client/server generators for other service frameworks like prost does for rust?
https://github.com/danburkert/prost/#services
https://docs.rs/prost-build/0.3/prost_build/trait.ServiceGenerator.html

**Comment by thesamet** [comment]
Yes, it would be possible. The way to move forward with it is to implement them as custom code generator and potentially a runtime library. Examples of a custom code generator is here: https://github.com/thesamet/sbt-protoc/tree/master/examples/custom-gen  will be happy to review a PR. Will you be able to work on this?

**Comment by dsilvasc** [comment]
Thank you, that's very helpful.  I mentioned Twirp as an example but my actual use case is an RPC framework internal to my employer at the moment.  Hopefully if the protocol spec and framework get released we can release a scalapb-based generator too.

In the meantime I think I can work on a generator here that provides a stripped down version of what the gRPC one generates as a baseline for other generators.

**Comment by thesamet** [comment]
Sounds good. I'll be closing this ticket then. As you work on your custom generator, feel free to ask questions in our Google Group or Gitter channel.
