### ISSUE TITLE
package prefixes or suffixes for all files

### ISSUE THREAD

**Issue by dsilvasc** [scalapb/ScalaPB#413]
When the flatPackage option is set to true, ScalaPB generates classes with the same fully qualified names (package name and class name) as the protoc Java generator.

To avoid the clash while keeping flat packages, would it be possible to specify a global package prefix or suffix?  For example, given a proto message Baz in proto (and/or java) package foo.bar, a package suffix of ".scala" would generate a Java class foo.bar.Baz and a Scala class foo.bar.scala.Baz

**Comment by thesamet** [comment]
You can specify a Scala package name for each file as a file-level option: https://scalapb.github.io/customizations.html

There's no mechanism for requesting a prefix/suffix to the generated code. The best route to avoid name clashes with Java is to keep `flatPackage=false`
