### ISSUE TITLE
Repeated fields are null for old messeges

### ISSUE THREAD

**Issue by lasekio** [scalapb/ScalaPB#418]
When I add repeated field for old messages persited in DB i get null value. I expect empty `Seq.empty` or `Option` at least.

**Comment by thesamet** [comment]
What function do you use to decode the old messages persisted in the DB? `parseFrom` and friends should never give you a null.

**Comment by lasekio** [comment]
Seems I have been using`JavaSerializer` in Akka, which handles generated case classes. Problem solved, I use `akka.remote.serialization.ProtobufSerializer` now.
