### ISSUE TITLE
0.7.x version proto3 json4s doesn't render enums

### ISSUE THREAD

**Issue by mao-vcs** [scalapb/ScalaPB#420]
Got a question? Please use https://groups.google.com/forum/#!forum/scalapb instead.

**Comment by mao-vcs** [comment]
My blame, it was without import scalapb.json4s.JsonFormat

**Comment by mao-vcs** [comment]
The issue still exists, but only with proto3 syntax
example project https://github.com/mao-vcs/scalapb-json-issue/

**Comment by thesamet** [comment]
Hi @mao-vcs, for Proto3, default values for any field are not rendered. Try assigning a non-zero value to that enum, and it should be rendered. This behavior is documented towards the end of this page https://scalapb.github.io/json.html and the spec is here (https://developers.google.com/protocol-buffers/docs/proto3#json). There's a `Printer` flag that allows you to modify this behavior so default values are rendered as well.
