### ISSUE TITLE
FileDescriptor ignores flat_package option

### ISSUE THREAD

**Issue by nau** [scalapb/ScalaPB#428]
When flat_package=false (default) scalapb generates class `com.foo.example.Test ` for this proto file
example.proto:

    package com.foo
    message Test {}

but `ExampleProto.messages.head.map(_.fullName)` would be `com.foo.Test`.

That makes reflection much more complicated :)

**Comment by thesamet** [comment]
The descriptors `fullName` field maps refers to the name of the symbol within the proto namespace, not Java's or Scala's namespace. If you'll set `java_package` and `scala_package` - fullName won't be affected as well. In other words, if you are looking at this field to find the message class's name in Scala you are looking in the wrong place.

There's another path that you could take, which is to look into the proto file companion object. If you have x.proto look for XProto. Instead it there's a field called `messageCompanions` which is a vector of all the top-level message companions. You could use them to produce a map between descriptors and the message's class name. Note that each message companion object contain a (possibly empty) list of message companions, as messages in protos may be statically defined within other messages.

**Comment by thesamet** [comment]
I haven't heard anything for a while, so I am closing this ticket. Feel free to reach out if you have additional questions on this matter.

**Comment by nau** [comment]
Forgot to comment this, sorry.
I did take a suggested solution with `messageCompanions` and it worked quite well. Thank you!
