### ISSUE TITLE
ScalaPB cannot be run behind a Proxy

### ISSUE THREAD

**Issue by lostiniceland** [scalapb/ScalaPB#435]
I am within a corporate environment and need to run scalapbc on the command line (no SBT project).

Since scalapbc is trying to download the protoc compiler it has to use our proxy which I cannot configure (at least the documentationd doesnt mention it).
I've tried 
```

scalapbc --scala_out=flat_package:src/main/scala-gen src/main/proto/file.proto -Dhttp.proxyHost=proxyHost -Dhttp.proxyPort=port -Dhttp.proxyUser=myuser-Dhttp.proxyPassword=myPW -Dhttps.proxyHost=proxy -Dhttps.proxyPort=port -Dhttps.proxyUser=myuser -Dhttps.proxyPassword=pw
```

Protoc in on my path, so maybe there's a way to utilize this.

**Comment by thesamet** [comment]
scalapbc uses [protoc-jar](https://github.com/os72/protoc-jar) which embeds a number of protoc versions in it so you don't have to download. If you explicitly specify a version that is embedded in it, it wouldn't have to download. Try this:

    scalapbc -v3.5.1 ...

Another alternative to prevent a download is to have protoc installed somewhere on your system and you can invoke it like this:

    scalapbc --protoc=/path/to/protoc ...

**Comment by lostiniceland** [comment]
Close as works as designed

Using a specific version does not cause problems behind firewalls.
