### ISSUE TITLE
Add Reflection Service

### ISSUE THREAD

**Issue by simplesteph** [scalapb/ScalaPB#442]
I might have missed it, but I think the reflection service is missing?
Something like this: https://github.com/grpc/grpc-java/blob/master/documentation/server-reflection-tutorial.md

**Comment by jyane** [comment]
I don't quite follow this repo but you can use the ProtoReflectionService via grpc-java.
e.g. `io.grpc" % "grpc-services" % scalapb.compiler.Version.grpcJavaVersion` and then `server.addService(ProtoReflectionService.newInstance())`.

It works on my hobby scalapb service.

**Comment by simplesteph** [comment]
Sweet this works thanks!
