### ISSUE TITLE
Java 10 not recognized

### ISSUE THREAD

**Issue by lostiniceland** [scalapb/ScalaPB#443]
Running ScalaPB with Java 10 result in the following error

```
The java installation you have is not up to date
requires at least version 1.6+, you have
version 10.0.1
```
 
Probably the new version-scheme isnt recognized.

**Comment by thesamet** [comment]
Hi @lostiniceland - can you add more details? Do you use SBT? Does SBT load? If so, at what stage does this message get printed?

**Comment by lostiniceland** [comment]
No, not using SBT, my projects are based on Gradle right now. I am actually generating the file via a little shell-script with ScalaPB and Protoc on my path

`scalapbc --scala_out=flat_package:build/generated/source/proto/main/java src/main/proto/my.proto`

**Comment by thesamet** [comment]
To clarify, are you getting the error you posted above when you attempt to run `scalapbc` ?

**Comment by lostiniceland** [comment]
yes

**Comment by xuwei-k** [comment]
- https://github.com/sbt/sbt-launcher-package/blob/d76459db699ab36d0d05418c8a8993c0e95822fa/src/universal/bin/sbt-launch-lib.bash#L241-L246
- https://github.com/sbt/sbt-launcher-package/pull/209
- https://github.com/sbt/sbt-launcher-package/pull/219
- https://github.com/sbt/sbt-launcher-package/pull/225
- https://github.com/sbt/sbt-launcher-package/pull/195

use old sbt🤔 ?

**Comment by thesamet** [comment]
I wasn't able to reproduce this problem. Here is what I did:

```
docker run --rm -ti openjdk:10-jdk /bin/bash

wget https://github.com/scalapb/ScalaPB/releases/download/v0.7.4/scalapbc-0.7.4.zip

unzip scalapbc-0.7.4.zip 

./scalapbc-0.7.4/bin/scalapbc 
[normal output]
```

Can you provide a way to reproduce this problem, ideally in a docker container?

**Comment by thesamet** [comment]
I was able to reproduce this in Ubuntu 18.04. Upgrading sbt-native-package resolved this issue.

**Comment by lostiniceland** [comment]
Thanks for your effort to reproduce (due to vacation I couldnt provide it myself).
