### ISSUE TITLE
NullPointerException on generated case classes with null values for String fields

### ISSUE THREAD

**Issue by DimaLiah** [scalapb/ScalaPB#450]
When I have a proto message:
```
message AMessage {
  string aString = 1;
}
```
for which scalaPB generates a case class `case class AMessage {...}`,
when I instantiate an instance of the class with `aString = null`, and call it's `toString()`, I get `NullPointerException`

```
val myMessage = AMessage(aString = null)
myMessage.toString()
```

Exception's stacktrace:
```
at scalapb.textformat.TextFormatUtils$.escapeDoubleQuotesAndBackslashes(TextFormatUtils.scala:160)
	at scalapb.textformat.TextGenerator.addMaybeEscape(TextGenerator.scala:29)
	at scalapb.textformat.Printer$.printFieldValue(Printer.scala:74)
	at scalapb.textformat.Printer$.printSingleField(Printer.scala:41)
	at scalapb.textformat.Printer$.printField(Printer.scala:28)
	at scalapb.textformat.Printer$$anonfun$print$2.apply(Printer.scala:13)
	at scalapb.textformat.Printer$$anonfun$print$2.apply(Printer.scala:12)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scalapb.textformat.Printer$.print(Printer.scala:12)
	at scalapb.textformat.Printer$.print(Printer.scala:8)
	at scalapb.textformat.Printer$.printToString(Printer.scala:19)
	at scalapb.TextFormat$.printToUnicodeString(TextFormat.scala:34)
	at com.example.AMessage.toString(AMessage.scala:86)
```

I wouldn't expect any class to throw a NullPointerException on `toString` invocation.

**Comment by DimaLiah** [comment]
Thanks for the quick reply.
I have a service (its API is defined in proto) which exposes an rpc endpoint.
It receives a request with a JWT token inside as an input (it's a string).
Based on the JWT token's payload values, the service generates a response (containing proto-generated case class).
If the token's payload contains a field with null, this null goes into the response message's string field.

I don't think that checking every field for nullity prior to constructing the mesaage (proto-generated case class instance) is the best option here...

**Comment by thesamet** [comment]
> I don't think that checking every field for nullity prior to constructing the mesaage (proto-generated case class instance) is the best option here...
Can you explain what you mean? In case you are looking for a way to distinguish between a "null" string and any other string in proto3, check out [`StringValue`](https://github.com/google/protobuf/blob/6b5fb0727a6a775be6ec306e2c69e9e4dc10bd68/src/google/protobuf/wrappers.proto#L107). It would generate an `Option[String]` for you which is a more idiomatic way in Scala to deal with missing values.

**Comment by DimaLiah** [comment]
My end goal is not to receive NPEs upon 
`ACaseClassGeneratedFromProto(aStringField = null).toString()`
because it violates what one would expect from invoking the `toString` method on a case class.

Taking into account what you've said _(The semantics of the Protobuf Java API is that nulls are never allowed into any field)_ , I suggest to modify the generation of case class's`apply` method, so that it'll protect from inserting nulls into string fields.

**Comment by DimaLiah** [comment]
Hi, sorry for asking, but is this issue being progressed somehow?..

**Comment by thesamet** [comment]
Hi @DimaLiah , I have been considering this issue and decided to leave things as they are now. There are several reasons:
1. In idiomatic Scala code there are no nulls (or at least we would like to pretend they don't exist), and thus it is considered unusual to do null checking in Scala, except in places where you actually have a reason to expect nulls to show up, for example when you receive a value from a Java function or non-idiomatic Scala code. ScalaPB has no reason to assume you'd be passing nulls to it. This is a different mindset than Java, where it is common to do null-checking at the top of public methods.
2. It is impossible to do a comprehensive null check for all field at construction time: some custom types may be aliased to scalar types (ints) where nulls are not allowed, and that would lead to compilation errors.
3. There is a very tiny performance cost for the null checks, but it may add up in certain use cases and it is just unnecessary for most users.
4. It is possible that this check would unnecessarily break existing code for users of ScalaPB if they happen to carry nulls in their case classes in a way that doesn't trigger an NPE.

My suggestion would be to check for null at the location where you receive them and convert them to `Option[T]` before passing them to Scala code.
