### ISSUE TITLE
Provide Gradle-plugin

### ISSUE THREAD

**Issue by lostiniceland** [scalapb/ScalaPB#462]
It would be great if there could be a gradle-scalapb-plugin in addition to the sbt-plugin.

Gradle and CLI ScalaPB are mostly working (except [this one](https://github.com/scalapb/ScalaPB/issues/461)) but having an integrated plugin would make things much easier.

@thesamet If you dont like Groovy or dont have the time, I would like to use this issue to discuss the usage of ScalaPB so I might be able to provide a plugin myself. If possible we could host it here once done.

**Comment by thesamet** [comment]
I haven't tried it, but it looks like this plugin is able to extract jars: https://github.com/CharlesAHunt/scalapb-gradle-plugin - can you give it a try?

**Comment by lostiniceland** [comment]
This plugin works, thanks.
