### ISSUE TITLE
allow building on JDK 9 (EncodingSpec needs java.xml.bind)

### ISSUE THREAD

**Issue by SethTisue** [scalapb/ScalaPB#466]
as seen at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk9-integrate-community-build/206/consoleFull there is a test failure when building on JDK 9:

```
[scalapb] [info] EncodingSpec:
[scalapb] [info] - fromBase64 is the inverse of toBase64
[scalapb] [info] - fromBase64 is compatible with javax.printBase64 *** FAILED ***
[scalapb] [info]   NoClassDefFoundError was thrown during property evaluation.
[scalapb] [info]     Message: javax/xml/bind/DatatypeConverter
[scalapb] [info]     Occurred when passed generated values (
[scalapb] [info]       arg0 = Array()
[scalapb] [info]     )
[scalapb] [info] - toBase64 is compatible with javax.parseBase64 *** FAILED ***
[scalapb] [info]   NoClassDefFoundError was thrown during property evaluation.
[scalapb] [info]     Message: javax/xml/bind/DatatypeConverter
[scalapb] [info]     Occurred when passed generated values (
[scalapb] [info]       arg0 = Array()
[scalapb] [info]     )
[scalapb] + com.trueaccord.scalapb.textformat.BasicsSpec.bytes 92ms  
```

info on how to resolve this is here: https://stackoverflow.com/questions/43574426/

this isn't critical to resolve, but we would like to get as much of the Scala 2.12 community build running on JDK 9 as possible, to help catch JDK 9/10 specific bugs in Scala.

**Comment by thesamet** [comment]
Fortunately, this can be fixed by having just the tests depend on commonds-codec. The run configuration was already free of `javax.xml.bind`.
