### ISSUE TITLE
Object is not a member of package <root> when no package is provided and flatPackage is set to true

### ISSUE THREAD

**Issue by herzrasen** [scalapb/ScalaPB#472]
Hi, 

when trying to compile 
`syntax = "proto3";

message A {
    int64 id = 1;
    string a = 2;

    message B {
        int64 id = 1;
        string b = 2;
    }

    repeated B bs = 10;
}`

with `flatPackage=true`, I get an error saying that object A is not a member of package <root>.

However the error does not occur, when providing the package in the .proto file or setting `flatPackage=false`.

**Comment by thesamet** [comment]
Hi @herzrasen , I added a check that would give a better error message for this scenario. In Scala, symbols defined when the package name is not defined can't be absolutely referenced using `_root_`, and can't be used in modules that have a package name defined, so we better not let them pass through.

See https://scala-lang.org/files/archive/spec/2.12/09-top-level-definitions.html:

> Top-level definitions outside a packaging are assumed to be injected into a special empty package. That package cannot be named and therefore cannot be imported. However, members of the empty package are visible to each other without qualification.

**Comment by herzrasen** [comment]
Ah sorry, I wasn't aware of that. An improved error message is fine.

**Comment by thesamet** [comment]
I considered this once more and recalled that the Java implementation does allow for empty package names. I actually filed a [similar issue](https://github.com/google/protobuf/issues/3114) myself on this last year. So despite the aforementioned visibility issues of package-less symbols, this could still be useful in some scenarios, so I committed a change to make it work.
