### ISSUE TITLE
cant load spark model while use grpc depenencies for scalaPB

### ISSUE THREAD

**Issue by alibaltschun** [scalapb/ScalaPB#476]
i have a problem about load spark model.
that totally works fine while not using gRPC dependencies.

this is my main.scala

    import org.apache.spark.ml.tuning.CrossValidatorModel
    import org.apache.spark.sql.SparkSession
    import org.apache.spark.sql.Row
    
        object lr_model {
    	val spark = SparkSession.builder().appName("ml model").master("local[*]").getOrCreate();
    
    	val model = CrossValidatorModel.load("C:/Users/.....................")
    	def testing(subject:String):String = {
    		val datatest = spark.createDataFrame(Seq(("CATEGORY_SOCIAL",subject))).toDF("labelss","subjects")
    		var result = model.transform(datatest).head().getDouble(6)
    		return result 
    	}
    
        def main(args: Array[String]): Unit = {
            println(testing("aaaa"))    
            spark.stop()
        }
    }

and this is my build.sbt

    scalaVersion := "2.11.7"
    
    PB.targets in Compile := Seq(
      scalapb.gen() -> (sourceManaged in Compile).value
    )
    
    val scalapbVersion =
    	scalapb.compiler.Version.scalapbVersion
    val grpcJavaVersion =
    	scalapb.compiler.Version.grpcJavaVersion
    
    libraryDependencies ++= Seq(
    	// spark
    	"org.apache.spark" %% "spark-core" % "2.3.1" ,
    	"org.apache.spark" %% "spark-sql" % "2.3.1" ,
    	"org.apache.spark" %% "spark-mllib" % "2.3.1" ,
    
    	// protobuf
    	"com.thesamet.scalapb" %% "scalapb-runtime" % scalapbVersion % "protobuf"
    	
    	//for grpc
    	//"io.grpc" % "grpc-netty" % grpcJavaVersion
    	//"com.thesamet.scalapb" %% "scalapb-runtime-grpc" % scalapbVersion
    )

but while i used gprc dependencies that give me an error like this.

    18/07/18 12:59:08 INFO SparkContext: Created broadcast 0 from textFile at ReadWrite.scala:387
    [error] (run-main-0) java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.mapred.FileInputFormat
    java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.mapred.FileInputFormat
            at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:312)
            at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:200)
            at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253)
            at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251)
            at scala.Option.getOrElse(Option.scala:121)
            at org.apache.spark.rdd.RDD.partitions(RDD.scala:251)
            at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)

its bug from grpc or my code was wrong?
thanks

note : scala 2.11.7 , spark 3.2.1 ,

**Comment by xuwei-k** [comment]
https://gist.github.com/xuwei-k/464cb30484300a882967946c316ed0d1
spark 2.3.1 depends on protobuf-java 2.5.0

**Comment by thesamet** [comment]
Hi @alibaltschun , as indicated above Spark 2.3.1 depends on an old version of protobuf (2.5.x) that is not binary-compatible with the version ScalaPB depends use (3.6.x). To get around this problem, you would need to deploy your program to spark as a single fat jar, and shade google protobuf so it doesn't clash with the version that is shipped with spark. There are more details on how to do this here: https://scalapb.github.io/sparksql.html .  Hope this helps!

**Comment by alibaltschun** [comment]
i was cloned your [repo](https://github.com/thesamet/sparksql-scalapb-test). 
edit libraryDependencies with

```
libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % "2.3.1" ,
  "org.apache.spark" %% "spark-sql" % "2.3.1" ,
  "org.apache.spark" %% "spark-mllib" % "2.3.1" ,
  "com.thesamet.scalapb" %% "sparksql-scalapb" % "0.7.0",

  // protobuf
  "com.thesamet.scalapb" %% "scalapb-runtime" % scalapbVersion % "protobuf",
	
  //for grpc
  "io.grpc" % "grpc-netty" % grpcJavaVersion ,//intransitive(),
   "com.thesamet.scalapb" %% "scalapb-runtime-grpc" % scalapbVersion //intransitive()
)

assemblyShadeRules in assembly := Seq(
  ShadeRule.rename("com.google.protobuf.**" -> "shadeproto.@1").inAll
)
```

change the scala.code to my code

"sbt run" and still give me the same error
```
(grpc-default-executor-0) java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.mapred.FileInputFormat
java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.mapred.FileInputFormat
```

thanks

**Comment by thesamet** [comment]
You can run the assembled jar by submitting to a cluster (which can just be local). You'll need to mark spark as a `provided` dependency, and then submit it to a cluster using spark-submit, see instructions in the README: https://github.com/thesamet/sparksql-scalapb-test

**Comment by alibaltschun** [comment]
i was tried**provided** for all spark dependencies -> assembly -> spark submit to local but that give me error like this. [my code](https://github.com/alibaltschun/spark-scalapb)
`
Exception in thread "main" io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional server found. Try adding a dependency on the grpc-netty artifact`

thanks for helping

**Comment by thesamet** [comment]
The exception suggests adding a dependency on grpc-netty, have you tried that?

**Comment by thesamet** [comment]
Looks like we're getting close. I found this thread: https://groups.google.com/forum/#!topic/scalapb/KG3ZgM7ciE4

Try in your `server.scala` to replace ServerBuilder with `io.grpc.netty.NettyServerBuilder`.

**Comment by alibaltschun** [comment]
thanks that's work for me
change serverbuilder to NettyServerBuilder in server
and change manageChangeManager to NettyChannelBuilder in client

maybe better if quote that on scalapb documentation.
thanks thesamet

**Comment by thesamet** [comment]
@alibaltschun - it looks like your earlier message confirming that things are working has been removed? Is this issue resolved?

**Comment by alibaltschun** [comment]
sorry about that. coz last error has fixed but I have another error.
i was changing 

> io.grpc.serverbuilder

 to 

> io.grpc.netty.NettyServerBuilder

 and the server has no error. but in client still have an error while i change 

> io.grpc.manageChanelBuilder

 to 

> io.grpc.netty.NettyChannelBuilder

 and give me error 

`Exception in thread "main" java.lang.IllegalStateException: No NameResolverProviders found via ServiceLoader, including for DNS. This is probably due to a broken build. If using ProGuard, check your configuration`

maybe this error not main of this thread. thanks for helping. if you can help me fix this client so thanks. but if not you cant close this thread. thanks thesamet.

**Comment by thesamet** [comment]
Looks like this issue is a combination of grpc-jave being used with sbt-assembly.  There is a workaround described here: https://github.com/grpc/grpc-java/issues/2149
