### ISSUE TITLE
Import management

### ISSUE THREAD

**Issue by teivah** [scalapb/ScalaPB#477]
Hello,

I have two simples .proto files A.proto and B.proto with B importing A but I'm facing errors during sbt compile:
```Import "A.proto" was not found or had errors.```

Are imports managed?

**Comment by thesamet** [comment]
Imports are working. Maybe `A.proto` has errors?

**Comment by thesamet** [comment]
We have plenty of tests that use imports so it sounds like a usage error.  I'm closing this issue for now. If you have any additional information to add, feel free to comment and I will re-open.
