### ISSUE TITLE
Java generation

### ISSUE THREAD

**Issue by teivah** [scalapb/ScalaPB#478]
Hey,

I can't understand why this [very simple project](https://github.com/teivah/test-protobuf/) generates something in Java instead of Scala. I followed the basic procedure. I can't understand.

Thanks

**Comment by thesamet** [comment]
I am not able to reproduce the issue you are seeing. This project does generate Scala, there's no Java generated. Which Java files get generated? Maybe they are left-over from a previous configuration?

**Comment by thesamet** [comment]
I wasn't able to reproduce this issue and haven't heard in a while, so I'm closing this issue. If there is additional information to add, feel free to comment and I will re-open.
