### ISSUE TITLE
ScalaPB Logo Proposal

### ISSUE THREAD

**Issue by Wei-1** [scalapb/ScalaPB#481]
![Imgur](https://i.imgur.com/aOxjoPf.png)
I notice that there is no logo for ScalaPB.
So I draw this with Paint.

**Comment by Wei-1** [comment]
![svg](https://svgshare.com/i/7ny.svg)
Or with this svg approach?

**Comment by thesamet** [comment]
Hi @Wei-1, thanks for proposing this logo. I feel that the proposed logo above is too similar to Scala's logo which it is building upon, to the point that it can cause confusion or suggest affiliation. I am definitely interested in finding a logo for this project (I think it's time!) so I'll be happy consider other proposals - feel free to post them as different issues. Thanks again for making this proposal and sharing it!
