### ISSUE TITLE
ScalaPB Logo Proposal

### ISSUE THREAD

**Issue by Wei-1** [scalapb/ScalaPB#483]
![scalapb](https://svgshare.com/i/7pF.svg)

Tried another SVG approach.

**Comment by thesamet** [comment]
@Wei-1  I prefer to have some other concept, unrelated to the Scala logo. How about some abstract logo, with the word ScalaPB written next to it? Ideally the logo would be hinting at message passing, or message sending and receiving. Should convey being lightweight, fast and fun to use.

**Comment by Wei-1** [comment]
![scalapb](https://svgshare.com/i/7pJ.svg)
I thought the message passed is purely defined in the protobuf file?

**Comment by thesamet** [comment]
Nice! I like this concept! How about we make this a little easier to read? It looks like the left half is a `P` the right half is a `B`. I tried to take it further with this:

![image](https://user-images.githubusercontent.com/307373/44302886-e8fef180-a2e6-11e8-9c6c-7bfb895e2a90.png)

What I don't like about my proposal is that it looks imbalanced before the bottom left side. But if I further extend the lower side of the `P`, it starts looking like an `e`... Thoughts?

For your question: protocol buffer messages are defined in the protobuf, and ScalaPB generates Scala code for them so they can be used in Scala.

**Comment by Wei-1** [comment]
![scalapb](https://svgshare.com/i/7uG.svg)
How about this? @thesamet 
The svg is about 1KB

**Comment by thesamet** [comment]
Thanks @Wei-1 for coming up with these beautiful logo proposals. We recently redid ScalaPB's website and ended up with something else.
