### ISSUE TITLE
Proposal: Allow to add annotations (and extends, etc) to sealed traits created by `oneof`s

### ISSUE THREAD

**Issue by pjrt** [scalapb/ScalaPB#484]
There is currently no way to do this.

**Comment by pjrt** [comment]
I am willing to give this a go if someone can point me in the right direction.

**Comment by thesamet** [comment]
- add a new option to the oneof: https://github.com/scalapb/ScalaPB/blob/82356cf1dfa134b6ea62f87edf6b66597c16e69e/protobuf/scalapb/scalapb.proto#L155  (should be a `repeated string annotations`)

I think the option should be applied to both sealed and regular oneofs.

- run `make_plugin_protos.sh` this would generate Java and Scala code for `scalapb.proto`, you need to do this each time you edit scalapb.proto.

- Follow [this pattern](https://github.com/scalapb/ScalaPB/blob/82356cf1dfa134b6ea62f87edf6b66597c16e69e/compiler-plugin/src/main/scala/scalapb/compiler/DescriptorImplicits.scala#L424) to add a new method `annotationsList` to `OneofDescriptorPimp`

- Update ProtobufGenerator.scala to use the new annotations (for both sealed and unsealed oneofs)

- In e2e add a test for this annotations; see how it is tested here: https://github.com/scalapb/ScalaPB/blob/82356cf1dfa134b6ea62f87edf6b66597c16e69e/e2e/src/test/scala/CustomOptionsSpec.scala#L247-L249

Feel free to ask here or on gitter if you have any questions.

**Comment by thesamet** [comment]
It is now possible to add `extends` to the base trait of oneofs. This tickets calls for annotations and other features - and it should be fairly straightforward to add at this point. Since this is an old ticket, I will be closing it now. If the additional functionality is still relevant please file a new ticket.
