### ISSUE TITLE
Support Scala.js 1.0.0-M3

### ISSUE THREAD

**Issue by thesamet** [scalapb/ScalaPB#486]

**Comment by xuwei-k** [comment]
latest scala-js 1.x milestone is 1.0.0-M5
https://www.scala-js.org/news/2018/08/13/announcing-scalajs-1.0.0-M5/

**Comment by thesamet** [comment]
@xuwei-k waiting for lihaoyi/utest#174

**Comment by thesamet** [comment]
@xuwei-k looks like fastparse is not getting updated so frequently. We might have to move to another parser if we want to stay on the latest versions of things.

**Comment by ngbinh** [comment]
https://github.com/sirthias/parboiled2 is more performant

**Comment by thesamet** [comment]
@ngbinh I actually have a branch from 2015 where I implemented TextFormatting with parboiled: https://github.com/scalapb/ScalaPB/blob/parsing-wip/scalapb-runtime/src/main/scala/com/trueaccord/scalapb/TextFormat.scala#L9 looks like I ran into some issues and switched to fastparse. This branch never got merged.

**Comment by thesamet** [comment]
ScalaJS 1.0.0 supported added in 0.10.0-M5
