### ISSUE TITLE
Scala tutorial

### ISSUE THREAD

**Issue by shankarshastri** [scalapb/ScalaPB#496]
Can we also have scala tutorial like
https://developers.google.com/protocol-buffers/docs/javatutorial

**Comment by thesamet** [comment]
That's a great idea. Are you by any chance able to help with this?

**Comment by shankarshastri** [comment]
Sure, I'm actually figuring out where the repo is actually located for it.

**Comment by thesamet** [comment]
https://github.com/scalapb/ScalaPB/tree/master/docs/src/main/tut

**Comment by shankarshastri** [comment]
Not the tutorial actually, I meant the Google GitHub repo for updating the tutorial

**Comment by thesamet** [comment]
ScalaPB is not affiliated with Google, it's an independent project. The tutorial we can put together will be published on https://scalapb.github.io/, not on https://developers.google.com/protocol-buffers

**Comment by shankarshastri** [comment]
Oh ok. Sure. I will take a look at it.

**Comment by thesamet** [comment]
We've recently revamped the website and added this tutorial: https://scalapb.github.io/docs/getting-started
