### ISSUE TITLE
How to make intelli generate the code?

### ISSUE THREAD

**Issue by avnerbarr** [scalapb/ScalaPB#509]
I've configured everything per the instructions and my sbt file looks like this:

```
// https://scalapb.github.io/
PB.targets in Compile := Seq(
  scalapb.gen() -> (sourceManaged in Compile).value
)

libraryDependencies += "com.thesamet.scalapb" %% "scalapb-runtime" % scalapb.compiler.Version.scalapbVersion % "protobuf"
lazy val grpcserver: Project = project.in(file("grpcserver")).dependsOn(driver).settings(
  commonSettings,
  name := "grpcserver",
  assemblyJarName in assembly := "grpc-server.jar",
  test in assembly := {},
  libraryDependencies ++= Seq(
    "io.grpc" % "grpc-netty" % scalapb.compiler.Version.grpcJavaVersion,
    "com.thesamet.scalapb" %% "scalapb-runtime-grpc" % scalapb.compiler.Version.scalapbVersion
  )
)
```

But the code isn't created when building in intellij - I was able to generate the code when going to SBT command line.

**Comment by thesamet** [comment]
Hi @avnerbarr , thanks for reporting. I have been observing the same behavior and I'm compiling in SBT when I need the protos to be regenerated. It seems that this is an IntelliJ limitation - it doesn't execute SBT tasks, only compile sources: https://intellij-support.jetbrains.com/hc/en-us/community/posts/206825945-sbt-tasks-as-part-of-the-normal-build . It would recommend to file a bug with IntelliJ.
