### ISSUE TITLE
Upgrade to fastparse v2

### ISSUE THREAD

**Issue by olafurpg** [scalapb/ScalaPB#510]
Fastparse v2 came out recently (http://www.lihaoyi.com/post/Fastparse2EvenFasterScalaParserCombinators.html) and it has binary breaking changes with v1.0.0. It doesn't look like fastparse v2 will use a custom package name like `fastparse.v2` (https://gitter.im/lihaoyi/fastparse?at=5bd18969ae7be94016b25649) so all libraries using fastparse must either upgrade to v2 or shade the fastparse dependency. 

Would it be possible for ScalaPB to shade its fastparse dependency? This would allow downstream users of ScalaPB to choose whether they want fastparse v1 or v2 on their classpath.

**Comment by thesamet** [comment]
If I shade the default artifact, then I'll be forcing users to have our private shaded copy of fastparse in the classpath (+potentially duplicate code for Scala.js users). If I publish this under another artifact name (say scalapb-runtime-shaded), then dependencies such as scalapb-json4s and scalapb-runtime-grpc will transitively bring in the original scalapb-runtime which depends on fastparse 1 which would cause a mess.

Maybe we should isolate the parsing out to an external library, and provide two implementations one for fastparse 1 and one for fastparse 2. Regardless, I think we'll have fastparse 2 as the default in ScalaPB 0.9.0

**Comment by olafurpg** [comment]
Fair enough, I renamed the ticket to "upgrade to fastparse v2". No rush on my side, we don't use the text format parser in Scalameta and we have opted to shade fastparse v1.

**Comment by raboof** [comment]
Looks like this depends on https://github.com/lihaoyi/fastparse/issues/215 (which depends on the [Scala Native 0.4.0 release](https://github.com/scala-native/scala-native/milestone/19))

**Comment by raboof** [comment]
Fastparse 2 is not available for scala 2.10, so this also depends on #542

**Comment by dgrnbrg** [comment]
I would like to have my application use ScalaPB & Ammonite. Unfortunately, Ammonite seems to depend on Fastparse 2, which is blocking this inclusion.

So, +1 for this issue.

**Comment by SethTisue** [comment]
looks like this should be closed now?

**Comment by raboof** [comment]
Yes - 0.9.0-M1 should contain this change

**Comment by thesamet** [comment]
Yes, this went in via https://github.com/scalapb/ScalaPB/commit/b467afaf4b5151a36d21919cd7e5c7fe5746ecfa

**Comment by thesamet** [comment]
Thanks @raboof for this PR!
