### ISSUE TITLE
client streaming generated code confuses

### ISSUE THREAD

**Issue by momania** [scalapb/ScalaPB#511]
Taking the following rpc call: ```rpc LotsOfGreetings(stream HelloRequest) returns (HelloReply) {}```, the generated client and server code use a `StreamObserver[HelloReply]`.

Why is this not a `Promise[HelloReply]`? That would make it much clearer from the code that it will only involve a single answer.

**Comment by thesamet** [comment]
It's a good question. We were following the Java signatures: https://grpc.io/docs/tutorials/basic/java.html#client-side-streaming-rpc  but that doesn't mean we can't improve. One of the design considerations is that the client and server implement the same interface. If `lotsOfGreetings` would take a `Promise[HelloReply]`. Then the client would have to invoke `promise.future` to get access to the result. I'm open to suggestions. Also note that there's a more functional implementation based on FS2 here: https://github.com/fiadliel/fs2-grpc

**Comment by momania** [comment]
Agree that the client and server api should be the same, but I think it would be an improvement.
The interface would be: 
```scala
def lotsOfGreetings(responsePromise: Promise[HelloReply]): StreamObserver[HelloRequest]
```

Internally a `Promise` is easily wrapped in a `StreamObserver`, i.e.:

```scala
  class PromisingStreamObserver[V](promise: Promise[V]) extends StreamObserver[V] {
    var ref: Option[V] = None

    override def onError(t: Throwable): Unit = promise.failure(t)
    override def onCompleted(): Unit = {
      ref.fold(promise.failure(new Exception("Completed before onNext")))(promise.success)
    }
    override def onNext(value: V): Unit = ref = Some(value)
  }
```
In the end the client code will be simplified to:
```scala
val promise = Promise[HelloReply]()
val requestObserver = stub.lotsOfGreetings(promise)

// send lots of requests...and then call onCompleted
requestObserver.onCompleted()

// deal with the future result
val future = promise.future
```

**Comment by thesamet** [comment]
This makes sense and I tend to agree that it would be less confusing using a Promise. Currently, the code follows the Java API pretty closely.  Implementing this change would deviate from the Java API for just this one case, and would also break the source of existing projects.  So I'd rather not introduce this change at this point. In the future, I'd like to have a new grpc code generator that is more functional and also addresses this issue.
