### ISSUE TITLE
How to define a trait type in a case class?

### ISSUE THREAD

**Issue by Birdflying1005** [scalapb/ScalaPB#514]
```
message Event {
  string eventId = 1;
  Command command = 2;
}
```

Command is a empty trait

```
trait Command
```

The command has been imported in option. 

How to define a trait type in a case class Event?

**Comment by thesamet** [comment]
Not sure what you mean by "The command has been imported in option".

If `Command` is a trait already defined in existing Scala code, you can look into [custom types](https://scalapb.github.io/customizations.html#custom-types). If you want ScalaPB to generate a sealed trait, take a look at [sealed oneofs](https://scalapb.github.io/sealed-oneofs.html).

Also, in the future, please use gitter, the mailing list or StackOverflow for usage questions. We use Github Issues for tracking bugs or feature requests.

**Comment by Birdflying1005** [comment]
@thesamet 
Thanks for your response. My .proto file as below:

```
syntax = "proto3";

import "scalapb/scalapb.proto";
import "google/protobuf/wrappers.proto";
import "model.proto";

option (scalapb.options) = {
  single_file: true
  package_name: "model"
  flat_package: true
  no_primitive_wrappers: false
  preamble: "trait BaseMessage"
};

message CommandEnvelope {
  string eventId = 1;
  BaseMessage command = 2;
}

```

The error is  "BaseMessage" is not defined.

**Comment by Birdflying1005** [comment]
let me try the oneof. thx

**Comment by thesamet** [comment]
You are getting this error from `protoc`. The types you use for fields in proto files must be valid protocol buffer types, protoc doesn't know about `BaseMessage`.

**Comment by thesamet** [comment]
Hope this helps. If you have additional questions don't hesitate to reach out over gitter or Stackoverflow.
