### ISSUE TITLE
feature request: optionally omit lenses in generated code

### ISSUE THREAD

**Issue by dsilvasc** [scalapb/ScalaPB#515]
I have a large proto repository that takes about 28 minutes to compile with Scala 2.12.7 and ScalaPB 0.8.2.  Compiling the generated Java code takes 2 minutes.

If I strip lens-related parts of the ScalaPB-generated code with the following script though, the Scala compile time goes down to 7 minutes:

```bash
find generated-src/scala -type f | while read f; do
  # remove everything between "implicit class ...Lens[" and the closing bracket
  # https://stackoverflow.com/questions/37680636/sed-multiline-delete-with-pattern
  sed -i '/implicit class /{:a;N;/}/!ba};/Lens[[]/d' $f
  # remove lens mixin
  sed -i -e 's/with scalapb.lenses.Updatable[^ ]* //' $f
done
```

Would it be possible to make lens generation optional?

**Comment by dsilvasc** [comment]
thank you :)

**Comment by thesamet** [comment]
You're welcome. I'll cut a release with this change in the next few days.

**Comment by dsilvasc** [comment]
Is this the 0.8.2 release or 0.8.3?
