### ISSUE TITLE
Add support to `Effect` for gRPC services

### ISSUE THREAD

**Issue by hilios** [scalapb/ScalaPB#523]
The goal of this issue is to propose a higher-kinded type – `F[_]` – to the generated `service` trait.

### The problem

Given the example provided on the docs, for a proto definition:

```protobuf
service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}
```

we have the compiled trait:

```scala
trait Greeter extends AbstractService {
   def sayHello(request: conspiracy.HelloRequest): Future[conspiracy.HelloReply]
}
```

For the folks using **Scalaz** or **cats-effect**, this is cumbersome since we have to convert our `IO` monad into a `Future` all the time.

### The solution

Introduce a type class to provide implicit conversions to the service effect and make the service trait a higher-kinded type that specifies the effect. Hence, the trait would have to be compiled to:

```scala
trait Greeter[F[_]] extends AbstractService[F] {
   def sayHello(request: conspiracy.HelloRequest): F[conspiracy.HelloReply]
}
```

Whereas we should provide a `ServiceEffect[F]` type class to convert the generic type `F` to the base effect:

```scala
trait ServiceEffect[F[_]] {
   def run[A](fa: F[A]): Future[A]
}

object ServiceEffect {
   // Transparent conversion to Future
   implicit def futureServiceEffect(implicit ec: ExecutionContext): ServiceEffect[Future] = new ServiceEffect[Future] {
    def run[A](fa: Future[A]): Future[A] = fa
  }
}
```

Once we have this structure in place it would be trivial to provide support to any effect library such as: `cats.effect.IO`, `scalaz.concurrent.Task `, `com.twitter.util.Future` and so on, provided by its own modules.

```scala
import cats.effect.IO

implicit val ioServiceEffect: ServiceEffect[IO] = new ServiceEffect[IO] {
  def run[A](ioa: IO[A]): Future[A] = ioa.unsafeToFuture()
}
```

Naturally, this would also require changes on the `.bindServer` method, but the good part is that we could drop the `ExecutionContext` requirement from it since is implicit summoned by the `ServiceEffect[Future]`.

```scala
object GreeterGrpc {
   def bindService[F[_]](serviceImpl: Greeter)(implicit F: ServiceEffect[F]): ServerServiceDefinition =
    ServerServiceDefinition.builder(SERVICE)
      .addMethod(
        METHOD_SAY_HELLO,
        ServerCalls.asyncUnaryCall(new ServerCalls.UnaryMethod[HelloRequest, HelloReply] {
          override def invoke(request: conspiracy.HelloRequest, observer: StreamObserver[conspiracy.HelloReply]): Unit =
            F.run(serviceImpl.sayHello(request)).onComplete(scalapb.grpc.Grpc.completeObserver(observer))
        }))
      .build()
}
```

Moreover, another idea is the type class to convert to any `ServerCallHandler` (uniary, straming or bidirectional) directly.

Finally, to start the service one will need to summon the desired effect and implicit conversion.

```scala
implicit val ioEffect: ServiceEffect[IO] = ???

GreeterGrpc.bindService[IO](Greeter())
```

I am willing to develop such a feature, but I wanted first to discuss the implementation with you guys and see your thoughts about it and, of course, some guidance on where I can start. 

Cheers, and thank you for the great plugin.

**Comment by thesamet** [comment]
Hey @hilios , it would be great to have this added. Can you elaborate on how you intend to handle streaming calls? Also, I wonder if you are familiar with https://github.com/fiadliel/fs2-grpc which is built on top of ScalaPB?

The easiest way to get started would be to make a copy of GrpcServicePrinter, and add some new flag to enable it so one could pick which flavor of Grpc they want. The easiest way to test is by adding a test case to the e2e directory and run `e2e.sh` to test the changes.

**Comment by hilios** [comment]
Sorry for getting too long to reply back @thesamet. 

For streaming, I see no difference from the proposal since we can hook up the side-effect (Future or IO) in any step of the operation, although I need to get a better grasp on the internals.

On the fs2 lib I am no acquainted with it, but giving a quick look I think both could coexist seamlessly with a problem w/ this approach for the same reasons described above.

During the weekend I will try to get my hands dirty and see what I can get.

**Comment by thesamet** [comment]
@hilios - checking in on this. Specifically, I'd like to know if the approach you are suggesting is different than what fs2-grpc already provides.

**Comment by hilios** [comment]
@thesamet , I just took `fs2-grpc` for a spin. 

The gotcha is the plugin lifts an `io.grpc` client/server instances into a `fs2.Stream` since they are mainly an I/O operation, thus leaving the actual service implementation still in terms of a `Future`.

For example, given the `Greeter` service from before:

```scala
// The greeter implementation still uses the Future
class  GreeterImpl extends GreeterGrpc.Greeter {
   def sayHello(req: HelloRequest): Future[HelloReply] = ???
}

val greeter =  new GreeterImpl()

// Lifiting a server
import org.lyranthe.fs2_grpc.java_runtime.implicits._

val service = GreeterGrpc.bindService(greeter, ec)

// Lift the io.grpc.Server into a lazy Stream[IO, Server]
val stream: Stream[F, Server] = ServerBuilder.forPort(9999)
          .addService(service)
          .stream[IO]

// Start server
stream..evalMap(server => IO(server.start()))
```

Even thought the server is a proper effectfull type – the `Stream` – there is no way to do the same on the implementation of the service.

**Comment by thesamet** [comment]
@hilios not sure I understand. Looking at [this fs2-grpc example](https://github.com/fiadliel/fs2-grpc-example/blob/77466737047087e8fe07e4136a1012881c5b92e3/server/src/main/scala/Main.scala#L10) the service is implemented in terms of an `IO` not `Future`s.

**Comment by pshemass** [comment]
@thesamet I think that @hilios is trying to say that there is still conversion required between Future and IO which could be avoided by abstracting Future to F[_]

**Comment by thesamet** [comment]
@pshemass , @hilios - But fs2-grpc does let you implement your service in terms of `F[_]` and `Stream[F, _]`, not int terms of Futures. The following is the trait that you need to implement when you write a service:

```
trait GreeterFs2Grpc[F[_]] {
  def sayHello(request: HelloRequest, clientHeaders: Metadata): F[HelloReply]
  def sayHelloStream(request: fs2.Stream[F, HelloRequest], clientHeaders: Metadata): fs2.Stream[F, HelloReply]
}
```

I am not seeing what is meant by "leaving the actual service implementation still in terms of a `Future`" and "conversion required between Future and IO" - can you point at the are the `Future`s you are referring to? My confusion is that I'm not seeing them in fs2-grpc.

**Comment by thesamet** [comment]
I'm closing this ticket since it is unclear what is being requested that is not available from `fs2-grpc`. Happy to re-open this ticket once this is clarified.

**Comment by hilios** [comment]
@thesamet sorry for keeping this opens for too long. Indeed `fs2-grpc` implements the protobuf protocol in terms of `F`. I had a hard time using it because of poor documentation, but in the end it was working.

To be clear I still think pushing `scalapb` to a tagless final approach is a good idea because it gives more flexibility and make it easier to sync with the lib latest versions (i.e. `fs2-grpc` still haven't released a stable version of the latest release). Moreover, it would be great to have a single compiler and be able to choose your version. Finally, in the end `f2s-grpc` it might be valuable to lift `grpc` into an `F` or a `Stream`, but the compiler part I fell should live in this project.

Currently I am being able to give full attention to this matter in my current job – even though I am using  `f2s-grpc` for now – so more ideas might rose from that, such as, I am writing a component to convert [Protobuf to Avro](https://github.com/apache/avro/tree/master/lang/java/protobuf) but let's see how things evolve from here.
