### ISSUE TITLE
using netty native transport with domain sockets

### ISSUE THREAD

**Issue by avnerbarr** [scalapb/ScalaPB#531]
currently I'm using the vanilla comman to cretae the GRPC server:

ServerBuilder.forPort(port).addService(GreeterGrpc.bindService(new GrpcServer, ec)).build().start()

When the service is for "local" traffic only , to use domain sockets instead? Can't seem to figure out how to configure it correctly.

Thanks!

**Comment by thesamet** [comment]
This feature is missing in grpc: https://github.com/grpc/grpc/issues/4677 closing as duplicate.
