### ISSUE TITLE
Small Lens enhancement - optional set

### ISSUE THREAD

**Issue by codingismy11to7** [scalapb/ScalaPB#539]
Wondering if this (or something similar) could be added to the `Lens` class:

```scala
  implicit class RichLens[Container, A](val lens: Lens[Container, A]) extends AnyVal {
    def :=?(aOpt: Option[A]): Mutation[Container] = c => aOpt.fold(c)(lens.set(_)(c))
  }
```

Didn't want to make a PR since i'm not sure if i'm missing some functionality that exists already, and didn't know if that symbolic operator is too weird or not. Happy to make a PR if it's useful, though.

**Comment by thesamet** [comment]
Sorry it took me long to respond. I want to limit the number of methods that have symbols in their names since IMO this hurts readability. I'll be happy to accept a PR where this method is named along the lines of `setOptional`
