### ISSUE TITLE
Drop support for sbt 0.13, scala 2.10

### ISSUE THREAD

**Issue by raboof** [scalapb/ScalaPB#542]
sbt 0.13 and scala 2.10 are EOL, and it is slowly getting harder to keep supporting them (for example, fastparse2 is not released for scala 2.10, #510).

What would be a good moment to stop supporting those in future scalapb releases?

**Comment by thesamet** [comment]
Only scalapb-runtime depends on fastparse, but not our compilerplugin. This means that we can drop Scala 2.10 support while keeping sbt 0.13 supported a little bit longer if necessary.

**Comment by thesamet** [comment]
We dropped support for Scala 2.10 for our runtime. The compiler plugin has no external dependencies can still be easily compiled with 2.10, so we can still support sbt 0.13.
