### ISSUE TITLE
Name collision for message type named "None"

### ISSUE THREAD

**Issue by akakitani** [scalapb/ScalaPB#543]
I've hit a weird corner case where one of the protos I'm using is defined like this:
```protobuf
message None { 

}
```
The generated class for this ends up colliding with `scala.None` for other generated classes in the same package e.g.
```scala
final case class OtherMessage(
    myField: scala.Option[some.other.Message] = None
) extends ....
```

Is it possible to use the fully qualified `scala.None` everywhere in the generated code instead?

**Comment by thesamet** [comment]
Yes, that would be a good solution. If you (or anyone else) would like to work on a PR, the steps would be:

1. Add a failing test case to e2e/src/main/protobuf/names.dot.proto
2. Make the necessary changes in `compiler-plugin`
3. Test by running `./e2e.sh`
