### ISSUE TITLE
Unknown type you may have to register it via FormatRegistry.registerCompanion

### ISSUE THREAD

**Issue by aalkilani** [scalapb/ScalaPB#553]
Implemented a TypeMapper from com.google.protobuf.any.Any to a custom case class. TypeMapper seems to perform as expected. This is used in a proto file like this:
```
repeated google.protobuf.Any myField = 1 [
        (scalapb.field).collection_type="collection.immutable.List",
        (scalapb.field).type = "MyCustomType"];
```
An attempt to convert to JSON:
```
import scalapb.json4s.JsonFormat
val myMessage = .... create instance of message containing myField above
println(JsonFormat.toJsonString(myMessage))
```

This results in an exception: 
```
Exception in thread "main" java.lang.IllegalStateException: Unknown type com.....$; you may have to register it via FormatRegistry.registerCompanion
```
The issue is that the codebase, scalapb 0.8.4 and scalapb-json4s from com.thesamet.scalapb version 0.7.2 don't have any means to do what the error message is asking for. There is no function called ```registerCompanion``` nor is there a way to add anything to the ```typeRegistry``` or ```printer``` in the current codebase. My best guess is that something must've gone wrong with some PRs and through the shuffling of projects from trueaccord to thesamet.

I see a PR that may be related but the code doesn't seem to reflect in a released code-base or has since changed: https://github.com/scalapb/scalapb-json4s/pull/13

Thanks

**Comment by thesamet** [comment]
The error message needs to be updated, but the functionality is there. Take a look at
https://github.com/scalapb/scalapb-json4s/blob/f934ad90e7e41e987616a8bbd198a45239a29ba8/src/test/scala/scalapb/json4s/AnyFormatSpec.scala and https://github.com/scalapb/scalapb-json4s/blob/f934ad90e7e41e987616a8bbd198a45239a29ba8/src/test/scala/scalapb/json4s/JavaAssertions.scala to see how companions are registered with `TypeRegistry` and then `Any`s with the respective message types can be parsed from JSON.

**Comment by aalkilani** [comment]
Thanks for the quick response.
So it sounds like in order for this to work, the custom type must be of type T <: GeneratedMessage with Message[T]. This may be an invalid assumption on my part. What I'm really trying to do with no success so far is what would translate in Scala as the following:
Simplifying this for purpose of the example:
- Create a base trait, let's say ```trait PlaysMusic{ def play() : String }```
- Implement 2 case classes that implement this trait. Let's say ```Guitar``` and ```Piano```
- Create a field of type List[PlaysMusic]

The closes I've been able to get this represented in proto with ScalaPB is as follows:
```
option (scalapb.options) = {
...
  flat_package: true
  single_file: true
  preamble: [
    "sealed trait PlaysMusic {",
    "    def play(): String",
    "}"
  ]
};

message Guitar {
    option (scalapb.message).extends = "PlaysMusic";
    option (scalapb.message).extends = "GuitarImplementation";
 ....
}

message Piano {
    option (scalapb.message).extends = "PlaysMusic";
    option (scalapb.message).extends = "PianoImplementation";
 ....
}
```

Then I want to use those 2 in a list, for example
```
message PolicySettings {
    repeated google.protobuf.Any phaseInPolicy = 1 [
        (scalapb.field).collection_type="collection.immutable.List",
        (scalapb.field).type = "PlaysMusic"];
}
```

I then implement an implicit ```TypeMapper[com.google.protobuf.any.Any, PlaysMusic]```
This simply introspects the ```typeUrl``` and produces the correct implementation type.

I feel like I'm on the right path but have the JSON bits to figure out, or is this the wrong way of approaching this? What would you recommend?

Note that the types also extend a specific implementation that addresses the PlaysMusic contract; so for example in the case of Guitar it also implements GuitarImplementation which is just another trait with a Scala self-type of PlaysMusic and overrides the method play().

Much appreciated!

**Comment by thesamet** [comment]
Take a look at [sealed oneofs](https://scalapb.github.io/sealed-oneofs.html) - it is designed exactly for this use case.
