### ISSUE TITLE
scalapb-runtime causes "Illegal reflective access ..." warnings for java > 8

### ISSUE THREAD

**Issue by eatkins** [scalapb/ScalaPB#559]
Presently sbt prints these warnings for any java runtime version greater than 8 due to the transitive dependency on protobuf-java:3.3.0 (see https://github.com/sbt/zinc/issues/459). There is a workaround (add an explicit dependency in the sbt build to protobuf-java:3.7.0), but it'd be nice to have a version of scalapb-runtime published with the updated dependency (a milestone release would likely be fine in the short term).

**Comment by thesamet** [comment]
We already have ScalaPB 0.9.0-RC1 which depends on protobuf 3.7.0. We will have 0.9.0 final in the near future.

**Comment by eatkins** [comment]
Great. Thank you. I couldn't find it on maven.

**Comment by thesamet** [comment]
https://mvnrepository.com/artifact/com.thesamet.scalapb/scalapb-runtime_2.12/0.9.0-RC1
