### ISSUE TITLE
getting an exception when calling my service from python

### ISSUE THREAD

**Issue by avnerbarr** [scalapb/ScalaPB#560]
I generated client stubs in python, but most times I encounter this exception when I call the service.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/avner/avner/venv/lib/python2.7/site-packages/grpc/_channel.py", line 549, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/avner/avner/venv/lib/python2.7/site-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Futures timed out after [10 milliseconds]"
	debug_error_string = "{"created":"@1553456403.745369717","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Futures timed out after [10 milliseconds]","grpc_status":13}"
```

I searched in grpc forum, but couldn't find much more then this explination

https://grpc.io/grpc/core/impl_2codegen_2status_8h.html#a35ab2a68917eb836de84cb23253108ebae648dab84c58ef5b1cfeea35867c4520

`GRPC_STATUS_INTERNAL | Internal errors. Means some invariants expected by underlying system has been broken. If you see one of these errors, something is very broken.`

`GRPC_STATUS_INTERNAL = 13`

**Comment by thesamet** [comment]
Looks like something is timing out after 10ms. This is a relatively short timeout. Try increasing it to at least a couple of seconds so we can tell whether that's the issue or not (probably is!). If this doesn't help, please provide a reproducible example.

**Comment by avnerbarr** [comment]
is there a server side timeout on the futures I'm returning my grpc implementation? (the functions return a future)

**Comment by thesamet** [comment]
Please take a look at https://grpc.io/blog/deadlines. From the information provided so far, this does not seem to be a ScalaPB bug, but an issue related to grpc or the way you are using grpc. ScalaPB is a pass-through wrapper between your code and grpc for this matter. I suggest to further debug this issue with the grpc community or StackOverflow.

**Comment by avnerbarr** [comment]
I increased it to 30ms , the problem indeed subsided on the client side. I left the client to add a timeout handler in their code . 

I still experience an issue though of a high latency between client and server. The server is reporting processing times of requests in the magnitude of 5ms but my client is experiencing around 20% deadlines at 20-30ms. 

Are there any mechanisms which can help to debug this?

**Comment by thesamet** [comment]
Are the client and server running on the same machine? If not, then the latency can come from your network.  If the client and server are running on the same machine, try to profile the client (which is in Python) to see where the time is spent. Since you indicate that the server's latency is slow, it is most likely happening on the Python side. I suggest to further debug this issue with the grpc community or StackOverflow.

**Comment by avnerbarr** [comment]
I'm asking since I thought perhaps there is a lower level processing that the scalapb code is doing that I can't account for in my simple timing metrics (for isntance the actual packet sent.) It could also be useful to get a metric on the round-trip time that the underlying libraries are seing (my server code is sandwitched in between)

**Comment by thesamet** [comment]
ScalaPB tries to call grpc-java as fast as it possibly can, without adding too much behavior or latency. It should be fairly easy to clone ScalaPB's runtime-grpc and add metrics, logging etc that would help you determine if there's any excessive time spent in the Scala side.
