### ISSUE TITLE
Implement two-way conversion between a message and `Struct`

### ISSUE THREAD

**Issue by rnd4222** [scalapb/ScalaPB#561]
Is there any way to convert case class to **Any** or **Struct** without using json4s?

**Comment by thesamet** [comment]
For `Any`, you can use `Any.pack` and `Any.unpack` to embed a proto inside an `Any`. There is no such functionality for `Struct`s. I don't think there's a functionality to convert between `Struct` and messages, even in scalapb-json4s. Can you provide more information on what you are trying to do, and we'll figure out whether there's a way to accomplish that, or turn this into a feature request.

**Comment by rnd4222** [comment]
I'm trying to use envoy api, and there is [some fields](https://github.com/envoyproxy/data-plane-api/blob/master/envoy/api/v2/route/route.proto#L127) that is **Struct**/**Any** typed.
And I want to create case class (defined as another message) and use it in this field.
How do I **Any.pack** it? It seems that generated case classes don't implement **Message** interface.

**Comment by thesamet** [comment]
There is no capability to convert a message to `Struct`. `Struct`s map naturally to JSON, so it would make sense to use JSON semantics when converting Structs to messages. The best way to accomplish this today would be to use `scalapb-json4s` and convert a struct to json and then that json to message (and vice versa). Would be willing to consider an implementation in ScalaPB if it's equivalent to the JSON spec (or follows another standard protobuf spec). Closing this in the meantime, but further discussion is welcome!
