### ISSUE TITLE
sealed oneof to allow for scalapb.message extends

### ISSUE THREAD

**Issue by aalkilani** [scalapb/ScalaPB#562]
When using [Sealed oneofs](https://scalapb.github.io/sealed-oneofs.html#sealed-oneofs), I would like to have the generated sealed trait, or generated object extend a base trait.
Today (scalapb 0.8.4), using either
`option (scalapb.message).extends`
OR
`option (scalapb.message).companion_extends`
on the sealed oneof message definition has the effect that the generated Message case classes that extend from scalapb.GeneratedMessage get the additional mixin and not the sealed oneof trait.

Here's a practical example:
proto file:
```
message PlayerShim {
    option (scalapb.message).extends = "MyBaseTrait";

    oneof sealed_value {
        BasketBallPlayer BasketBallPlayer = 1;
        SoccerPlayer SoccerPlayer = 2;
    }
}

message BasketBallPlayer {
    required int32 something = 1;
}

message SoccerPlayer {
    required int32 something_else = 1;
}
```

The generated code produces
```
sealed trait PlayerShim {
  isEmpty
  isDefined
  asMessage
}
```
Notice how the PlayerShim sealed trait does not extend `MyBaseTrait` even though it's "instructed" to do so.

Similarly, the PlayerShimMessage, BasketBallPlayer, and SoccerPlayer case classes end up extending `MyBaseTrait` instead.

The ask here is to provide an option, perhaps `(scalapb.message).sealedoneof_extends` that allows trait mix-ins for the generated sealed trait.

One practical use case for this is serialization with AKKA. To serialize a sealed one of, it's necessary to get the message via `asMessage`. This works fine if you only had one sealed oneof to deal with. When you have a few, there's no "base trait" to rely on such that Scala type matching would work with and `asMessage` could subsequently be called. In short, if I had multiple sealed one of traits, I would have to account for each and every one of them instead of doing something like this:

case oneof: MyBaseTrait => oneof.asMessage

Ideally, even if an option like this `(scalapb.message).sealedoneof_extends`  doesn't exist, ideally, all generated sealed oneof traits would extend from a base trait that we can match on globally. Currently, the generated sealed oneof trait does not mixin any global `type` or trait.

**Comment by thesamet** [comment]
Hi @aalkilani ,

I am fine with either the suggestions you made, and also with implementing both:
1. Add `sealed_oneof_extends` (repeated string). This would require a check in ProtoValidation that the message it is applied to is indeed a sealed oneof.
2. Introduce a base trait for all sealed oneofs in ScalaPB.

Will you be able to work on a PR?

@olafurpg , thoughts on (2)? It doesn't seem like this change would break existing code.

**Comment by aalkilani** [comment]
Yes, I can look into submitting a PR for this. Won't be for a few weeks until I can get to it. Thanks for the quick response.

**Comment by olafurpg** [comment]
Proposal (1) and (2) sound good to me 👍

**Comment by aalkilani** [comment]
Any pointers to where I can start? I see the scalapb.proto under ../protobuf/scalapb/scalapb.proto and I see the generated sources seem to be under scalapb-runtime/shared/src/main/scala/scalapb/options/MessageOptions.scala 

I couldn't find any "getting started" for contributing so far so just poking around. Any help is much appreciated.

**Comment by thesamet** [comment]
Fair point. I've meant to do this for quite sometime. I'm going to put something together today and share (#563)

**Comment by thesamet** [comment]
Added this page https://github.com/scalapb/ScalaPB/blob/master/CONTRIBUTING.md - feel free to reach out if you have any questions.

**Comment by aalkilani** [comment]
PR is ready to the best of my ability: https://github.com/scalapb/ScalaPB/pull/564
