### ISSUE TITLE
question: what is the purpose of the various thread pools and what is the best practice for configuration

### ISSUE THREAD

**Issue by avnerbarr** [scalapb/ScalaPB#565]
In the generated code the stub receives an execution context, i.e.

```
val ec =ExecutionContext.fromExecutor(Executors.newFixedThreadPool(20))
  val server = io.grpc.netty.NettyServerBuilder.forPort(1234).addService(ServiceGrpc.bindService(serviceImpl = serviceImpl,executionContext = ec)).build()
```

I also see in this question https://github.com/grpc/grpc-java/issues/3057 that it is recommended to change the "application executor, especially on server-side"

> There are two main thread pools in grpc: Netty event loops and application executor. The Netty event loops are current 2x the number of cores. The application executor is a Executors.newCachedThreadPool(), so it scales with load (possibly to its detriment). It should not end up being more than the maximum number of concurrent RPCs. It can be a good idea to override the application executor, especially on server-side, via ServerBuilder.executor() (ManagedChannelBuilder.executor() for client-side).

I see that there are a lot of options for configurint the NettyServer.

What is the role of the execution context that is passed in to the service builder, and if you have a good rule of thumb for configuration+ setting up the exector/boss/event groups etc directly on the netty server builder 

i.e
`io.grpc.netty.NettyServerBuilder.forPort(ApplicationConfig.Service.bindPort).executor(...)`

**Comment by thesamet** [comment]
The ExecutionContext that ScalaPB gets through `bindService` is used to adapt the `Future`s returned by unary methods (one request - one response) and adapt it to a grpc-java observer: https://github.com/scalapb/ScalaPB/blob/c3519338ae2d24509d8358564460ffae2b3dd87a/scalapb-runtime-grpc/src/main/scala/scalapb/grpc/Grpc.scala#L23

I expect this to be a pretty fast non-blocking behavior. I can't offer much guidance on tuning it, you can try experimenting with a default value. However, I anticipate that this wouldn't have substantial impact on the overall performance.

**Comment by avnerbarr** [comment]
The default value of what ?

**Comment by thesamet** [comment]
Edited - I meant different settings on the execution context, such as number of threads.
