### ISSUE TITLE
Release scalapbc artifact for v0.9.0-M2

### ISSUE THREAD

**Issue by aalkilani** [scalapb/ScalaPB#566]
Any change we can get a release artifact for scalapbc for the latest tag? Or perhaps show us how to create a local release ourselves? I tried putting something together for a few hours and continue to hit issues. Unfortunately most of our projects use Maven and ScalaPB Maven integration is still a bit of a pain. Was thinking of creating/forking a maven plugin specifically to address this.

For what it's worth, the approach we've taken differs from the [documented](https://github.com/thesamet/scalapb-maven-example) approach. The main motive is so we don't have to manually copy over proto file dependencies manually and potentially also get that wrong; so instead, we use the "[protobuf-maven-plugin](https://www.xolstice.org/protobuf-maven-plugin/)", have it pull down dependent proto files from projects we depend on and simply replace the `protocExecutable` in its configuration to run scalapbc instead. This works well. Need to know how to package up a release though. 

I tried taking 0.8.4 files and just replacing everything, including reference in the executable bash file, to current 0.9.0-M2 jars but that just hung at the generating step unfortunately.

**Comment by thesamet** [comment]
We've been having some issues with our build pipeline. In the meantime, in sbt, run `scalapbc/universal:packageBin` that would generate a zip under scalapbc/target/universal.

**Comment by aalkilani** [comment]
Thank you! This worked well. I'll go ahead and close the ticket.
