### ISSUE TITLE
JDK version support in 0.9.0

### ISSUE THREAD

**Issue by raboof** [scalapb/ScalaPB#567]
I see 0.9.0-M2 (at least `scalapb.options.compiler.Scalapb`) appears to be released compiled as class file version 54.0 (Java10):

```
java.lang.UnsupportedClassVersionError: scalapb/options/compiler/Scalapb has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

Are you intending to drop support for previous Java versions in 0.9.0, or is this unintended (perhaps an effect of the build pipeline issues alluded to in #566)?

**Comment by thesamet** [comment]
This is unintended, sorry about that and thanks for reporting. Future version will keep supporting Java 9.

**Comment by raboof** [comment]
Clear, thanks! I see build.sbt even suggests Java 7 as a target - I'd be happy with 8 ;)
