### ISSUE TITLE
repeated of String does not work with collection_type as Array

### ISSUE THREAD

**Issue by Dollyg** [scalapb/ScalaPB#571]
`repeated` of `String` does not work with `collection_type` as `Array`. Following is the error that comes in pb generated models. If the collection_type is changed to `Seq`, it works fine.

**Error**
```
PbBlob.scala:114:51: value asJava is not a member of Array[String]
[error]     javaPbOut.addAllStrings(scalaPbSource.strings.asJava)
[error]                                                   ^
[error] one error found
```

**proto file:**

```
syntax = "proto3";

package proto;

import "scalapb/scalapb.proto";

message PbBlob {
    repeated int32 ints = 1  [(scalapb.field).collection_type="Array"];
    repeated string strings = 2  [(scalapb.field).collection_type="Array"];
}
```

**Code to reproduce the error:**

```
import proto.blob.PbBlob
import scalapb.TypeMapper

case class Blob(ints: Array[Int], strings: Array[String])

object Blob {
  val data = Blob(Array(1, 2), Array("one", "two"))

  val blobTypeMapper: TypeMapper[PbBlob, Blob] =
    TypeMapper[PbBlob, Blob](b => Blob(b.ints, b.strings))(c => PbBlob(c.ints, c.strings))
}

object Demo extends App {
  val bytes: Array[Byte] = Blob.blobTypeMapper.toBase(Blob.data).toByteArray
  val blob: Blob         = Blob.blobTypeMapper.toCustom(PbBlob.parseFrom(bytes))
  println(blob)
}
```

**Comment by thesamet** [comment]
Hi @Dollyg ,

Using Array as custom collection does not work only when java_conversions are enabled. This is noted in the documentation at https://scalapb.github.io/customizations.html#custom-collection-types:

> Note: using Array is not supported along with Java conversions.

Do you really need java conversions? If so, I can revisit that limitation - I can't remember the details

**Comment by Dollyg** [comment]
Thanks @thesamet. I did not need the java conversions, disabling it works for me.

**Comment by thesamet** [comment]
Thanks for confirming. Closing the issue then.
