### ISSUE TITLE
Support the standard protoc plugin interface

### ISSUE THREAD

**Issue by kerinin** [scalapb/ScalaPB#572]
We're using [prototool](https://github.com/uber/prototool) to compiled shared PB definitions for multiple languages, but AFAICT it's not possible to use scalapb/c as a protoc plugin (ie, `protoc --scala_out=foo`, which forces us to build a scala-specific compilation step. It would be nice if scalapbc (or some other tool, ie `protoc-gen-scala`) could be used with the standard protoc executable.

**Comment by thesamet** [comment]
Agree it would be nice addition. Note that the generator is written in Scala/Java, so a possible solution would be to provide the desired plugin as a shell script that invokes a JVM.

**Comment by thesamet** [comment]
Done. You can try it out before the next release by running

    sbt universal:packageBin

This would produce a `scalapbc/target/universal/scalapbc-$VER.zip` that contains a `bin/protoc-gen-scala` executable which behaves as a standard protoc plugin. You can extract it and make it work. See the commit references above for additional documentation.

**Comment by ckchow** [comment]
seems to work. would love to see this released as a standalone artifact on maven. :)

**Comment by thesamet** [comment]
I've released 0.9.0-M4. It's on maven at http://central.maven.org/maven2/com/thesamet/scalapb/scalapbc_2.12/0.9.0-M4/

**Comment by ckchow** [comment]
I'm not exactly sure how to do this, but I mean it would be nice to have the scalapb plugin in a form where it can be consumed by the google gradle-protobuf plugin. right now I just kind of monkeypatched together my own version. 

```
protobuf {
    protoc {
      artifact = "com.google.protobuf:protoc:${protocVersion}"
    }

    // Locate the codegen plugins
    plugins {
      scala {
        path = 'tools/scalapbc-0.9.0-M3/bin/protoc-gen-scala'
      }
    }
```

**Comment by thesamet** [comment]
@ckchow what needs to happen to make that possible? Will you be able to provide more details in a separate ticket, and also work towards the solution?

**Comment by ckchow** [comment]
Yes, I am currently investigating. I'll open a ticket with some results.
