### ISSUE TITLE
Extension options only keep the last option set

### ISSUE THREAD

**Issue by coltfred** [scalapb/ScalaPB#574]
@thesamet asked me to produce a minimal example of only the last option being fetched properly when using `.extension` to fetch my specific types of options.

I _think_ I've traced the issue to being that the options aren't getting written as packed bytes. For instance the following was the UnknownFieldSet. The ScalaPB ones are pakced into a single ByteString, but mine are 2 separate byte strings.

```
UnknownFieldSet(
    Map(102000 -> Field(Vector(),Vector(),Vector(),Vector(<ByteString@4df828d7 size=3>, <ByteString@b59d31 size=14>)), 
            1020 -> Field(Vector(),Vector(),Vector(),Vector(<ByteString@62fdb4a6 size=92>)))
```

I've created a project demonstrating this issue. The message extension proto definition is [here](https://github.com/coltfred/scalapb-example/blob/master/src/main/protobuf/example/enums.proto) and the use of it is [here](https://github.com/coltfred/scalapb-example/blob/master/src/main/protobuf/example/user.proto).

I've also made that project have a main that is running 2 asserts and showing why it fails. Any help in tracking this issue down would be appreciated.

**Comment by thesamet** [comment]
A workaround is to define the options in a single line:

```
    option (enums.message) = { foo: FOO_TWO; bar: BAR_ONE };
```
