### ISSUE TITLE
Publish for 2.13.0-RC2

### ISSUE THREAD

**Issue by raboof** [scalapb/ScalaPB#586]
Depends on:
* [ ] https://github.com/lihaoyi/utest/issues/197
* [ ] https://github.com/scalapb/protoc-bridge/pull/28

**Comment by tOverney** [comment]
I guess this one can be skipped in favor of 2.13.0 which just got released: https://github.com/scala/scala/releases

**Comment by thesamet** [comment]
Filed #593
