### ISSUE TITLE
(scalapb.field).type option is ignored when field is a sealed oneof

### ISSUE THREAD

**Issue by marq** [scalapb/ScalaPB#587]
**src/main/protobuf/message.proto:**
```proto
import "scalapb/scalapb.proto";

option (scalapb.options) = {
    import: "scalapbtest.MySealedMessage.mapper"
};

message IntMessage {
    required int32 v = 1;
}

message StringMessage {
    required string v = 1;
}

message SealedMessage {
    oneof sealed_value {
        IntMessage intMsg = 1;
        StringMessage stringMsg = 2;
    }
}

message WrapperMessage {
    required SealedMessage msg = 1 [(scalapb.field).type = "scalapbtest.MySealedMessage"];
}
```

**scalapbtest/MySealedMessage.scala**
```scala
package scalapbtest

import message.{IntMessage, SealedMessage, StringMessage}
import scalapb.TypeMapper

sealed trait MySealedMessage

case object MyEmpty extends MySealedMessage

case class MyIntMessage(v: Int) extends MySealedMessage

case class MyStringMessage(s: String) extends MySealedMessage

object MySealedMessage {

	implicit val mapper: TypeMapper[SealedMessage, MySealedMessage] = new TypeMapper[SealedMessage, MySealedMessage] {

		def toCustom(base: SealedMessage): MySealedMessage = base match {
			case SealedMessage.Empty => MyEmpty
			case IntMessage(v) => MyIntMessage(v)
			case StringMessage(v) => MyStringMessage(v)
		}

		def toBase(custom: MySealedMessage): SealedMessage = custom match {
			case MyEmpty => SealedMessage.Empty
			case MyIntMessage(v) => IntMessage(v)
			case MyStringMessage(v) => StringMessage(v)
		}
	}
}
```

**expected `WrapperMessage`:**
```scala
case class WrapperMessage(
    msg: scalapbtest.MySealedMessage
)
```

**actual `WrapperMessage`:**
```scala
case class WrapperMessage(
    msg: message.SealedMessage
)
```

**Comment by thesamet** [comment]
Sealed oneofs are implemented by using a custom type from the code that would have been generated if it wasn't sealed - so it looks like you can't add your own custom type on top of that. That certainly can be fixed.

However, I am curious: why would you use a sealed oneof if you intend to type map it, rather than using a non-sealed oneof (and typemap it)? Afterall, the reason sealed oneofs exist is that the code they generate is a little easier to work with, but they are functionally equivalent to the non-sealed oneofs.

**Comment by marq** [comment]
I thought it would be easier to convert it to my trait using a sealed oneof. Now I see you're right, it's better to use a non-sealed one in my case.

**Comment by thesamet** [comment]
@marq you can use `(scalapb.field).type`

**Comment by thesamet** [comment]
For now, I've made the code generator throw an error when a sealed oneof is typemapped, so it is not silently ignored. If in the future, we have a compelling reason to support typemapping of sealed oneofs I'll be happy to review a PR.
