### ISSUE TITLE
Publish for Scala 2.13.0

### ISSUE THREAD

**Issue by thesamet** [scalapb/ScalaPB#593]

**Comment by raboof** [comment]
in progress at #596

**Comment by thesamet** [comment]
This got intertwined with the protobuf-java upgrade to 3.8.0 which is causing problems (more on that later). I'll stick for protobuf-java 3.7.x for now, and get a release for Scala 2.13 in the next day or so.

**Comment by thesamet** [comment]
Released 0.9.0-M7.
