### ISSUE TITLE
add "import scala.jdk.CollectionConverters" option in scalapb compiler-plugin?

### ISSUE THREAD

**Issue by xuwei-k** [scalapb/ScalaPB#598]
`scala.collection.JavaConverters` deprecated since Scala 2.13.

I think we should add new option for which class to use `scala.jdk.CollectionConverters` or `scala.collection.JavaConverters` for avoid deprecation warnings.

something like

```scala
  if (useJdkCollectionConverter) {
    printer.add("import scala.jdk.CollectionConverters._")
  } else {
    printer.add("import scala.collection.JavaConverters._")
  }
```

https://github.com/scalapb/ScalaPB/blob/34993f96528f29efc6f9aca6bb664e3b68fdaf12/compiler-plugin/src/main/scala/scalapb/compiler/ProtobufGenerator.scala#L1651-L1652

**Comment by giiita** [comment]
As a similar problem, default `Seq` has been changed from `scala.collection.Seq` to` scala.collection.immutable.Seq` from scala2.13'.
This will require a `toSeq` call during model conversion.

**Comment by xuwei-k** [comment]
> we should add new option 

Alternatively, create custom compat converter object in scalapb-runtime 🤔 

https://github.com/scala/scala-collection-compat/issues/208

**Comment by thesamet** [comment]
@xuwei-k yes! that would be my preference, so the same source compiles for all versions of Scala.

@giiita Can you clarify what problem you are referring to? Is there a warning you are seeing?

**Comment by giiita** [comment]
@thesamet 
No, there is no warning.

There is such an interface.
```
message AnyList {
    repeated string values = 1;
}
```

```scala
final case class AnyList(values: _root_.scala.collection.Seq[String])
```

In 2.12, the default Seq is `scala.collection.Seq`.
```
type Seq[+A] = scala.collection.Seq[A]
val Seq = scala.collection.Seq
```

so the following works.
```scala
case class MyList(values: Seq[String])

MyList(AnyList().values)
```

In contrast, in 2.13 it has been changed to `scala.collection.immutable.Seq`.
```
@migration("scala.Seq is now scala.collection.immutable.Seq instead of scala.collection.Seq", "2.13.0")
type Seq[+A] = scala.collection.immutable.Seq[A]
val Seq = scala.collection.immutable.Seq
```

so conversion by` toSeq` is necessary.
```scala
case class MyList(values: Seq[String])

MyList(AnyList().values.toSeq)
```

Since this breaks compatibility with 2.12, I think it is preferable to change the automatically generated code to `immutable.Seq`.

**Comment by thesamet** [comment]
@giiita Both `MyList.values` and `AnyList.values` are `scala.colleciton.Seq` in both Scala 2.12 and Scala 2.13. Therefore, `.toSeq` is not necessary for either version of Scala. I might be missing something - if so, can you please start a separate issue so the discussion stays focused here stays focused on the JavaConverters warning?
