### ISSUE TITLE
Support for `no_box` at message/file level 

### ISSUE THREAD

**Issue by fpopic** [scalapb/ScalaPB#616]
The idea came from the StackOverflow [question](https://stackoverflow.com/questions/56826332/scalapb-typemapper-for-custom-primitive-wrappers-not-found)

Instead of selecting `no_box` option for all usages of the message, it should be possible to define `no_box` option at the message level.

```scala
syntax = "proto3";

package my_package;

option (scalapb.options) = {
  scope: FILE
  no_box: true <----
};

message MyMessage {
     ....
}
```

but maybe it should be possible in every proto that consumes  the message `MyMessage` to override the message level option:

```scala
syntax = "proto3";

package my_package;

import "scalapb/scalapb.proto";
import "my_package/my_message.proto"

message Usage {
    my_package.MyMessage  = 1; <--- should become MyMessage in scala
    my_package.MyMessage  = 2 [(scalapb.field).no_box = false]; <--- should become  Option[MyMessage] in scala
}
```

Would like to contribute to scalapb but have no idea where to start and how big this change would be?

**Comment by thesamet** [comment]
@fpopic thanks for filing the issue. You are "possible to define `no_box` option at the message level", but the example code snippet is at the file-level. I prefer that we implement it at message-level and possibly at the file-level, but not just at the file-level without at the message-level.

Instructions for developing: https://github.com/scalapb/ScalaPB/blob/master/CONTRIBUTING.md there's a section that focuses on changes to scalapb.proto
The code that determines whether to box or not is at https://github.com/scalapb/ScalaPB/blob/48a89535c007f194dfc173ea7489bd870343bcaa/compiler-plugin/src/main/scala/scalapb/compiler/DescriptorImplicits.scala#L236

**Comment by thesamet** [comment]
I added this functionality today and will be part of the next release.

**Comment by fpopic** [comment]
Hey, thank you @thesamet! (was on a long vacation, didn't have time earlier to work on PR)
