### ISSUE TITLE
SSL dependencies for gRPC

### ISSUE THREAD

**Issue by matthewha123** [scalapb/ScalaPB#621]
Hello,
I am using scalapb 2.11

I am creating channels without .usePlainText:
`    val channel = ManagedChannelBuilder
      .forAddress("host", 50051)
      .userAgent("user")
      .build()`
When making gRPC calls through this channel I receive:
`java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available`

Following this I have added this dependency to my pom.xml:

> 

        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>2.0.20.Final</version>
        </dependency>

> 

I still receive the error. I am not sure how to proceed.

**Comment by thesamet** [comment]
Hi @matthewha123 , this is a better question for grpc-java, this aspect is not being handled by ScalaPB. You can start with this search: https://github.com/grpc/grpc-java/search?q=alpn&type=Issues and possibly file a new issue on that project. This came up multiple time for ScalaPB users, so I'd appreciate if you post back once you solved it.
