### ISSUE TITLE
Getting ClassNotFoundException: scalapb.GeneratedMessage when running with Spark cluster

### ISSUE THREAD

**Issue by yzhan-te** [scalapb/ScalaPB#622]
I am using ScalaPB with Spark to deserialize a Kafka stream. My current setup runs fine locally and deserializes correctly using standalone mode, but when I submit the project jar file to my AWS cluster and run the jar with `spark-submit`, it throws `ClassNotFoundException: scalapb.GeneratedMessage`.

This is my current code setup:
```scala
// project/scalapb.sbt
addSbtPlugin("com.thesamet" % "sbt-protoc" % "0.99.23")
libraryDependencies += "com.thesamet.scalapb" %% "compilerplugin" % "0.9.0-M7"

// build.sbt
scalaVersion in ThisBuild := "2.12.8"

lazy val commonSettings =
  Seq(organization := "com.myorg", version := "1.0-SNAPSHOT")

lazy val app = (project in file("."))
  .settings(commonSettings: _*)
  .settings(name := "spark-scala")
  .enablePlugins(AssemblyPlugin)

libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.4.3"
libraryDependencies += "org.apache.spark" %% "spark-sql-kafka-0-10" % "2.4.3"
libraryDependencies += "com.thesamet.scalapb" %% "scalapb-runtime" % scalapb.compiler.Version.scalapbVersion % "protobuf"

PB.targets in Compile := Seq(scalapb.gen() -> (sourceManaged in Compile).value)

// src/main/scala/com/myorg/SparkJob.scala
val stream: Dataset[ProtobufMessage] = spark.readStream
  .format("kafka")
  .option("kafka.bootstrap.servers", brokers)
  .option("startingOffsets", "earliest")
  .option("subscribe", "mytopic")
  .load()
  .map(_.getAs[Array[Byte]]("value"))
  .map(ProtobufMessage.parseFrom) // parse from generated protobuf case classes
```

I built the jar file using `sbt compile` and all protobuf case classes are inside `src_managed` so this part should be fine. I wonder if I need to pull some other jars for ScalaPB when submitting the job to spark?

I have no idea what went wrong here so any help would be appreciated! 

Edit:
Just tested running using `spark-submit` locally and it throws the same error too. Probably needs a jar for ScalaPB to submit to spark.

**Comment by thesamet** [comment]
Spark needs to be able to find the dependencies that you have. One way to accomplish it is to build a single jar with all the dependencies. You'll also need to shade `protobuf-java` since Spark comes with its own old version of it. See some hints at https://scalapb.github.io/sparksql.html
