### ISSUE TITLE
toJson loses the precision with float fields

### ISSUE THREAD

**Issue by ryanli-me** [scalapb/ScalaPB#624]
I was trying to write some unit test for a spark application where I used `to_json` function to marshal the `Dataset[MyProto]` to json. I tried to create expected json with `scalapb.json4s.Printer` with the following code.
```
  def marshal(obj: MyProto): String = {
    new Printer(
      includingDefaultValueFields = true,
      formattingLongAsNumber = true
    ).print(obj)
  }
```
`MyProto` contains fields with type `float`. After `marshal` those fields loses the precision. For example,
```
 Expected: 0.41804487
 Got: 0.4180448651313782
```
Sorry if I'm missing something. I'm fairly new to scala and very unfamiliar with the underlying `json4s`. Please let me know if I'm doing it wrong.

**Comment by ryanli-me** [comment]
When using `jackson` the float values are the same as the expected. However, the json result contains a lot of redundant fields like `allFields`.

**Comment by thesamet** [comment]
@ryanli-me can you provide the entire test case that is failing?

**Comment by ryanli-me** [comment]
@thesamet sure! Here's a simple version of the test.
Test proto is defined in `test.proto` and the simple test only marshals the proto and compare to the `to_json` function of spark. Also I provide the jackson's marshal result.


`test.proto`
```
syntax = "proto3";

option java_package="mytest.test";
option java_outer_classname="Proto";

message Test {
  float floatField = 1;
}
```

`ScalaPBSpec.scala`
```
package mytest.test

import mytest.test.test.Test
import scalapb.json4s.Printer
import org.scalatest.{FunSuite, Matchers, BeforeAndAfter}
import com.holdenkarau.spark.testing.{SharedSparkContext}
import org.apache.spark.sql.SQLContext
import com.stephenn.scalatest.jsonassert.JsonMatchers
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule

class ScalaPBTestSpec extends FunSuite with Matchers with SharedSparkContext with JsonMatchers {
  test("scala pb marshal to json") {
    val obj = Test(floatField = 0.41804487f)
    val expected = new Printer(
      includingDefaultValueFields = true,
      formattingLongAsNumber = true
    ).print(obj)
    println(s"scalaPB result: $expected")

    val sqlContext = new SQLContext(sc)
    import sqlContext.implicits._
    val got = sc.parallelize(Seq(obj)).toDS.selectExpr("to_json(struct(*)) AS value").first().get(0).toString
    println(s"spark to_json result: $got")

    val m = new ObjectMapper().registerModule(DefaultScalaModule)
    val jacksonResult = m.writeValueAsString(obj)
    println(s"jackson result: $jacksonResult")

    got should matchJson(expected)
  }
}
```
`console log`
```
scalaPB result: {"floatField":0.4180448651313782}
spark to_json result: {"floatField":0.41804487}
jackson result: {"floatField":0.41804487,"allFields":{"Test.floatField":0.41804487}}
[info] ScalaPBTestSpec:
[info] - scala pb marshal to json *** FAILED ***
[info]   Json did not match "{"floatField":0.41804487}" did not match "{"floatField":0.4180448651313782}"
[info]
[info]   Json Diff:
[info]   "floatField
[info]   Expected: 0.4180448651313782
[info]        got: 0.41804487
[info]   " (ScalaPBSpec.scala:30)
[info] ScalaTest
[info] Run completed in 4 seconds, 350 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
```

**Comment by thesamet** [comment]
Fixed in https://github.com/scalapb/scalapb-json4s/commit/9a0d4605ea934d4a1c1442149bc5c0da5384db8c - the problem was conversion from float to double that would cause the precision loss. Since json4s doesn't support floats directly we are now going through BigDecimals. This change is available in scalapb-json4s 0.9.3

**Comment by ryanli-me** [comment]
@thesamet Thanks for the quick fix!

**Comment by ryanli-me** [comment]
@thesamet `scalapb-json4s 0.9.3` has dependency on `json4s-jackson 3.6.7` which breaks spark2.4.3's dependency on `json4s-jackson` which is `3.5.3`(https://github.com/apache/spark/blob/5f4feeb0ae236cc2b4cff80889bf23c8e017d9d4/pom.xml#L717). 

As a result, I got `java.lang.NoSuchMethodError: org.json4s.JsonDSL$.seq2jvalue(Lscala/collection/Traversable;Lscala/Function1;)Lorg/json4s/JsonAST$JArray;` errors.

Is there a good way to fix this? I'm not sure if shading is going to work. Thanks!

**Comment by thesamet** [comment]
Yes, use sbt-assembly to create a fat jar that includes a shaded version of json4s-jackson.

**Comment by ryanli-me** [comment]
Can I run `sbt test` on a fat jar?

**Comment by thesamet** [comment]
You can publish your fat jar, and then have another project (or subproject in a multiproject build) that depends on that fat jar and includes your tests. Then you can use sbt test to test that thing.

**Comment by thesamet** [comment]
You can also create a fat jar of only your dependencies (without your own code), that should lead to an easier workflow so you won't have to publish the fat jar each time you make a code change.

**Comment by thesamet** [comment]
Actually, the easiest solution is to force your project into a lower version of json4s-jackson and possibly json4s. The way ScalaPB accesses those libraries hasn't changed, so it might work. See https://www.scala-sbt.org/1.x/docs/Library-Management.html#Overriding+a+version

**Comment by ryanli-me** [comment]
Oh, thanks!
