### ISSUE TITLE
JsonFormat throws "should not happen" when FieldDescriptor.`type` == None

### ISSUE THREAD

**Issue by ugniusb** [scalapb/ScalaPB#626]
According to [descriptor.proto](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto#L182-L184), `FieldDescriptor.type` "needs not be set".
However, if a message with a descriptor like that is encountered in [`JsonFormat.toJson`](https://github.com/scalapb/scalapb-json4s/blob/master/src/main/scala/scalapb/json4s/JsonFormat.scala#L233), it incorrectly delegates to [`serializeSingleValue`](https://github.com/scalapb/scalapb-json4s/blob/master/src/main/scala/scalapb/json4s/JsonFormat.scala#L265).

Specifically, [`(f: FieldDescriptor).protoType.isTypeMessage`](https://github.com/scalapb/scalapb-json4s/blob/master/src/main/scala/scalapb/json4s/JsonFormat.scala#L243) is `false` when `FieldDescriptorProto.type = None`: `protoType = asProto.getType = asProto.type.getOrElse(TYPE_DOUBLE) != TYPE_MESSAGE`.

I caused the situation by generating new descriptors with message fields, but this can also happen for generated enums.

For the fix, perhaps throwing an exception in the check is appropriate.

**Comment by thesamet** [comment]
Can you share more about the way you trigger this exception? Do you have a manually written subclass that extends `GeneratedMessage` with a manually instantiated `scalapb.Descriptor`? A possible way for us to fix would be to make `scalapb.Descriptor.protoType` recover the type using `scalaType`.

**Comment by ugniusb** [comment]
I manually create some descriptors and add them to parsed descriptors in a compiler plugin (`protocbridge.ProtocCodeGenerator`) before generating Scala sources, e.g.
```scala
val message = DescriptorProto(
  name = Some(s"Update${entity.getName}Request"),
  field = Seq(
    FieldDescriptorProto(
      //`type` = Some(TYPE_MESSAGE),
      typeName = entity.name,
      name = Some("entity"),
      number = Some(1),
    ),
    FieldDescriptorProto(
      //`type` = Some(TYPE_MESSAGE),
      typeName = Some("google.protobuf.FieldMask"),
      name = Some("fieldMask"),
      number = Some(2),
    ),
  ),
)
...
val file: FileDescriptorProto = ???
file.withMessageType(file.messageType :+ message)
...
```

Everything works fine if `TYPE_MESSAGE` is specified, but it was rather hard to debug as I forgot that haven't specified them days ago.

`scalaType` is `Double` in that case (maybe uses `asProto.getType` too?), so not really a way to recover.  
I think the only way to get the message-iness would be to get the descriptor via `file.descriptorsByName.get(field.typeName)` from one of the file descriptors in the dependency closure.

I imagine [self-describing messages](https://developers.google.com/protocol-buffers/docs/techniques#self-description) with `type = None` might also trigger this issue.

**Comment by thesamet** [comment]
I am surprised you are not getting an exception here when `scalapb.Descriptor` is being constructed at runtime: https://github.com/scalapb/ScalaPB/blob/master/scalapb-runtime/shared/src/main/scala/scalapb/descriptors/Descriptor.scala#L250 this should happen before `toJson` is called.

**Comment by ugniusb** [comment]
`getType` is `type.getOrElse(TYPE_DOUBLE)`, so no exception 🙂
