### ISSUE TITLE
Add an option for removing default parameter value in generated codes.

### ISSUE THREAD

**Issue by taeguk** [scalapb/ScalaPB#629]
Currently, there is default value for optional field in codes generated by `scalapb`.
For example, there is the proto file `message foo { int32 x = 1; }` written in proto3.
Generated code by `scalapb` is like: `final case class Foo(x: _root_.scala.Int = 0)`.
The problem is that a programmer can omit putting `x` when encoding data to proto because there is no compile error due to the default value (`0`).
So, removing default value in generated codes by `scalapb` is good for preventing programmer's mistake.
So, I suggest adding new option for removing default parameter value.

**Comment by thesamet** [comment]
Thanks for making this feature request and sending a PR. Sorry for the delay in getting back to you. I wanted to take the time to consider this change before getting back to you. While I understand the motivation behind this issue, I am hesitant to add an option to inhibit default values. My main concern is that features like this increase the complexity of the generator and as a result come with a maintenance cost, while only being useful for a small subset of users. It is also hard to remove them if they turn out to cause problems, since removing a feature like this significantly breaks code. Also, the behavior resulting from this feature is not aligned with other protobuf implementations.

For the time being, I am closing this issue. I am willing to reconsider if this turns out to be something people want, so the complexity and maintenance costs are warranted.

**Comment by taeguk** [comment]
@thesamet Thanks for your kind comment.
However, IMHO, I think that this option is important and very helpful. I don't think that it is only for a few users.
What I said is not that removing default value of optional field in protobuf.
What I said is preventing a user from omitting putting a field by mistake when constructing a protobuf object.
In many cases, a user want to put not default value but specific value to a field when constructing a protobuf object. But currently, a user can make a mistake so easily because of default value in constructor.
If there is no default value in constructor, a user don't make that kind of mistake. And even if a user want to put default value to field, he/she can do easily through putting default value explicitly.

Really my team made that mistakes frequently since introduced scalapb long time ago. Scala is the strongly typed language and many scala developers rely on compile time type system. But, the current behavior (default value in constructor) is contrasting to such things.
So I think the option I suggested can be useful for many scala developers.
I'm sorry, but could you consider one more time about, please?

**Comment by thesamet** [comment]
The use case and motivations are clear. I'm more comfortable adding it without a generator parameter (proto options only). Let's consider this experimental, we may remove it if there are some unintended consequences.

**Comment by thesamet** [comment]
Released ScalaPB 0.9.1, with `no_default_value_in_constructor` file-level option.

**Comment by AndreyIlin** [comment]
Hi @thesamet. 
Personally find this option very helpful, because of the reasons described in initial comment.
However I would find it more helpful if we had an ability to leave default values for Option fields.
Maybe through some other option.
Could you please consider this feature request?

**Comment by thesamet** [comment]
Currently, in ScalaPB whether a field has a default value in the case class constructor can be described like this, based on the field type, and the option `no_default_value_in_constructor` which defaults to `false`:

| setting  |  optional | required | repeated |
|----------| ------------| ------------ |------------|
|no_default_value_in_constructor=false | has default | no default | has default |
|no_default_value_in_constructor=true | no default | no default | no default |

It looks like the change you are asking for would only differ from the standard behavior for `repeated` fields - is that the intent?

**Comment by AndreyIlin** [comment]
Thanks for a quick reply.
Yes, that's exactly what I meant.

**Comment by kevinmu** [comment]
Related to the above, would it be possible to have a `no_default` field-level tag similar to `no_box`? My intuition was that those two tags were pretty similar in when they would be applied.

**Comment by thesamet** [comment]
I've released this functionality in 0.11.5, see the docs and tests in 5058fb6 for details.
