### ISSUE TITLE
Why `parseFrom` isn't  availiable. 

### ISSUE THREAD

**Issue by dmgcodevil** [scalapb/ScalaPB#665]
I followed the instructions provided on the web site but for some reason `parseFrom` isn't available.
I tried to add  `scalapb-runtime` into my sbt but it did not solve the problem. Am I missing something?

[similar question](https://stackoverflow.com/questions/55022567/unable-to-get-parsefrom-as-an-available-method-from-generated-proto)

**Comment by dmgcodevil** [comment]
Ah, it must be `% "compile"`  instead  of `% "protobuf"`

**Comment by thesamet** [comment]
There should be no need to add this `libraryDependency`. When you add `scalapb.gen` the right library dependency should be added for you automatically. It would be helpful if you can provide a minimal example project that demonstrates this behavior.

**Comment by dmgcodevil** [comment]
I have a multimodule sbt project. All proto files locate in `core` module:

```scala
// Protobuf compiler settings

PB.protoSources in Compile := Seq(file("core/src/main/protobuf"))
PB.targets in Compile := Seq(
  scalapb.gen() -> (sourceManaged in Compile in core).value
)

```

**Comment by thesamet** [comment]
It looks like you are generating projects in `core` from another project. So sbt-protoc adds the dependency on protobuf-runtime to the wrong subproject, and you have to add it manually to `core`. Sounds like you should move these proto settings to the right subproject.
Here is an example of how various `PB` settings are defined within a subproject.

**Comment by dmgcodevil** [comment]
@thesamet got, thanks
