### ISSUE TITLE
scalapb-json4s for Scala 2.13

### ISSUE THREAD

**Issue by lostiniceland** [scalapb/ScalaPB#674]
Any plans on releasing the json-support for Scala 2.13?

If the project is not continued, how can I convert from a generated case-class to the underlying java-type, so I could use the protobuf-java-format artefakt which expects a GeneratedMessage type to print to json.

**Comment by lostiniceland** [comment]
With regards to the Java-compatibility: the docs mention how to achieve this with SBT
```
PB.targets in Compile := Seq(
  PB.gens.java -> (sourceManaged in Compile).value,
  scalapb.gen(javaConversions=true) -> (sourceManaged in Compile).value
)
```
How to configure this via Maven ( I've followed the sample from here https://github.com/thesamet/scalapb-maven-example/blob/master/pom.xml )

**Comment by thesamet** [comment]
Hi @lostiniceland , we already have 2.13 support in the past few versions: https://mvnrepository.com/artifact/com.thesamet.scalapb/scalapb-json4s

For java conversions, `protobuf-maven-plugin` does not support passing parameters to plugins (see https://github.com/xolstice/protobuf-maven-plugin/issues/61). Once this is supported, you can add `java_conversions` as a generator parameter.

**Comment by lostiniceland** [comment]
Thanks for the clarrification. My Maven search was somehow wrong, the latest version I saw was 0.3.3 which only had Scala 2.12. Sorry
