### ISSUE TITLE
Feature Request: Custom names for enums

### ISSUE THREAD

**Issue by otto-dev** [scalapb/ScalaPB#675]
It's currently [possible](https://scalapb.github.io/customizations.html#custom-names) in ScalaPB to define a custom Scala field name in `messages`, but not for `enums`.

It would be great to be able to do the same for `enums`, since the Scala naming convention is that [constants and case object should be upper camel case](https://docs.scala-lang.org/style/naming-conventions.html#constants-values-variable-and-methods), not all-caps, like in Java or `protobuf`.

For example, in Scala you would write `DayOfWeek.Monday` and not scream `DayOfWeek.MONDAY`.

Would just make things more consistent and protobuf-generated code more transparent.

**Comment by thesamet** [comment]
It's a valid request to allow to customize scala names for enum values, though based on the reason you provided it seems like a better solution would be to provide a file-level/package-level option to use CamelCase for enums. I would have probably made it a default if it wasn't breaking the compatibility of generated code.

**Comment by otto-dev** [comment]
What? Already done?  Fantastic. :tada: :tada: :tada:

> better to provide a file-level/package-level option

100% agreed.
