### ISSUE TITLE
[scalapb-json4s][0.10.0-M1] java.lang.NoSuchMethodError: com.google.protobuf.timestamp.Timestamp.<init>(JI)V 

### ISSUE THREAD

**Issue by bjaglin** [scalapb/ScalaPB#679]
```
com.thesamet.scalapb:scalapb-json4s_2.12:0.9.3
com.thesamet.scalapb:scalapb-runtime_2.12:0.10.0-M1
```

It looks like [defaulting to `preserve_unknown_fields` in scalapb-runtime](https://github.com/scalapb/ScalaPB/commit/33a36bf126eeb2d542e779a9ad42d28a391ca309#diff-2923e745fb594e70c7ab6e469c54cdcfR103) is binary-incompatible as [`Timestamp(seconds = ns2, nanos = nn2)`](https://github.com/scalapb/scalapb-json4s/blob/v0.9.3/src/main/scala/scalapb/json4s/Timestamps.scala#L123) is turned (with scalac 2.12 & 2.13 at least) into `invokespecial com/google/protobuf/timestamp/Timestamp.<init>(JI)V`, which does not exist any longer in 0.10.0-M1 (the only constructor being`public Timestamp(long arg0, int arg1, scalapb.UnknownFieldSet arg2) { // <init> //(JILscalapb/UnknownFieldSet;)V`).

**Comment by bjaglin** [comment]
Instead of recompiling `scalapb-json` against `scalapb-runtime:0.10.0-M1` (which would obviously work), maybe we can have `compilerplugin` add a manual, second constructor without the `unknownFields` param for backward compatibility with all bytecode that would have been generated against `scalapb-runtime` so far?

I was expecting `scalac` to do that automatically, but I guess the number of constructors would explode. I am also surprised the call to `Timestamp.apply(JI)V` is inlined to the constructor call, but that's probably for performance reason, at the cost of binary-compatibility...

**Comment by thesamet** [comment]
Thanks for testing it out and reporting! I am concerned about introducing the additional constructor for compatibility since by being there it would become part of the binary API, so it will be difficult to remove it in the future without breaking binary compatibility again. So perhaps the best time to break things is now.

I am open to reconsider this if this becomes too much hassle.

In the meantime I have release scalapb-json4s 0.10.0-M1 which is compiled again ScalaPB 0.10.0-M1

**Comment by bjaglin** [comment]
Thanks for cutting a release! Should it be `0.10.0-M1` though since it follows `0.10.0`? I have opened https://github.com/scalapb/ScalaPB/pull/682 to close this.

**Comment by bjaglin** [comment]
> Should it be 0.10.1-M1 though since it follows 0.10.0?

It looks like the last scalapb-json4s is [back to 0.10.0-Mx](https://github.com/scalapb/scalapb-json4s/releases), is that on purpose?

**Comment by thesamet** [comment]
Yes, please ignore 0.10.1-M1.
