### ISSUE TITLE
Scala Vertx gRPC stubs generator

### ISSUE THREAD

**Issue by swetharamaiah** [scalapb/ScalaPB#681]
Upon using ScalaPB plugin for Vertx, plugin should be able to generate stubs that use Vertx Async Handlers in addition to the Response object.

For example: 
https://github.com/vert-x3/vertx-examples/blob/master/grpc-examples/src/main/java/io/vertx/example/grpc/pingpong/Client.java

Currently the stub returns `scala.concurrent.Future[_<ResponseObject>]`
`override def method(request): scala.concurrent.Future[ResponseObject]`

**Example:**
```
    override def calcSum(request: _root_.com.example.sum.SumRequest): scala.concurrent.Future[_root_.com.example.sum.SumResponse] = {
      _root_.scalapb.grpc.ClientCalls.asyncUnaryCall(channel, METHOD_CALC_SUM, options, request)
    }
```

Expected: 
`override def method(requestObject, io.vertx.core.Future<ResponseObject>)`

**Example in Java**
```
    public void unaryCall(io.vertx.example.grpc.Messages.SimpleRequest request,
        io.vertx.core.Future<io.vertx.example.grpc.Messages.SimpleResponse> response) {
      asyncUnimplementedUnaryCall(getUnaryCallMethod(), PingPongServiceGrpc.toObserver(response.completer()));
    }
```

**Comment by thesamet** [comment]
I would be happy to host a project that does it (custom generator and runtime for Vertx) under the ScalaPB org, but it's not a priority for ScalaPB right now. If anyone finding this and want to work on this, please shoot me a note here or through other channels. Closing for now.
