### ISSUE TITLE
Issues with oneof

### ISSUE THREAD

**Issue by ahjohannessen** [scalapb/ScalaPB#695]
Hi @thesamet 

I experience two issues with generated code involving `oneof` that causes conflicts.

The first is when a field inside of `oneof` is called `empty`:
```proto
syntax = "proto3";
package one_of_empty_name;

message OneOfFieldNamedEmpty {

  oneof content {
    Foo   foo   = 1;
    Bar   empty = 2; // fails to compile because field is called empty
    Empty baz   = 3; // Message called `Empty` is fine.
  }

  message Foo {}
  message Bar {}
  message Empty {}
}
```

The second issue is when a `oneof` field is named such that the generated code conflicts with a message on same level with same name:

```proto
syntax = "proto3";
package one_of_name_on_same_level;

message OneOfNameOnSameLevel {

  Options options = 1;

  message Options {

    // Does not work with name `foo_options` when a message
    // called `FooOptions` is on same level.

    oneof foo_options {
      FooOptions for = 1;
      BarOptions bar = 2;
    }

    message FooOptions { }

    message BarOptions {

      // Works fine when using same name as 
      // the enclosing message.

      oneof bar_options {
        uint64 baz1 = 1;
        Empty  bar2 = 2;
      }

    }

  }

  message Empty {}

}
```

I used the following setup:

```scala
addSbtPlugin("com.thesamet" % "sbt-protoc" % "0.99.26")
libraryDependencies += "com.thesamet.scalapb" %% "compilerplugin" % "0.9.4"

...

PB.targets in Compile := Seq(
  scalapb.gen() -> (sourceManaged in Compile).value
)
```

I have no control in the naming of fields in the protobuf definitions that I experience above issues with, otherwise I would just rename fields that cause conflicts.

**Comment by ahjohannessen** [comment]
Thanks a lot @thesamet :) You set a great example as an OSS maintainer :)

Would it be possible to get a 0.9.5 release with this, fs2-grpc is not so keen on milestone releases. If too convoluted, I can maintain a fs2-grpc that is based on 0.10.0-Mx release.

**Comment by thesamet** [comment]
Thank you. Of course, waiting on travis.

**Comment by ahjohannessen** [comment]
🤘

**Comment by thesamet** [comment]
v0.9.5 is on its way to maven central.

**Comment by ahjohannessen** [comment]
Thanks :)
