### ISSUE TITLE
Well known types not work in services

### ISSUE THREAD

**Issue by UkonnRa** [scalapb/ScalaPB#706]
## SBT Settings

```
addSbtPlugin("com.thesamet" % "sbt-protoc" % "0.99.27")

libraryDependencies += "com.thesamet.scalapb" %% "compilerplugin" % "0.10.0-M1"
```

## Proto code

```
import "google/protobuf/wrappers.proto";

service UserEndpoint {
    rpc GetPasswordById(google.protobuf.StringValue) returns (google.protobuf.StringValue);
}

```

## Generated code

```
  trait UserEndpoint extends _root_.scalapb.grpc.AbstractService {
    override def serviceCompanion = UserEndpoint
    def getPasswordById(request: _root_.com.google.protobuf.wrappers.StringValue): scala.concurrent.Future[_root_.com.google.protobuf.wrappers.StringValue]
  }
```

Here, the param is still `wrappers.StringValue`, rather than `Option[String]`

**Comment by thesamet** [comment]
It's indeed a bug - however, fixing it won't bring the result you expect :)

ScalaPB maps `StringValue` to a `String` type, not `Option[String]`, as the message itself doesn't encode presence or absence of the value. The wrapping inside an Option comes when this message is used as an optional field within a containing message. To achieve the effect that you want, you need to add a wrapper that has a single StringValue field. Then you can add a typemapper that would convert between your message and an optional message.

**Comment by UkonnRa** [comment]
THX! Learned a lot!
