### ISSUE TITLE
json4s issues with spark structured streaming

### ISSUE THREAD

**Issue by f0ster** [scalapb/ScalaPB#708]
Hello,

I am trying to convert proto dataframes to json using the `scalapb-json4s` lib.  

I am doing something like,
```
 val streamToLakeQ : StreamingQuery = myStreamingDataSet
      .map { o =>
          JsonFormat.toJsonString(o)
       }
      .writeStream
      .format("parquet")
      .outputMode("append")
      .option("checkpointLocation", cl)
      .start(outputLocation)

```

When I add it to my project, I get the following runtime error:
```
 Cause: java.lang.NoSuchMethodError: org.json4s.JsonDSL$.seq2jvalue(Lscala/collection/Traversable;Lscala/Function1;)Lorg/json4s/JsonAST$JArray;
```

I am on spark 2.4.4 and using 
```
  "com.thesamet.scalapb" %% "sparksql-scalapb" % "0.9.0" % Compile,
  "com.thesamet.scalapb" %% "scalapb-json4s" % "0.9.3" % Compile,
```

It looks like an issue with json4s 3.6.7 , https://github.com/json4s/json4s/issues/623

**Comment by thesamet** [comment]
Spark brings a version of json4s which is not binary-compatible with the version that ScalaPB has. You can get around this problem by shading json4s. See https://scalapb.github.io/sparksql.html#setting-up-your-project and add a `ShareRule.rename` for json4s.

**Comment by f0ster** [comment]
Thanks @thesamet ,  I am working with shading now, and getting a run time error when attempting to invoke "MyProto.parseFrom(bytes)" on the kafka reading,

```
ERROR ApplicationMaster: User class threw exception: java.lang.AbstractMethodError: repackaged.com.google.protobuf.descriptor.FileDescriptorProto$.parseFrom(Lcom/google/protobuf/CodedInputStream;)Lscalapb/GeneratedMessage;
java.lang.AbstractMethodError: repackaged.com.google.protobuf.descriptor.FileDescriptorProto$.parseFrom(Lcom/google/protobuf/CodedInputStream;)Lscalapb/GeneratedMessage;
	at scalapb.GeneratedMessageCompanion$class.parseFrom(GeneratedMessageCompanion.scala:211)
	at repackaged.com.google.protobuf.descriptor.FileDescriptorProto$.parseFrom(FileDescriptorProto.scala:303)
```

**Comment by thesamet** [comment]
It looks like you are shading ScalaPB classes as well. I am not sure what's the reason, but you can try to exclude them with `ShadeRule.keep("com.google.protobuf.descriptor.*")` as the first rule.  It's hard to help further without seeing the build. Can you set up a minimal git repo with precise instructions that will help me reproduce this issue?

**Comment by f0ster** [comment]
This has resolved my issues, thank you @thesamet
