### ISSUE TITLE
Intellij build fails when trying to integrate with scalapb

### ISSUE THREAD

**Issue by PKHeb** [scalapb/ScalaPB#720]
Once the classes are auto generated, running sbt compile /sbt assembly works fine. I am able to get a fat jar.

However Intellij idea fails to recognize thie below option in sbt

PB.targets in Compile := Seq(
  scalapb.gen() -> (sourceManaged in Compile).value
)

and tries to compile like a regular class, causing this error.

Error:(8, 41) type GeneratedFileObject is not a member of package scalapb
object DemoProto extends _root_.scalapb.GeneratedFileObject {

**Comment by PKHeb** [comment]
the runtime of the sbt jar fails with the below error

java.lang.NoClassDefFoundError: scalapb/GeneratedMessage

**Comment by PKHeb** [comment]
the issue is with this as well on run time.

  User class threw exception: java.lang.NoClassDefFoundError: scalapb/lenses/Updatable
at java.lang.ClassLoader.defineClass1(Native Method) 

I see two references, one of which has the pointer to the correct sources, but isn't included in the packaged jar

C:\Users\prashak\.ivy2\cache\com.thesamet.scalapb\compilerplugin_2.11\srcs\compilerplugin_2.11-0.9.4-sources.jar!\scalapb\package.scala
C:\Users\prashak\.ivy2\cache\com.thesamet.scalapb\compilerplugin_2.12\jars

**Comment by thesamet** [comment]
For the intellij problem: can you get IntelliJ to re import `build.sbt`? This will take care of the errors it shows.

I am missing information to help you on the second problem you are seeing at run time. I am not sure what your sbt configuration is like and how you build a fat jar. Can you provide additional information, or even better create a small project on github that can be used to demonstrate this problem?

**Comment by PKHeb** [comment]
@thesamet , thank you for the suggestion, i just re-imported build.sbt and that fixed the issue.
You can ignore the second one,as there was some sbt issues while setting up the fat jar
