### ISSUE TITLE
Primitive Wrappers loses scalar formatting config on JSON serialization 

### ISSUE THREAD

**Issue by msta** [scalapb/ScalaPB#727]
## Description

When serializing a protobuffer with a scalar-valued wrapper type to JSON, the `Printer` utility loses the config parameter `formattingLongAsNumber` as it is statically set to false. Which means that the only way to format longs as numbers is to write custom writer functions for wrapper types, which already exists. 

### testMessage.proto
```
syntax = 'proto3';
import "google/protobuf/wrappers.proto";

message TestMessage {
    google.protobuf.Int64Value someLong = 1;
}
```
### Test.scala
```
import scalapb.json4s.Printer
object Test {
  def main(args: Array[String]): Unit = {
    val printer = new Printer().formattingLongAsNumber
    val msg = TestMessage().withSomeLong(123456)
    println(printer.toJson(msg))
  }
}
```

## Expected Output
`JObject(List((someLong,JInt(123456))))`

## Actual Output
`JObject(List((someLong,JString(123456))))`

## Comments
It seems to me `JsonFormat.scala:446:primitiveWrapperWriter` could use `printer.config.formattingLongAsNumber` directly instead of always using `false`.

I would gladly make a PR with the change and run the tests if there's no obvious reason why it should be like this.

Thank you guys for a very nice job!

**Comment by thesamet** [comment]
@msta thanks for reporting and investigating. Sounds like this should be a relatively easy fix. Please make sure to include a test case in your PR as well. Once in, I'll cherry-pick into the 0.9.x branch as well.

**Comment by msta** [comment]
I opened a PR on the json library :-)
