### ISSUE TITLE
Unable to decode protobuf message using scalapb 

### ISSUE THREAD

**Issue by sidtandon2014** [scalapb/ScalaPB#731]
My use case is to decode Protobuf message present in kafka stream.
For this, first I need to convert proto message to class file, for which I have used following

1. Scalapb plugin - Throwing windows version error and plugin is crashing
2. scalapbc compiler tool - Class files generated are throwing error in the solution. "Any trait can be mixed with"
3. protoc - **Finally I have used protoc to encode proto message to class file. Included it in jar and put in on databricks cluster**

Now, when I am trying to decode this message using sparksql-scalapb. Its throwing following error:

**Unable to find encoder for type X.Protobufs.MessageBuffer.SMSBuffer. An implicit Encoder[X.Protobufs.MessageBuffer.SMSBuffer] is needed to store X.Protobufs.MessageBuffer.SMSBuffer instances in a Dataset. Primitive types (Int, String, etc) and Product types (case classes) are supported by importing spark.implicits._  Support for serializing other types will be added in future releases._**

Below code, I am using for decoding:

import java.io.{ByteArrayInputStream, ByteArrayOutputStream, ObjectInputStream, ObjectOutputStream}

  def serialise(value: Any): Array[Byte] = {
    val stream: ByteArrayOutputStream = new ByteArrayOutputStream()
    val oos = new ObjectOutputStream(stream)
    oos.writeObject(value)
    oos.close()
    stream.toByteArray
  }
  
eventhubs.select($"value").map(row => SMSBuffer.parseFrom(serialise(row(0))))

Not sure where I am making the mistake

**Comment by thesamet** [comment]
Hi @sidtandon2014 . Since you directly used protoc, I assume you generated Java code using `--java_out` (correct me if I'm wrong). As such, sparksql-scalapb can't help in providing Spark encoders for the generated classes and this is why you see the errors. If you are interested in working with Java protobufs in spark, please take a look at this unaffiliated project: https://github.com/saurfang/sparksql-protobuf

I am happy to help you with getting your code compiled using ScalaPB, but I'll need additional information on the errors you are seeing and step-by-step information of what you are doing to get those errors. Also, which versions of Windows, JVM you are using.

**Comment by sidtandon2014** [comment]
@thesamet  Thanks for the hint.
Now, I am able to compile the generated scala files (from proto message) using protoc and "protoc-gen-scala". (I have referred https://scalapb.github.io/scalapbc.html#using-scalapb-as-a-proper-protoc-plugin)

I am using 0.9.4 version of scalapb-runtime_2.11, as with latest version (0.10.0-M4) generated files are throwing some weird error w.r.t traits

Below is my system configuration:
Scala: 2.11.8
Spark: 2.4.0
OS: Windows 10
scalapbc: 0.9.4
protoc: 3.11.2

**Pom.xml dependencies**

> <dependency>
      <groupId>com.thesamet.scalapb</groupId>
      <artifactId>scalapb-runtime_2.11</artifactId>
      <version>0.9.4</version>
    </dependency>
    
    <dependency>
      <groupId>com.thesamet.scalapb</groupId>
      <artifactId>compilerplugin_2.11</artifactId>
      <version>0.9.4</version>
    </dependency>
    
    <dependency>
      <groupId>com.trueaccord.lenses</groupId>
      <artifactId>lenses_2.11</artifactId>
      <version>0.4.12</version>
    </dependency>

I am referring following JARs in spark:
scalapb_runtime_2_11_0_9_4.jar
sparksql_scalapb_2_11_0_9_0.jar

But while converting the stream data , I am getting an error:

**Code**
`import scalapb.spark.Implicits._
import X.Protobufs.MessageBuffer._
import org.apache.commons.lang.SerializationUtils

def anyTypeToByteArray(value: Any): Array[Byte] = {
    val valueConverted :Array[Byte] = SerializationUtils.serialize(value.isInstanceOf[Serializable])
    valueConverted
  }

kafkaQuery.select($"value").map(row => SMSBuffer.parseFrom(anyTypeToByteArray(row(0))))`

**Error**
**command-927991112657511:3: error: Symbol 'type <none>.frameless.TypedEncoder' is missing from the classpath.
This symbol is required by 'class scalapb.spark.ByteStringTypedEncoder'.
Make sure that type TypedEncoder is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
A full rebuild may help if 'ByteStringTypedEncoder.class' was compiled against an incompatible version of <none>.frameless.
import org.apache.commons.lang.SerializationUtils
       ^
command-927991112657511:12: error: Symbol 'type <none>.lenses.Updatable' is missing from the classpath.
This symbol is required by 'class X.Protobufs.MessageBuffer.SMSBuffer'.
Make sure that type Updatable is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
A full rebuild may help if 'SMSBuffer.class' was compiled against an incompatible version of <none>.lenses.
eventhubs.select($"value").map(row => SMSBuffer.parseFrom(anyTypeToByteArray(row(0))))
                                      ^
command-927991112657511:12: error: Symbol 'type <none>.lenses.ObjectLens' is missing from the classpath.
This symbol is required by 'class X.Protobufs.MessageBuffer.SMSBuffer.SMSBufferLens'.
Make sure that type ObjectLens is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
A full rebuild may help if 'SMSBuffer.class' was compiled against an incompatible version of <none>.lenses.
eventhubs.select($"value").map(row => SMSBuffer.parseFrom(anyTypeToByteArray(row(0))))**

**Comment by thesamet** [comment]
It looks like you are missing the transitive dependencies of ScalaPB and sparksql-scalapb. The way to accomplish that would be to build a single fat jar that contains your code and all needed dependencies. I don't have an example on how to do this with maven, but you can research online. The sample project I linked to accomplishes it with sbt.

**Comment by sidtandon2014** [comment]
Thanks.
Now, I am getting:

**Comment by thesamet** [comment]
It looks like you still don't have all the dependencies. This one comes from frameless, which depends on shapeless and other things: https://github.com/typelevel/frameless/blob/master/build.sbt

**Comment by sidtandon2014** [comment]
These are the dependencies I have specified in project. 
I guess frameless is already a part of sparksql-scalapb. Am I missing something?

><dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala-library</artifactId>
      <version>${scala.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-core_${scala.version.major}</artifactId>
      <version>${spark.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-sql_${scala.version.major}</artifactId>
      <version>${spark.version}</version>
    </dependency>
    <dependency>
      <groupId>com.databricks</groupId>
      <artifactId>dbutils-api_2.11</artifactId>
      <version>0.0.3</version>
    </dependency>
    
    
    
    <dependency>
      <groupId>com.thesamet.scalapb</groupId>
      <artifactId>scalapb-runtime_2.11</artifactId>
      <version>0.9.4</version>
    </dependency>
    <dependency>
      <groupId>com.thesamet.scalapb</groupId>
      <artifactId>compilerplugin_2.11</artifactId>
      <version>0.9.4</version>
    </dependency>
    <dependency>
      <groupId>com.thesamet.scalapb</groupId>
      <artifactId>lenses_2.11</artifactId>
      <version>0.9.4</version>
    </dependency>
    <dependency>
      <groupId>com.thesamet.scalapb</groupId>
      <artifactId>sparksql-scalapb_2.11</artifactId>
      <version>0.9.0</version>
    </dependency>

**Comment by thesamet** [comment]
Based on the error you are missing frameless

**Comment by thesamet** [comment]
It would be better to find a way to find the dependencies automatically, otherwise you'll end up with a very brittle solution. Consider looking into this, or using sbt.

**Comment by sidtandon2014** [comment]
Thanks. 
With SBT i am able to solve multiple things. But now while printing/ writing the DF it is throwing following error. Any clues?

com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).

**Comment by thesamet** [comment]
Nice progres ! The error is saying that the array of bytes that you are passing to ScalaPB's parseFrom is not a valid protobuf message. Looking at your `serialise` function on the first post in this issue - it seems odd. Why not pass `value(0)` directly. What data is in it? How are the protos represented in your Kafka topic?

**Comment by sidtandon2014** [comment]
Thanks @thesamet for quick response everytime.
Its working now for entire message, except one part.

If a message has byte field it is getting converted to "com.google.protobuf.ByteString" in generated source files, and when I am trying to do parseFrom it is throwing "Task not serializable".
I can avoid this field while accessing the data, but want to know your thoughts

**Comment by thesamet** [comment]
`ByteString`s are Serializable (see [here](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/ByteString)). sparksql-scalapb also have test that parse and serialize messages with bytes, so there must be something else going on. If you can provide a minimal example that causes it would be helpful.

**Comment by thesamet** [comment]
Closing this issue as my understanding is that there are no issues left to investigate. If there are any issues remaining please file a new issue.
