### ISSUE TITLE
Package scoped options from separate file

### ISSUE THREAD

**Issue by Charlyzzz** [scalapb/ScalaPB#737]
(conversation from Gitter)
 It would be nice to apply options
```
#myFile.proto

message MyMessage {
    option (scalapb.message).companion_extends = "MyCompanionExtension";
    ...
}
```
But defined on a separate file.

@thesamet:
> Currently there's no way to apply options without modifying the proto file. It would be interesting to look into a way to use package scoped options (https://scalapb.github.io/customizations.html#package-scoped-options) to set options in a separate proto file. If this is interesting to you, please file a ticket on github and we can look into. Please also indicate if you're available to work on a PR to expedite it

**Comment by Charlyzzz** [comment]
I'm having a hard time trying to imagine what you are suggesting, would you mind giving an example?

**Comment by thesamet** [comment]
I am thinking of something like this, in `package.proto`:

```
import "scalapb/scalapb.proto";

package com.mypackage;

option (scalapb.options) = {
  scope: PACKAGE
  flat_package: true
  message_options: [
    {
       scope: "com.mypackage.MyMessage", 
       options: {companion_extends="MyExtension"},
    },
    { scope: ..., options: ...}
  ]
};
```

`message_options` is a new repeated field that lists all the messages that needs their option set. `messafge_options.options` is a [`MessageOptions`](https://github.com/scalapb/ScalaPB/blob/edbca2050fb4eb2e29a7c00aff340e829f24c9b2/protobuf/scalapb/scalapb.proto#L110). If a message is listed there and in addition specifies its own options, the effective options are merged with preference to the ones in the message (similar to what we do for file options)

**Comment by Charlyzzz** [comment]
Will take a look, thanks!

**Comment by zenyui** [comment]
FWIW I would love this feature.
