### ISSUE TITLE
Missing classes trying to open repo with Intellij

### ISSUE THREAD

**Issue by Charlyzzz** [scalapb/ScalaPB#745]
Classes derived from `make_plugin_proto.sh` I believe are removed from the IDE.

```
Duplicated content roots detected
Path [.../ScalaPB] of module [root] was removed from modules [shared-sources]
```
Members such as `scalapb.options.compiler.Scalapb` and `scalapb.options.compiler.Scalapb.ScalaPbOptions` appear in red (as missing) and I'm not able to use autocomplete function.

Any ideas? 

How do you develop ScalaPB? Are you using IntelliJ?

**Comment by thesamet** [comment]
I transitioned to VS Code. Generally, if it compiles in SBT, but intellij has a problem analyzing the project - it's an IntelliJ bug. Having said that, if there's a simple change we can make to workaround this, I wouldn't mind merging it.
