### ISSUE TITLE
Generated case class constructor visibility

### ISSUE THREAD

**Issue by otto-dev** [scalapb/ScalaPB#755]
A feature request for consideration. It may or may not make sense.

Sometimes I need to have multiple messages inherit from the same sealed trait. Some of those messages are public API, others are for "internal" use only.

Due to the nature of sealed traits, I have to declare the internal messages as protobuf messages as well, which means they are visible in the entire application, even though those messages are meant to be used in a specific package/class only.

For such cases it would be nice to be able to configure the visibility of generated case classes. An argument may be made that this goes against the purpose of protobuf messages in the first place.

Background: Akka Typed, where actors receive both public and internal messages which necessarily inherit from the same trait.

**Comment by thesamet** [comment]
There is a feature that was meant to allow you to add annotations to the generated code, but it can be used as-is for setting visibility:

```
message Person {
  option (scalapb.message).annotations = "private";
  option (scalapb.message).companion_annotations = "private";
  optional string name = 1;
  optional int32 age = 2;
}
```

Would that work for you?

**Comment by otto-dev** [comment]
Yep, that does it, thank you. Quick and good solution as always :+1:
