### ISSUE TITLE
[feature request] option for scala_outer_package/scala_outer_object

### ISSUE THREAD

**Issue by forevergenin** [scalapb/ScalaPB#757]
I came across a  requirement where scala and java versions of classes are built as two different libraries and in some of the projects both versions needs to be included.

The `package` specifier is used by both java and scala and for most cases `java_outer_class` option is used to wrap Java classes under a specific class. Having a simliar option for scala classes is helpful in the same way.

Currently 'flatPackage' option server this situation but the suffix class name is always fixed (same as the proto file name where the message definition is). It would be great if some additional option is there which helps overridding this default value like `scala_outer_package` or `scala_outer_object`.

For example the scala version of kafka-streams library has all the [scala specific classes][0] under a subpackage named `scala` and in simliar in this scenario the `scala_outer_package` can be used to place all the scala case classes under `scala` package prefixed with the package name specied by `package` specifier.

[0]: https://kafka.apache.org/20/documentation/streams/developer-guide/dsl-api.html#scala-dsl

**Comment by forevergenin** [comment]
```
package foo.bar;
option scala_outer_packagename = "scala";

message EmptyMessage {
}
```

Generating java and scala classes for the above proto file should create packages like the below

1. For Java

```java
package foo.bar;

public final class EmptyMessage {
}
```

2. For scala

```scala
package foo.bar.scala
final case class EmptyMessage()
```

**Comment by thesamet** [comment]
We currently support:

    option (scalapb.options).package_name = "for.bar.scala";

Which I think is close enough (you have to give the whole package name, rather than just a suffix). It's probably better not to add a package suffix option given that we have a more powerful way to specify the entire package.

I am ok with  `scala_outer_package` if there's a use case. However, if you wrap your proto file with `message MyObject { }`, all the messages are going to be generated inside a companion object named `MyObject`, though sometimes this is not desirable and an option would be a cleaner way.

**Comment by thesamet** [comment]
Hi @forevergenin , can you confirm that `option (scalapb.options).package_name = "for.bar.scala";` is sufficient? And if not, why not? If so, we can close this issue.

**Comment by forevergenin** [comment]
@thesamet I have multiple proto files. Can `option (scalapb.options).package_name = "for.bar.scala";` be customized for each package. If yes then that meets my requirement.

**Comment by forevergenin** [comment]
I tried the `option (scalapb.options).package_name = "for.bar.scala"` approach. It meets my requirements. But in order for this to work I need to add `scalapb.proto` to code base to not break the generation of PB by other protobuf compilers (go and python) flows.

I think having `scala_outer_package` will be a cleaner approach. I can set the option as part of the `sbt` build task and need not necessarily introduce `scalapb` specific proto files and changes to the proto files.

**Comment by thesamet** [comment]
@forevergenin , great that `(scalapb.options).package_name` works. Understood that importing scalapb.proto in your proto files can be undesirable. Re an SBT option - we're trying to avoid external generator options that affect source compatibility as this leads to interoperability issues. See https://scalapb.github.io/faq.html#why-a-certain-customization-is-not-available-as-a-global-generator-parameter
