### ISSUE TITLE
java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by user753** [scalapb/ScalaPB#763]
>[error] (Compile / protocGenerate) java.lang.UnsupportedClassVersionError: protocbridge/frontend/BridgeApp has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

```
addSbtPlugin("com.thesamet" % "sbt-protoc" % "0.99.23")

libraryDependencies += "com.thesamet.scalapb" %% "compilerplugin" % "0.9.4"
```
```
scala 2.13.1
```
```
windows 10
```
```
java version "1.8.0_212"
Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.212-b10, mixed mode)
```

**Comment by thesamet** [comment]
I believe this issue has already been resolved. Please try updating to latest sbt-protoc (0.99.27) , and latest ScalaPB (0.9.6). Can you try and let me know?
