### ISSUE TITLE
oneof generates companion object with early initializer

### ISSUE THREAD

**Issue by jodersky** [scalapb/ScalaPB#772]
Consider the following protobuf definition:

```protobuf
syntax="proto3";

message Foo {
    oneof bar {
        int32 x = 1;
    }
}
```

the code generated by ScalaPB will contain an early initializer:

```scala 
object Foo extends scalapb.GeneratedMessageCompanion[protocol.Foo] {
  // ...
  sealed trait Bar extends _root_.scalapb.GeneratedOneof {
    def isEmpty: _root_.scala.Boolean = false
    def isDefined: _root_.scala.Boolean = true
    def isX: _root_.scala.Boolean = false
    def x: _root_.scala.Option[_root_.scala.Int] = _root_.scala.None
  }
  object Bar extends { // <----- early initializer
    @SerialVersionUID(0L)
    case object Empty extends protocol.Foo.Bar {
      //...
    }
   //...
  }
}
```

(the line containing the early initializer is marked with `// <----` in the snippet above).

While this code is valid Scala (up to 2.13), it cannot be compiled with dotty since [early initializers have been removed](https://dotty.epfl.ch/docs/reference/dropped-features/early-initializers.html).

Regardless of the alternative, I'm wondering why early initializers are necessary here in the first place? If not, removing them would allow ScalaPB-generated code to be compiled with dotty.

By the way, I tested the above with ScalaPB 0.9.4 and 0.10.0-M6, with various combinations of customization parameters.

**Comment by thesamet** [comment]
Thanks for reporting this. It looks like the generated code has been using early initializers since the first version we supported oneofs (November 2014). I don't think there was a good reason for it, it's most likely an error - the `extends` there is by mistake and it just happens to compile.

**Comment by jodersky** [comment]
Thanks for the fast response!
