### ISSUE TITLE
Feature Request: Typed Access to Descriptors

### ISSUE THREAD

**Issue by morgen-peschke** [scalapb/ScalaPB#789]
I'm currently working with a bit of code which needs to enforce additional constraints on messages beyond what's representable in protobuf (we're using gRPC), and I'm a bit stymied by how the functionality _nearly_ exists to do this in a general sort of way, but it's not _quite_ there.

You can use a `FieldDescriptor` to programmatically access fields, while being able to keep breadcrumbs for error reporting, but it moves type-checking to runtime, and there isn't a clean way to get field descriptors for known fields.

You can use the lenses to programmatically access fields, while keeping the association between a field and it's type, but the ability to keep breadcrumbs for error reporting is lost.

Are there currently plans to unify these capabilities? 

If not, would there be interest in a PR to address this by:
1. Adding field descriptors for the known fields to the generated messages.
    This would make it easy to access a `FieldDescriptor`:
    ```
    val fooDescriptor: FieldDescriptor = proto.fieldDescriptors.foo
    ```
2. Adding a path-dependent type to the `FieldDescriptor` class and an `Aux` trait to the `FieldDescriptor` companion object.
    Together with easy access to `FieldDescriptor`s, it would be possible to write more generic validations:
    ```
    def validateFoo[M <: GeneratedMessage](message: M, field: M => FieldDescriptor.Aux[M, Foo]): Either[ThingsWentWrong, Foo] = ???

    val result: Either[ThingsWentWrong, Foo] = validateFoo(msg, _.fieldDescriptors.foo)
    ```

**Comment by thesamet** [comment]
Hi @morgen-peschke ! I've been thinking of ways we can make field descriptors more type-safe, would love to see movement in this direction and will be happy to merge a PR. Since it sounds like a significant API change, I suggest we spend some time spec'ing the change more clearly. Maybe over a shared google doc?

Few things that it's important to clarify:
1. Would it break source or binary compatibility for existing users of FieldDescriptor?
2. Can you outline the new FieldDescriptor and Aux traits? What changes need to be done in the generated code?
3. Examples of the type of problems it is going to solve (will be helpful for adding to the docs later).

Thank you!

**Comment by morgen-peschke** [comment]
Sounds good 👍 
WRT the clarifying points:

1. We'd be adding stuff, and the constructors for the various `Descriptor` subclasses are all private, so it shouldn't break source compatibility. 
    `FieldDescriptor`'s hierarchy is complex enough that I don't know off the top of my head how adding a type member will affect binary compatibility.

2. While I'll need to pull the repo and play around with it a bit to clarify the details, conceptually the `FieldDescriptor` class won't change much at all.
    I'm not 100% sure the correct way to thread these values through the constructors yet, so there's going to be some hand-waving here, but conceptually it'd be something like this:
    ```scala
    class FieldDescriptor(...) extends BaseDescriptor {
      type Value
      type ContainingMessage
      ...
    }
    object FieldDescriptor {
      trait Aux[M <: GeneratedMessage, O] = FieldDescriptor {
        type Value = O
        type ContainingMessage = M
      }
    }
    ```

    Assuming a proto with this definition:
    ```protobuf
    message Foo {
      int32 bar = 1;
      string baz = 2;
    }
    ```

    The generated protos would be largely the same as they are today, with the addition of something like this:
    ```
    case class Foo(bar: Int, baz: String) {
      ...
      object fieldDescriptors {
        val bar: FieldDescriptor.Aux[Foo, Int] = ...
        val baz: FieldDescriptor.Aux[Foo, String] = ...
      }
      ...
    }
    ```
    It may end up making sense to add them as extensions (similarly to how lenses are handled, which have a really nice interface), or simple fields as in the example above.

3. The most immediate usecase I can think of is better support for typeclasses, validation being the one which comes to mind most readily (mostly because that's the one I'm working on), but I'm sure there are likely others.

I'll probably fork the repo tonight and start playing around with it a bit to better flesh out these ideas.

**Comment by thesamet** [comment]
The relationship you pointed out between lenses and field descriptors is interesting. Maybe the two concepts need to converge in Scala and it would create a nice API. I think that what you were trying to do (breadcrumbs for validation) would have been easier if only the lens had a reference to the current implementation of field descriptor.

**Comment by morgen-peschke** [comment]
I forked the repo last night and started poking around, and from what I can tell there's 3 ways forward which seem like they have promise.

1. Augment `FieldDescriptor` with type information. 
2. Augment `Lens` with metadata
3. Create a bridge between `FieldDescriptor` and `Lens`

### Augment `FieldDescriptor` with type information

While my initial impulse was to augment `FieldDescriptor` with type information, it doesn't look like this would really be feasible because of the way `FieldDescriptor` is constructed. The type information we'd need is discarded well upstream of where it's needed, so it would require quite a bit of restructuring to thread the information through to where it the `FieldDescriptor` is generated.

### Augment `Lens` with metadata

This definitely has strong potential for creating a clean API. I hadn't gotten to exploring possible changes to the lenses yet, so my thoughts on this one aren't well defined yet. That being said, I like the idea of augmenting `Lens` with pathing metadata. 

Having breadcrumbs in a lens makes sense conceptually, and it would minimize disruptions to the API surface. It may need to be a bit more complex than a `FieldDescriptor` reference - unless I missed something, I didn't see a way for `FieldDescriptor` to indicate which array element was part of the path of something like `_.update(_.foo(4).bar := baz)`.

I haven't done much exploration on this front yet, however it's conceptually similar to how I'm currently keeping path information, and it works fairly well, so there's definitely promise here.

I did notice that the lenses have been moved into the scalabp project, do we know if there are any external places it's used that might not have a `FieldDescriptor`?

### Create a bridge between `FieldDescriptor` and `Lens`

Creating a bridge was something I played around a bit with last night, and would involve adding some classes to link the lens and descriptors, then generating an instance for each field in the message companions. This has the advantage of creating a home for some other information which is currently only exposed in an erased form (like the enum/message companions). 

While not feasible now as a dependency on shapeless probably isn't desirable, it also creates values which could be used to create an `HList` of typed field informations when that becomes part of the standard library in Scala 3, which could open up additional opportunities for generic programming.

The biggest downside of this approach is that it feels a bit "bolted on", which isn't ideal.

A sketch of the bridge classes would something like this (there may be others for e.g. `oneof`, this is still very preliminary):

```scala
abstract class GeneratedFieldBridge[ParentPB <: GeneratedMessage, Value] {
  def javaDescriptor: JavaDescriptor
  def scalaDescriptor: Descriptor
  def lens: Lens[ParentPB, Value]
}

case class GeneratedScalarFieldBridge[ParentPB <: GeneratedMessage, Value](
  val javaDescriptor: JavaDescriptor,
  val scalaDescriptor: Descriptor,
  val lens: Lens[ParentPB, Value]
) extends GeneratedFieldBridge[ParentPB, Value]

case class GeneratedMessageFieldBridge[ParentPB <: GeneratedMessage, Value <: GeneratedMessage](
  val javaDescriptor: JavaDescriptor,
  val scalaDescriptor: Descriptor,
  val lens: Lens[ParentPB, Value],
  val messageCompanion: GeneratedMessageCompanion[Value]
) extends GeneratedFieldBridge[ParentPB, Value]

case class GeneratedEnumFieldBridge[ParentPB <: GeneratedMessage, Value <: GeneratedEnum](
  val javaDescriptor: JavaDescriptor,
  val scalaDescriptor: Descriptor,
  val lens: Lens[ParentPB, Value],
  val enumCompanion: GeneratedEnumCompanion[Value]
) extends GeneratedFieldBridge[ParentPB, Value]
```

Assuming this example proto:
```proto
package example

message Foo {
  enum Bar {
    UNKNOWN = 0;
    BAR = 1;
  }

  message Baz {
    string value = 1;
  }

  int32 int_field = 1;
  Bar bar_field = 2;
  Baz baz_field = 3;
}
```

We might generate something like this
```scala
...
object Foo extends scalapb.GeneratedMessageCompanion[example.Foo] {
    ...
    // Horrible name, maybe `fields`?
    object bridges {
        val intField: scalapb.GeneratedScalarFieldBridge[example.Foo, Int](
          javaDescriptor = javaDescriptor.findFieldByNumber(1).get,
          scalaDescriptor = scalaDescriptor.findFieldByNumber(1).get,
          lens = _root_.scalapb.lenses.Lens.unit[example.Foo].intField
        )
        val barField: scalapb.GeneratedMessageFieldBridge[example.Foo, example.Foo.Bar](
          javaDescriptor = javaDescriptor.findFieldByNumber(2).get,
          scalaDescriptor = scalaDescriptor.findFieldByNumber(2).get,
          lens = _root_.scalapb.lenses.Lens.unit[example.Foo].barField,
          messageCompanion = example.Foo.Bar.messageCompanion
        )
        val bazField: scalapb.GeneratedEnumFieldBridge[example.Foo, example.Foo.Baz](
          javaDescriptor = javaDescriptor.findFieldByNumber(3).get,
          scalaDescriptor = scalaDescriptor.findFieldByNumber(4).get,
          lens = _root_.scalapb.lenses.Lens.unit[example.Foo].bazField,
          messageCompanion = example.Foo.Baz.enumCompanion
        )
    }
}
```

**Comment by thesamet** [comment]
Some notes with regard to the specific ways proposed:
# Augment FieldDescriptor with type information
> The type information we'd need is discarded well upstream of where it's needed
We could change the way we instantiate FD's if needed.

> Augment Lens with metadata
> I did notice that the lenses have been moved into the scalabp project, do we know if there are any external places it's used that might not have a FieldDescriptor?

I am not aware. I think it's reasonable to assume that usage in the wild is limited to interaction with ScalaPB generated code.

# Create a bridge between FieldDescriptor and Lens
This approach is /possible/, but I think we'll miss on a chance to create a nicer API than what we have today, and instead package up our existing ones.

Also, if useful, feel free to experiment with writing your own generator for experimentation. It's fairly easy now to create a single sbt multi-project with a generator and a project that tests it. See https://github.com/scalapb/zio-grpc

**Comment by morgen-peschke** [comment]
Fair enough. I agree that unifying them would likely be much nicer API.

Adding a path in the form of something analogous to `Vector[Either[FieldDescriptor,Int]]` looks to be mostly straightforward. 

The method that's giving me trouble  is `zip`, as it has the potential to turn the straightforward path into a not-so-straightforward tree (which would unfortunately be growing from all the leaves at once), so I'll probably need to have a think on how that one would work. Part of that is figuring out if it's even possible to compose a lens once it's been zipped (other than by additional zipping). If not, it becomes much more tractable. 

As a hilarious aside: I ended up poking around in the guts of `FunctionalPrinter` about the same time I was playing around with a bit of code to generate a graph definition in DOT, and kept thinking how useful `FunctionalPrinter` would be

**Comment by morgen-peschke** [comment]
Turns out that augmenting `Lens` with a `FieldDescriptor` won't work directly without restructuring the project (`runtime` depends on `lenses`, so we'd need to merge the projects).

Good news is that it looks like we may not need to. I was able to get a change working that sidesteps this by making the descriptor generic, at the cost of having to do some type-level programming. The exposed API looks to be reasonable, so I'm optimistic about this approach (snippet from [`SimpleTest`](https://github.com/morgen-peschke/ScalaPB/blob/5663e913eb7478c58ffd16a6b12925610e3ae875/lenses/shared/src/test/scala/scalapb/lenses/SimpleTest.scala#L383):

```
    def renderLens[U, A, P <: Path](base: U, lens: Lens[U, A, P])(implicit renderPath: Render[P]): String =
      Render.render(lens.path(base))

    "it should build the expected lens path for apply selections" - {
      renderLens(mapTest, Lens.unit[MapTest].addressMap(mosh).street) ==> "_.addressMap(Ben, Mosh).street"
      renderLens(mapTest, Lens.unit[MapTest].intMap(3)) ==> "_.intMap(3)"
    }
```

To get it working, I had to add a type parameter to `Lens`, which I'd like to avoid. I'm hoping this was an artifact of something else that wasn't working at the time, and am going to take another pass at it to try and get that parameter back to being a type member.

I've pushed a [temporary commit](https://github.com/morgen-peschke/ScalaPB/commit/5663e913eb7478c58ffd16a6b12925610e3ae875) so you can check out the changes.

Possible areas of interest:
- `Path` ADT can be found [here](https://github.com/morgen-peschke/ScalaPB/blob/5663e913eb7478c58ffd16a6b12925610e3ae875/lenses/shared/src/main/scala/scalapb/lenses/Path.scala)
    This still needs to be documented. The relevant bits are at the very top, the rest of the file defines some operations and the needed extensions methods to make it work. 

    Because we need access to the generic type parameters of stuff nested deep, the return types can't be widened to `Path`, and often depend on the specific types of the parameters, and extension methods provide this. Happily, it's zero-import.

- [`SimpleTest`](https://github.com/morgen-peschke/ScalaPB/blob/5663e913eb7478c58ffd16a6b12925610e3ae875/lenses/shared/src/test/scala/scalapb/lenses/SimpleTest.scala) is probably the easiest way to see what the exposed API looks like at this stage.
    - [`Render`](https://github.com/morgen-peschke/ScalaPB/blob/5663e913eb7478c58ffd16a6b12925610e3ae875/lenses/shared/src/test/scala/scalapb/lenses/SimpleTest.scala#L40) is what it looks like to use the API to define a new operation (in this case, pretty-printing the path)
    
    - [`RoleMutation`](https://github.com/morgen-peschke/ScalaPB/blob/5663e913eb7478c58ffd16a6b12925610e3ae875/lenses/shared/src/test/scala/scalapb/lenses/SimpleTest.scala#L123) is pretty representative of the changes we'd need to make to the generated code (fairly minimal, all things considered)
        One part I'm not as happy with is `Path.Empty.appendField(...)`, so I'll probably be creating a helper to help avoid exposing `Path.Empty` to create a `Path.Single`.
    
        The path creation is defined as a [def](https://github.com/morgen-peschke/ScalaPB/blob/5663e913eb7478c58ffd16a6b12925610e3ae875/lenses/shared/src/main/scala/scalapb/lenses/Lenses.scala#L7) in `Lenses.scala` to support setting the path correctly in helpers like [`SeqLikeLens.last`](https://github.com/morgen-peschke/ScalaPB/blob/5663e913eb7478c58ffd16a6b12925610e3ae875/lenses/shared/src/main/scala-2.12/scalapb/lenses/CompatLensImplicits.scala#L28)

**Comment by morgen-peschke** [comment]
I was able to get the new type argument converted to a type member, and I'm not really sure it's worth the added complexity, as getting it to work required using `Lens.Aux` pretty much everywhere.

You can find the change to switch to a type member [here](https://github.com/scalapb/ScalaPB/commit/cbb3d86d94ac1542777503d5d1e17b7531faf3f0).

What are your thoughts about leaving the path as a type parameter? Either way, it looks like adding pathing information will unfortunately break binary compatibility, mostly due to changes in method signatures introduced to pass the additional path information around:
```
[error] lenses: Failed binary compatibility check against com.thesamet.scalapb:lenses_2.12:0.10.0! Found 18 potential problems (filtered 22)
[error]  * method apply(scala.Function1,scala.Function2)scalapb.lenses.Lens in object scalapb.lenses.Lens does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scalapb.lenses.Lens.apply")
[error]  * method apply(Int,scala.collection.generic.CanBuildFrom)scalapb.lenses.Lens in class scalapb.lenses.CompatLensImplicits#SeqLikeLens does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scalapb.lenses.CompatLensImplicits#SeqLikeLens.apply")
[error]  * method head(scala.collection.generic.CanBuildFrom)scalapb.lenses.Lens in class scalapb.lenses.CompatLensImplicits#SeqLikeLens does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scalapb.lenses.CompatLensImplicits#SeqLikeLens.head")
[error]  * method last(scala.collection.generic.CanBuildFrom)scalapb.lenses.Lens in class scalapb.lenses.CompatLensImplicits#SeqLikeLens does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scalapb.lenses.CompatLensImplicits#SeqLikeLens.last")
[error]  * method compose(scalapb.lenses.Lens)scalapb.lenses.Lens in class scalapb.lenses.ObjectLens does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scalapb.lenses.ObjectLens.compose")
[error]  * method zip(scalapb.lenses.Lens)scalapb.lenses.Lens in class scalapb.lenses.ObjectLens does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scalapb.lenses.ObjectLens.zip")
[error]  * method field(scalapb.lenses.Lens)scalapb.lenses.Lens in class scalapb.lenses.ObjectLens does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scalapb.lenses.ObjectLens.field")
[error]  * method field(scala.Function1,scala.Function2)scalapb.lenses.Lens in class scalapb.lenses.ObjectLens's type is different in current version, where it is (scalapb.lenses.Lens,scalapb.lenses.Path#Composer)scalapb.lenses.Lens instead of (scala.Function1,scala.Function2)scalapb.lenses.Lens
[error]    filter with: ProblemFilters.exclude[IncompatibleMethTypeProblem]("scalapb.lenses.ObjectLens.field")
[error]  * extension method field$extension(scalapb.lenses.Lens,scala.Function1,scala.Function2)scalapb.lenses.Lens in object scalapb.lenses.CompatLensImplicits#SeqLikeLens does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scalapb.lenses.CompatLensImplicits#SeqLikeLens.field$extension")
[error]  * extension method apply$extension(scalapb.lenses.Lens,Int,scala.collection.generic.CanBuildFrom)scalapb.lenses.Lens in object scalapb.lenses.CompatLensImplicits#SeqLikeLens does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scalapb.lenses.CompatLensImplicits#SeqLikeLens.apply$extension")
[error]  * extension method head$extension(scalapb.lenses.Lens,scala.collection.generic.CanBuildFrom)scalapb.lenses.Lens in object scalapb.lenses.CompatLensImplicits#SeqLikeLens does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scalapb.lenses.CompatLensImplicits#SeqLikeLens.head$extension")
[error]  * extension method last$extension(scalapb.lenses.Lens,scala.collection.generic.CanBuildFrom)scalapb.lenses.Lens in object scalapb.lenses.CompatLensImplicits#SeqLikeLens does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scalapb.lenses.CompatLensImplicits#SeqLikeLens.last$extension")
[error]  * extension method apply$extension(scalapb.lenses.Lens,java.lang.Object)scalapb.lenses.Lens in object scalapb.lenses.Lens#MapLens does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scalapb.lenses.Lens#MapLens.apply$extension")
[error]  * static method apply(scala.Function1,scala.Function2)scalapb.lenses.Lens in interface scalapb.lenses.Lens does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scalapb.lenses.Lens.apply")
[error]  * method compose(scalapb.lenses.Lens)scalapb.lenses.Lens in interface scalapb.lenses.Lens does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scalapb.lenses.Lens.compose")
[error]  * method zip(scalapb.lenses.Lens)scalapb.lenses.Lens in interface scalapb.lenses.Lens does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scalapb.lenses.Lens.zip")
[error]  * abstract method path(java.lang.Object)scalapb.lenses.Path in interface scalapb.lenses.Lens is present only in current version
[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("scalapb.lenses.Lens.path")
[error]  * method apply(java.lang.Object)scalapb.lenses.Lens in class scalapb.lenses.Lens#MapLens does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scalapb.lenses.Lens#MapLens.apply")
[error] stack trace is suppressed; run last mimaReportBinaryIssues for the full output
[error] (mimaReportBinaryIssues) Failed binary compatibility check against com.thesamet.scalapb:lenses_2.12:0.10.0! Found 18 potential problems (filtered 22)
```

**Comment by morgen-peschke** [comment]
I've been playing around with different encodings for `Path`, and I'd like to get feedback on what type signatures are more reasonable. The examples are pulled from a scratch project, the types were generated by IntelliJ and don't need to be written out for any of the versions of `Path` to function. I've included two versions of the type signatures: one nicely formatted to show the structure, and one as a single line to show what they'll look like in compiler error messages.

The examples will use these definitions:
```scala
    val p1 = Path.field(Foo).field(Bar)
    val p2 = Path.ap(3).field(Baz).ap("foobar")
```

### Initial Encoding

The initial version simply encodes the path by reifying the operations, which keeps the types from getting overly deep, at the cost of introducing the `Single` class to cut down on the number of times `Empty.type` shows up. This is somewhat undesirable as it breaks path equality (`Single(e)` is semantically, but not structurally equivalent to `Appended(Empty, e)`).

Composing two paths results in this signature:
```scala
    val p3 //: Composed[Appended[Single[Field[Var]], Field[Def]], Appended[Appended[Single[Apply[Int]], Field[Var]], Apply[String]]]
    //    : Composed[
    //        Appended[
    //          Single[Field[Var]],
    //          Field[Def]
    //        ],
    //        Appended[
    //          Appended[
    //            Single[Apply[Int]],
    //            Field[Var]
    //          ],
    //          Apply[String]
    //        ]
    //      ]
    = p1.compose(p2)
```

Zipping paths gives these signatures:
```scala
    val p4 //: Zipped[Zipped[Single[Field[Var]], Single[Field[Def]]], Single[Apply[Int]]]
//    : Zipped[
//        Zipped[
//          Single[Field[Var]],
//          Single[Field[Def]]
//        ],
//        Single[Apply[Int]
//        ]
//      ]
    = Path.field(Foo) zip Path.field(Bar) zip Path.ap(3)
    val p5 //: Composed[Zipped[Zipped[Single[Field[Var]], Single[Field[Def]]], Single[Apply[Int]]], Appended[Single[Field[Var]], Field[Def]]]
//    : Composed[
//        Zipped[
//          Zipped[
//            Single[Field[Var]],
//            Single[Field[Def]]
//          ],
//          Single[Apply[Int]]
//        ],
//        Appended[
//          Single[Field[Var]], 
//          Field[Def]
//        ]
//      ]
    = p4 compose p1
``` 

Overall, they're not terrible when formatted. I did find it easy to loose track of the nesting when the signatures were on a single line.

### Compacted Encoding

By investing some additional complexity in the `Composer` typeclass, we can collapse things down to the point where it's reasonable to drop `Single`. 

Unfortunately, because we need to support the `zip` operation, we can't get rid of `Composed` - a zipped path creates a hard-stop and prevents composition via concatenation. `zip` is likely a fairly uncommon operation, as I haven't figured out a way to build a lens which composes with the result of zipping two lenses, so this hopefully won't come up often.

This results in a deeper, but more straightforward type signature for simple composition:
```scala
    val p3 //: Appended[Appended[Appended[Appended[Appended[Empty.type, Field[Var]], Field[Def]], Apply[Int]], Field[Var]], Apply[String]]
    //    :
    //      Appended[
    //        Appended[
    //          Appended[
    //            Appended[
    //              Appended[
    //                Empty.type,
    //                Field[Var]
    //              ],
    //              Field[Def]
    //            ],
    //            Apply[Int]
    //          ],
    //          Field[Var]
    //        ],
    //        Apply[String]
    //      ]
    = p1.compose(p2)
```

Introducing zipped paths degrades back to something very similar to the initial nested type signatures, and they're similarly difficult to visually parse when formatted as a single line:
```scala
val p4 //: Zipped[Zipped[Appended[Empty.type, Field[Var]], Appended[Empty.type, Field[Def]]], Appended[Empty.type, Apply[Int]]]
    //  : Zipped[
    //      Zipped[
    //        Appended[
    //          Empty.type,
    //          Field[Var]
    //        ],
    //        Appended[Empty.type,
    //          Field[Def]
    //        ]
    //      ],
    //      Appended[
    //        Empty.type,
    //        Apply[Int]
    //      ]
    //    ]
    = Path.field(Foo) zip Path.field(Bar) zip Path.ap(3)
    val p5 //: Composed[Zipped[Zipped[Appended[Empty.type, Field[Var]], Appended[Empty.type, Field[Def]]], Appended[Empty.type, Apply[Int]]], Appended[Appended[Empty.type, Field[Var]], Field[Def]]]
    //  : Composed[
    //      Zipped[
    //        Zipped[
    //          Appended[
    //            Empty.type, 
    //            Field[Var]
    //          ], 
    //          Appended[
    //            Empty.type, 
    //            Field[Def]]
    //        ], 
    //        Appended[
    //          Empty.type, 
    //          Apply[Int]
    //        ]
    //      ], 
    //      Appended[
    //        Appended[
    //          Empty.type, 
    //          Field[Var]
    //        ],
    //        Field[Def]
    //      ]
    //    ] 
    = p4 compose p1
```

### Symbolic Encoding

I also played around with using symbolic infix types, and this results in a _really_ nice type signature:
```scala
    val p3 //: Empty.type |+| Field[Var] |+| Field[Def] |+| Apply[Int] |+| Field[Var] |+| Apply[String]
    //  : Empty.type |+|
    //    Field[Var] |+|
    //    Field[Def] |+|
    //    Apply[Int] |+|
    //    Field[Var] |+|
    //    Apply[String]
```
I don't think going full-symbolic is wise, as leaving `Composed` and `Zipped` untouched leads to fairly nice signatures and avoids having to remember more than 1 symbolic type:
```scala
    val p4 //: Zipped[Zipped[Empty.type |+| Field[Var], Empty.type |+| Field[Def]], Empty.type |+| Apply[Int]]
    //  : Zipped[
    //      Zipped[
    //        Path.Empty.type |+| Field[Var],
    //        Empty.type |+| Field[Def]
    //      ],
    //      Empty.type |+| Apply[Int]
    //    ]
    = Path.field(Foo) zip Path.field(Bar) zip Path.ap(3)
    val p5 //: Composed[Zipped[Zipped[Empty.type |+| Field[Var], Empty.type |+| Field[Def]], Empty.type |+| Apply[Int]], Empty.type |+| Field[Var] |+| Field[Def]]
    //  : Composed[
    //      Zipped[
    //        Zipped[
    //          Path.Empty.type |+| Field[Var],
    //          Path.Empty.type |+| Field[Def]
    //        ],
    //        Path.Empty.type |+| Apply[Int]
    //      ],
    //      Path.Empty.type |+| Field[Var] |+| Field[Def]
    //    ]
    = p4 compose p1
```

One benefit of the partially symbolic types is it makes it a bit easier to keep track of the nesting when `Zipped` and `Composed` do end up in the type signatures.

**Comment by morgen-peschke** [comment]
@thesamet : Hey Nadav, it's been about a month and normally this wouldn't be a big concern (things get pushed to the back burner, life's like that), however as your previous response time was about a day, and with all the crazy going on, I'd _really_ appreciate a short ping.

We'll get back to this when time permits, I'd just like to know you're still ok.

**Comment by thesamet** [comment]
Hi @morgen-peschke , sorry about the delay. It looks like this change is bringing a lot of complexity that I wasn't able to find time to digest. Hope I can find time soon. One possibility in the mean time may be to create an alternative generator that can produce the new style lens and descriptors outside scalapb core? The easiest way to get started with that is looking at zio-grpc

**Comment by morgen-peschke** [comment]
No worries, I'll have a look sometime in the next week or so :)

**Comment by thesamet** [comment]
I wrote some time ago a guide on how to write your own code generator: https://scalapb.github.io/docs/writing-plugins . Perhaps it would be useful to start experimenting with typed descriptors through an external project.
