### ISSUE TITLE
Issues with cross compiling to Python

### ISSUE THREAD

**Issue by mattdornfeld** [scalapb/ScalaPB#802]
I just started using scalapb to compile my protobuf code to Scala, but I'm having some issues cross compiling to Python. I'm using grpcio and grpcio-tools to peform the latter task however, the scalapb specific syntax is causing some issues. For example, grpcio-tools complains when I try to run `import "scalapb/scalapb.proto";` or extend a class using a scala base `option (scalapb.message).extends = "ScalaTrait";`. Is there a recommend way to get scalapb working with other protobuf compilers, or cross compile to other languages?

**Comment by thesamet** [comment]
Hi @mattdornfeld ,

Once you provide [scalapb/scalapb.proto](https://github.com/scalapb/ScalaPB/blob/master/protobuf/scalapb/scalapb.proto) and `google/protobuf/descriptor.proto` to the Python code generators, the errors you are seeing should be resolved. ScalaPB uses standard protocol syntax, so I wouldn't anticipate problems with other tools.

**Comment by thesamet** [comment]
@mattdornfeld Has this issue been resolved? It is currently not actionable so will close soon if I don't hear back.

**Comment by mattdornfeld** [comment]
Yes you can close. Thanks for the help.
