### ISSUE TITLE
Define Custom-Types even for generated java classes, possible?

### ISSUE THREAD

**Issue by giulianfazio** [scalapb/ScalaPB#843]
Hello,

I wanted to make use of custom types for message fields and I found the `(scalapb.field).type` option shown here: https://scalapb.github.io/customizations.html#custom-types.
I've implemented the example with the `Seconds` class and used it in my proto definition:
```
  optional int32 timeout = 1 [(scalapb.field).type = "mydomain.Seconds"];
```

It worked just fine for the generated Scala classes. 
But, once I enable the generation of Java classes (yes, I need them as well, unfortunately), the `timeout` field is still using `Int` as type instead of `Seconds`.

Is there a way - even a workaround - to make the `(scalapb.field).type` option have an effect also on the generated Java classes?

I'm using:
* `compilerplugin`  version `0.10.3`
* `sbt-protoc` version `0.99.28`

Thanks in advance for the help :)

**Comment by thesamet** [comment]
Hi @giulianfazio , the Java code is generated by Google's official Java generator. The option `(scalapb.field).type` is ScalaPB-specific. I don't believe there's an option to alter the Java generated types code in such a way, but you could try making this proposal to the official protobuf project (though I am doubtful a change like this would be introduced there).

If you are using the Java code in Scala, you can consider creating an implicit conversion on `Int`, so you can write something like `mymsg.timeout.asSeconds`.

**Comment by giulianfazio** [comment]
Unfortunately, that's the answer I was expecting.
Thank you for the help... and for providing such a useful option like `(scalapb.field).type` in ScalaPB 😃
