### ISSUE TITLE
Generated class for enum value differs only in case from another value

### ISSUE THREAD

**Issue by dsilvasc** [scalapb/ScalaPB#850]
If you add this enum definition with two enum values that differ only in case to `e2e/src/main/protobuf/enum.proto`:

```protobuf
enum EnumWithCaseInsensitiveClash {
  option allow_alias = true;
  EXAMPLE = 0;
  example = 0;
}
```

then `./e2e.sh` fails with:

```
[info] Compiling 296 Scala sources and 91 Java sources to /Users/dsilva/Snapchat/Dev/src/ScalaPB/e2e/target/scala-2.12/classes ...
[error] /Users/dsilva/Snapchat/Dev/src/ScalaPB/e2e/target/scala-2.12/src_managed/main/com/thesamet/proto/e2e/enum/EnumWithCaseInsensitiveClash.scala:27:15: Generated class com.thesamet.proto.e2e.enum.EnumWithCaseInsensitiveClash$example$ differs only in case from com.thesamet.proto.e2e.enum.EnumWithCaseInsensitiveClash$EXAMPLE$.
[error]   Such classes will overwrite one another on case-insensitive filesystems.
[error]   case object example extends EnumWithCaseInsensitiveClash(0) with EnumWithCaseInsensitiveClash.Recognized {
[error]               ^
```

When my team owns the enum, I can annotate one of the values with `[(scalapb.enum_value).scala_name = "SomeOtherName"]`.  This is a bit more difficult when another team owns the proto file.

Since this is valid proto and yields valid code in other languages, would it make sense for scalapb to disambiguate that case by itself when there isn't a `scala_name` option on one of the values?

**Comment by thesamet** [comment]
Hi @dsilva , Thanks for reporting. Few thoughts:
1. I believe this message is a warning, but your scala options turn into a fatal error. If you can turn it into a warning, or set your build to silence it, and your team doesn't use case insensitive file systems, it should be safe to ignore.
2. ScalaPB could try to disambiguate by adding suffixes or prefixes, but it would push the ambiguity to the programmer, which can result in bugs when the enum values are different.
3. One solution we have for setting options on files we don't own is auxiliary options. We have them for messages, fields and enums, but unfortunately not for enum values. See: https://scalapb.github.io/customizations.html#auxiliary-options  - would something like this work for you, and if so, can you look into sending a PR?

**Comment by dsilvasc** [comment]
Hi @thesamet , thanks for the quick response and for looking into options here.

Auxiliary options seem like a nice compromise between not editing definitions directly and not silently producing names that might surprise consumers of the generated scala code.

I can take a look at how to do that for enums.

**Comment by thesamet** [comment]
Thanks! Example of the pattern to follow is at https://github.com/scalapb/ScalaPB/commit/ce26a0706b5c615df11dcae5ee4f96aab0d57da5
