### ISSUE TITLE
Scalapb generates code which cannot compile when used with oneof along with no_box

### ISSUE THREAD

**Issue by adarshaj** [scalapb/ScalaPB#858]
I have the simple protobuf message as follows, which uses `oneof` and `no_box` option of scalapb:
```protobuf
syntax = "proto3";

package example.protobuf;

import "scalapb/scalapb.proto";

message Seconds {
  option (scalapb.message).no_box = true;  // do not wrap in Option
  int32 seconds = 1;
}

message Minutes {
  option (scalapb.message).no_box = true;  // do not wrap in Option
  int32 minutes = 1;
}

message Duration {
  option (scalapb.message).no_box = true;  // do not wrap in Option
  oneof duration_optional {
    Seconds seconds = 1;
    Minutes minutes = 2;
  }
}
```

Which generates wrong code and fails to compile.

I have put together a minimal reproduction here: https://github.com/hackcave/scalapb-oneof-nobox-issue-858

**Comment by thesamet** [comment]
Thanks for reporting @adarshaj , I think that we should add a check to not allow inclusion of no_box messages inside oneofs. If we do it, then instead of compilation error, you will get a nicer error message from ScalaPB explaining that the proto is invalid.

I assume though your intent in setting no_box was to achieve a certain code layout, rather than error, if so - can you share what were you were trying to accomplish?

**Comment by adarshaj** [comment]
Yes indeed, I have a custom business model in my app, which is used as custom type for generated protobuf model, however there's many of these custom models, so we planned to write a `TypeMapper` generating macro. but depending on enum/sealed oneof and Google's wrapper for optional primitive types (string), some have Option type and others have concrete values, which is difficult for us to generalize without getting rid of inconsistency in generated code (by kind of following rules that scalapb itself would use by looking at no_box for example). any inputs to solve this in a better/elegant way is highly appreciated!

**Comment by thesamet** [comment]
Can you illustrate the problem you described with specific code? What I'd like to understand better what your models are like, how you represent it as protos, what are the inconsistencies in the generated code, what would you expect it to look like when it's consistent?

**Comment by adarshaj** [comment]
sorry for delayed reply, we were trying out the changes and moved from message level `no_box` option to just field level `no_box` within each message. That solved our problem, we never wanted to write a type mapper for the field represented by `oneof` really. Thanks for indulging!

**Comment by thesamet** [comment]
Great, glad you were able to find a solution. Closing this issue then, and feel free to reach out if you need additional help.
