### ISSUE TITLE
Support `field_presence` from protoc 3.12

### ISSUE THREAD

**Issue by plaflamme** [scalapb/ScalaPB#870]
protoc 3.12 has added the notion of `field presence` to `proto3`

https://github.com/protocolbuffers/protobuf/blob/7eddac7877b6983cdb23a082dcbe63efe3403b95/docs/field_presence.md

It'd be nice if `scalapb` could support this in its generated code. Adding helpers to test field presence.

But more importantly, perhaps it could drop the `Option` wrapper when a field isn't `optional`? It's not clear if that actually works in practice, but having more flexibility around this would be a win in terms of usability of the generated code.

**Comment by thesamet** [comment]
Hi @plaflamme,
This experimental feature is now available in 0.11.0-M2. Just add:
```
Compile / PB.protocOptions += "--experimental_allow_proto3_optional"
```

> But more importantly, perhaps it could drop the Option wrapper when a field isn't optional?
Can you elaborate? This is the existing behavior for basic fields in proto3 when they are not optional. Singular message fields are still going to be wrapped in option (explicit presence) regardless of whether `optional` is given (and there's an option `no_box` to modify this behavior)

**Comment by plaflamme** [comment]
I'm not sure if my suggestion makes sense TBH, but I was assuming that if the explicit presence option is enabled, the generated code could forgo the `Option` wrapper for any singular message field that isn't marked `optional` by default (without needing the `no_box` option as well).

Mainly because if the user turns on this protoc option, they're explicitly requesting to track presence which means that they are assuming the wire will always contain non-optional fields even when they have the default value. From what I understand, deserialization can still occur successfully by setting the field to the default instance of the singular message type, and expose a `hasXX: Boolean` method to test presence (i.e.: for application-level validation).

As I said, I'm not 100% sure this makes sense, I've only considered singular message fields...

**Comment by thesamet** [comment]
The new experimental flag adds the `optional` keyword for proto3 to enable presence tracking for any singular field. It doesn't change the semantics for fields that are not labeled `optional`: all basic singular fields remain unwrapped, and singular message fields remain wrapped regardless of whether `optional` or not. Changing non `optional` message fields to be not wrapped in an `Option[]` would introduce a breaking change (in both logic and source-code compatibility), a deviation from the Java semantics, and will make it impossible to represent the absence of a message. You proposed to add a `hasX` method to track presence without `Option`, but that is inconsistent with the rest of ScalaPB, and doesn't seem necessary: you still have `msg.x.isDefined: Boolean` and `msg.getX: X`.

**Comment by plaflamme** [comment]
I definitely didn't put enough thought into this, though I do understand that it would be a breaking change to ScalaPB. From what I understand, presence doesn't change the semantics of the fields, but it does allow changes to the generated code, i.e.: to communicate information about field presence. I assumed that the new keyword would allow code generation to branch and potentially behave differently when it is present vs. not for a field. I'll dig into the generated Java code by protoc to better understand what this keyword does in practice.

My original use-case for unwrapping fields is for application-level validation. If a field is considered "non-optional" and it is missing on the wire, we want de-serialization to succeed, but application-level validation to fail (i.e.: based on field presence). Once a message type has gone through application-level validation, it'd be more idiomatic for the validated fields to be unwrapped (no `Option[T]`). But this cannot be the case since serialization requires `Option` to set `None`. So the thought was to split presence out into its own field (i.e.: `value: T` and `hasValue: Boolean`). I understand we can use `getValue: T` for a similar result. That said, I was somewhat hoping that field presence could enable this concept of optional/non-optional and trigger this code generation style (which seems to have the same semantics as before, but is a breaking change).

I'll close this since this isn't relevant to the original ask anymore.

**Comment by plaflamme** [comment]
RE: validation, I just discovered https://github.com/scalapb/scalapb-validate that's pretty awesome, thanks for all the work!
