### ISSUE TITLE
Missing package name in generated descriptors

### ISSUE THREAD

**Issue by ksvladimir** [scalapb/ScalaPB#871]
I'm using scalapb with google.protobuf.Any type, and got a problem with the generated descriptor names.

Say I've got a file `myproto.proto`:

```protobuf
syntax = "proto2";
package org.example;
message MyMessage {}
```

MyMessage class is available as `org.example.myproto.MyMessage`. However, the descriptor's fullName is missing `myproto` component:

```
scala> import org.example.myproto.MyMessage
scala> MyMessage.scalaDescriptor.fullName
val res9: String = org.example.MyMessage
```

I would expect the fullName to match the fully qualified name of the message class.

**Comment by thesamet** [comment]
@ksvladimir , `scalaDescriptor.fullName` returns the full name of the message in the protobuf namespace, not the Scala namespace. You can get the full Scala name from the class: `classOf[MyMessage].getName()`

**Comment by ksvladimir** [comment]
OK, got it. It makes sense, it means I just need to setup TypeRegistry accordingly.
