### ISSUE TITLE
gRPC stubs not generated per default

### ISSUE THREAD

**Issue by battermann** [scalapb/ScalaPB#879]
Generating gRPC stubs should be enabled by default according to the documentation: https://scalapb.github.io/sbt-settings.html#grpc

But it looks like it is not. It needs to be explicitly enabled.

Here is a minimal example that shows the issue: https://github.com/battermann/scalapb-test

With line 15 in the `build.sbt` it doesn't work:

```scala
scalapb.gen() -> (sourceManaged in Compile).value / "scalapb"
```

The object `com.example.protos.hello.GreeterGrpc` is not generated.

Like this it works:

```scala
scalapb.gen(grpc = true) -> (sourceManaged in Compile).value / "scalapb"
```

Now the object `com.example.protos.hello.GreeterGrpc` is generated.

**Comment by thesamet** [comment]
Thanks, that was a regression introduced in a recent change. The workaround you identified (passing `grpc=true`) should be used in the impacted versions (0.10.5 through 0.10.7). Newer versions would have grpc enabled by default.
