### ISSUE TITLE
Is there a recommended way of dealing with Unrecognized inputs for enums?

### ISSUE THREAD

**Issue by mattdornfeld** [scalapb/ScalaPB#882]
I'm case matching on enums generated by ScalaPB, and I'm getting a few warnings similar to
```
[warn] /scala/project/src/main/scala/co/company/package/types/Events.scala:78:7: match may not be exhaustive.
[warn] It would fail on the following input: Unrecognized(_)
[warn]       liquidity match {
```
Is there a recommended way of dealing with this? I was hoping to find a solution other than explicitly dealing with the Unrecognized case in the case match each time, but that's all I can think of right now.

**Comment by thesamet** [comment]
Hi @mattdornfeld , in each enum companion object, there's a trait called Recognized, which all the recognized enums extend. If you are sure your enum is recognized (at the cost of a runtime exception if it's not), you could write:

```
myEnum.asRecognized.get match {
  case ... =>
}
```

**Comment by mattdornfeld** [comment]
Thank you! That solves it.
