### ISSUE TITLE
How can I get deserialize proto supported types as Java types?

### ISSUE THREAD

**Issue by mattdornfeld** [scalapb/ScalaPB#890]
Let's say I have a proto message like so
```
message Duration {
  google.protobuf.Duration duration = 1;
```
I want to define a `TypeMapper` such that the `duration` field gets deserialized as a `java.time.Duration` class. The ScalaPB documentation does a good job of showing how I can do this with a custom class: define the class, define the companion object with the implicit `TypeMapper`, then put the appropriate annotation in the proto file. But I'm not sure how to do this with an already defined class. Defining the `TypeMapper` is easy enough 
```
import java.time.{Duration => JavaDuration}
import com.google.protobuf.{Duration => ProtoDuration}
import scalapb.TypeMapper

implicit val typeMapper = TypeMapper[ProtoDuration, Duration](
  protoDuration => JavaDuration.ofNanos(protoDuration.getNanos)
)(
  duration =>
    ProtoDuration
      .newBuilder()
      .setNanos(duration.getNano)
      .build()
)
```

But I'm not sure where to put it so that ScalaPB can find it, since I can't define a companion object for `JavaDuration`.

**Comment by thesamet** [comment]
Hey @mattdornfeld , you can place the implicit typemapper in a package object for the same package as the generated code, or any of its parent packages. For example, if your proto file has `package a.b.c` statement, you can put the typemapper in c's package object like this:

```
package a.b

package object c {
  implicit val typeMapper = ...
}
```

**Comment by thesamet** [comment]
I believe the answer should address the issue. Feel free to respond here or open a new issue if there are further questions.
