### ISSUE TITLE
Annotations on unknownFields

### ISSUE THREAD

**Issue by gael-ft** [scalapb/ScalaPB#898]
Hi, 

Generated protobuf classes are also used as database model in some cases.

(De)Serialization logic for a given class is handled by the database plugin itself but we would like to ignore `unknownFields` which could be done using annotations.

Would it be possible to add an option to add annotations on the generated `unknownFields` field ?

**Comment by thesamet** [comment]
Hi @gael-ft, Yes, this feature request makes sense.

Will you be able to contribute a PR for this? There are some starting points here https://github.com/scalapb/ScalaPB/blob/master/CONTRIBUTING.md and I'll be happy to help and answer questions.

**Comment by gael-ft** [comment]
Yes I can try to find some time to contribute this month. I'll keep you informed @thesamet.

**Comment by gael-ft** [comment]
Closing issue as implemented and merged.
