### ISSUE TITLE
Include proto files from "dependsOn" dependencies

### ISSUE THREAD

**Issue by ghostbuster91** [scalapb/ScalaPB#924]
Currently it is possible to:
- load proto files from the project (`src/main/protobuf`, `src/main/proto` or custom)
- load proto files from a packaged dependency
(`libraryDependencies += "com.example" %% "my-grpc-service" % "1.0.0" % "protobuf"`)

However, is it possible to load proto files from a local project whose my project depends on using `dependsOn`?

I tried `dependsOn(projectWithProto)` and `dependsOn(projectWithProto % "protobuf")` but the 'local' proto files are not recognized (if the `projectWithProto` includes other protos via `libraryDependencies` they are being recognized)

This question was originally asked by @olivierlemasle here https://github.com/akka/akka-grpc/issues/487, but I've just run into the same problem.

My usecase:
I have a sbt-module - moduleA and want to expose its api via grpc. Simple, just need to create moduleA-api  which contains protobuf definitions and configure scalapb for this module. Obviously in a real world I will probably use some highlevel wrapper over standard grpc service like akka-grpc or fs2-grpc. That means that this module will now contains both scala classes which represents grpc messages and akka wrapper around grpc stub. But what if I would like to consume this api from another project which is fs2 based? Although it might work to generate fs2 wrappers alongside with akka it seems impractical since it requires my fs2 module to depend on akka. In other words I would like to postpone the decision of using particular implementation to the call side.

**Comment by thesamet** [comment]
`dependsOn` will add the protoc's imoprt search path the protobuf source directories of the dependant project. Here is a test:  
https://github.com/thesamet/sbt-protoc/tree/master/src/sbt-test/settings/depends-on

Would that work for your use case?

**Comment by thesamet** [comment]
If in addition, you want the sub-project to generate akka-grpc/fs2-grpc code for the imported protos, you have to add the proto files as sources. Didn't test the below, but it would be something like:

```
(PB.protoSources in Compile) += (baseDirectory in baseProject).value / "src" / "main" / "protobuf"
```

**Comment by ghostbuster91** [comment]
Yes, the second option did the trick for me. 
I also run into some problems with configuring the google types in a such setup but eventually figured that out. Here is my demo project. If you could take a look at the last commit to check if this is how protobufs should be shared I would really appreciate that. https://github.com/ghostbuster91/fs2-grpc-example/commit/deb8710b6549600f945a3bc63a0df0753b2a2ea0

**Comment by thesamet** [comment]
I am not sure what `dependsOn(otherProject % "protobuf")` does. It is sufficient to do ` dependsOn(otherProject)` to be able to import protos from the other project.
