### ISSUE TITLE
Apply scalapb options to google.protobuf.Timestamp?

### ISSUE THREAD

**Issue by RyanBerti** [scalapb/ScalaPB#938]
Hi @thesamet 

I'm attempting to use the scalapb-generated protos in Scio, Spotify's Scala wrapper for Apache Beam. Scio/Beam doesn't like Seqs, so I've been adding the scalapb options to override collection_type to be List, and also setting preserve_unknown_fields to false (as those unknown fields use a Seq[Long] under the covers). I'd like to apply the same options to the scala file associated with google.protobuf.Timestamp; can this be done via package scoped option (where package would be google.protobuf)? I attempted this, but I can't tell if the Timestamp.scala is actually being generated, or is being pulled in via some dependency? Any context here would be helpful.

Thanks!

**Comment by thesamet** [comment]
Hi Ryan, google protos are pre-generated and are shipped with ScalaPB, so the custom options you are setting do not modify them. An easy solution would be to use your own timestamp case class. Few things you can try:
1. Replace google.protobuf.Timestamp with yourpkg.Timestamp which is just a copy of Google's Timestamp message into your own code.
-OR-
2. We can automatically override the class used for Timestamp across your entire code through auxiliary options. Create a new `timestamp_override.proto` that looks like this:
```
syntax = "proto3";
package google.protobuf;

option (scalapb.options) = {
    scope: PACKAGE
    aux_message_options: [
        {
            target: "google.protobuf.Timestamp"
            options: {
                type: "com.mycode.MyTimestampCaseClass"
            }
        }
    ]
};
```
Then, define in your own code your own timestamp case class, as well as a typemapper between Google's timestamp and your one. https://scalapb.github.io/docs/customizations/#message-level-custom-type-and-boxing

**Comment by RyanBerti** [comment]
Thanks for the info - I found that due to our proto repo structure, I was only able to force this package change on the proto files within the same directory. I assume I had done something wrong, but at this point I'm moving away from attempting to specify too many scalapb options and instead attempting to configure the consumer of these classes to handle the non-configured classes. For context, I'm attempting to utilize these generated classes to generate BigQuery schemas, so I've been testing your scala4s, as well as Spotify's BigQueryType and magnolify alongside these generated classes. Because our proto definitions are relatively complex (via nesting and customizations), nothing has worked out of the box, but I'm getting close with magnolify as it's allowing me to configure custom type handlers quickly. Testing is still trial/error due to the use of macros for all of these.

**Comment by thesamet** [comment]
Sounds good. FWIW, adding package-scoped options apply to a single protoc run (a single sbt subproject). To get the option to kicked in to other subprojects, the file either needs to copied, or explictly imported by another proto in that sub-project.
