### ISSUE TITLE
Compile error with proto field called "empty"

### ISSUE THREAD

**Issue by lukapeschke** [scalapb/ScalaPB#943]
Hello,

I've got a compile error when trying to compile the following proto message:
```protobuf
message Foo {
  message Empty{}

  oneof Bar{
    Empty empty = 1;
  }
}
```
The error is `Foo.scala:111:9: method isEmpty is defined twice;`, and indeed, the generated code looks like this:
```scala
sealed trait Bar extends _root_.scalapb.GeneratedOneof {
  def isEmpty: _root_.scala.Boolean = false
  def isDefined: _root_.scala.Boolean = true
  def isEmpty: _root_.scala.Boolean = false
  def empty: _root_.scala.Option[foobar.Foo.Empty] = _root_.scala.None
}
```
This issue seems to be similar to https://github.com/scalapb/ScalaPB/issues/207 .

I have no control over the proto source files, so renaming the fields is unfortunately not an option. Is there a way to overcome this error ?

**Comment by thesamet** [comment]
@lukapeschke , you can use auxiliary options to rename the message or the field without changing the original proto: https://scalapb.github.io/docs/customizations#auxiliary-options

**Comment by lukapeschke** [comment]
@thesamet thanks, I missed that part of the docs, it'll be useful!

In the end, we found https://github.com/scalapb/ScalaPB/issues/695 and upgrading to 0.9.5 appears to have solved the issue. But we'll probably have to use auxiliary options in the future, so your link will definitely be useful.

Anyway thanks a lot for the quick response!
