### ISSUE TITLE
Feature request: Allow customising / augmenting validation of protobufs

### ISSUE THREAD

**Issue by Horneth** [scalapb/ScalaPB#947]
The validation offered by the rules in https://scalapb.github.io/docs/validation is quite extensive but has some inherent limitations.
For instance as far as I can tell there's no way to validate fields of a message in relationship with each other, say

```proto
message Foo {
  int32 a = 1;
  int32 b = 2;
}
```

I couldn't find a way here to express "a must be different from b".

One way I can think of enabling that would be to add an option that stops the generator from including the implicit validator instance in the companion object of `Foo`. This way one could extend `Foo`'s companion with the already existing extension mechanism and inject their own validator instance. For example using the auxiliary options it could look like

```scala
trait CustomFooValidation {
  implicit val fooValidator: Validator[Foo] = ...
}
```

```proto
syntax = "proto3";
package a.b.c;
import "scalapb/scalapb.proto";
option (scalapb.options) = {
    scope: PACKAGE
    aux_message_options: [
        {
            target: "a.b.c.Foo"
            options: {
                insert_validator_instance: false
                companion_extends: "a.b.c.CustomFooValidation"
            }
        }
    ]
};
```

This would allow targeting specific message to augment or replace their validation logic, while keeping the rest of the messages unchanged.

**Comment by Horneth** [comment]
Would you be open to a PR to add an option in the scalapb proto for this and make use of it in `scalapb-validate` ?

**Comment by thesamet** [comment]
I am open for a PR for this. To create space for future customization, I prefer that it would be made in a proto that comes with scalapb-validate, not in scalapb.proto. The new proto could be something like this:

```
extend scalapb.MessageOptions {
  optional ValidationOptions validation = 1001;
}

message ValidationOptions {
  optional bool insert_validator_instance = 1;
}
```

**Comment by Horneth** [comment]
That makes sense, I'll look into it when I have some time :)

**Comment by Horneth** [comment]
That would mean we'd need to define an extension range in `MessageOptions` in `scalapb.proto` first is that right ?

**Comment by thesamet** [comment]
Yes. I think 1001 and beyond should be safe.

**Comment by thesamet** [comment]
We now have an option to inhibit the implicit validator insertion. Closing - feel free to open a new issue if there are additional gaps.
