### ISSUE TITLE
Allow sealed oneofs to be part of a parent message

### ISSUE THREAD

**Issue by otto-dev** [scalapb/ScalaPB#974]
This is a carry-on from #751. Might be niche use-case, but it would be nice to be able to define a `preamble` for the body of a generated companion object. The idea is to have messages, as well as sealed traits, namespaced to an enclosing object.

My use case is Akka Typed, particularly with persistence, where there is a naming-convention to have all the messages (the protocol) for an actor inside a single object, including a `sealed trait Command` and `Event`, which is then extended by messages.

My current solution is to hack the `sealed trait` preamble into the companion object using `annotations`

```proto
message SomeProtocol {
  message State {
    // Hack to place the sealed traits in the SomeProtocol object
    option (scalapb.message).annotations = "sealed trait Command";
    option (scalapb.message).annotations = "sealed trait Event";

    // ...
  }

  message DoSomething {
    option (scalapb.message).extends = "Command";
    // ...
  }

  message SomethingDone {
    option (scalapb.message).extends = "Event";
    // ...
  }
}
``` 

This way `SomeProtocol.Command` and `SomeProtocol.DoSomething` signal that they belong to the same "protocol" and belong to each other by living in the same object. They are also easily and idiomatically imported together using `import SomeProtocol._`.

**Comment by thesamet** [comment]
Hi @otto-dev , will definite accept a PR for a new `companion_preamble`. This doc contains some notes on how to do this: https://github.com/scalapb/ScalaPB/blob/master/CONTRIBUTING.md - also I wonder if you looked into [sealed oneofs](https://scalapb.github.io/docs/sealed-oneofs/) as a way to have the sealed traits generated for you.

**Comment by otto-dev** [comment]
I didn't know about `sealed oneofs`. It would be perfect, except that I can't namespace the messages under a common `object` then, because they'd have to be top-level.

Good to know that a PR would be accepted. Hoping to look into it.

**Comment by thesamet** [comment]
@otto-dev out of curiosity, why your messages need to be top-level?

**Comment by otto-dev** [comment]
They'd have to be top-level for the `sealed oneofs` [to work](https://scalapb.github.io/docs/sealed-oneofs/#sealed-oneof-rules) (rule 4, also 5). But that's not what I was looking for. I want the traits from the example (`Command`, `Event` and `State`) to be part of a single importable `object`.

**Comment by thesamet** [comment]
Got it. I think rules 4 and 5 can be relaxed to "top-level or defined inside the same message", but no one ever asked.

**Comment by otto-dev** [comment]
> I think rules 4 and 5 can be relaxed to "top-level or defined inside the same message", but no one ever asked.

Then let me ask with a PR :wink: #977

I ran a few experimental cases, and at appears to work, as you suspected.

**Comment by otto-dev** [comment]
No, thanks to you @thesamet for this library and your excellent maintenance of the same!
