### ISSUE TITLE
Comparison error in Dotty

### ISSUE THREAD

**Issue by EmergentOrder** [scalapb/ScalaPB#981]
I recently started using ScalaPB for generation from a proto file in my project, was working just as expected (including in Dotty!) until just now when I moved from 0.27.0-RC1 to 3.0.0-M1. 

Now I get:
```
[error] -- Error: /home/selvelrel/dev/onnx-scala/proto/.js/target/scala-3.0.0-M1/src_managed/main/onnx/onnx/TypeProto.scala:588:60 
[error] 588 |        _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
[error]     |                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]     |Values of types scalapb.descriptors.Descriptor and scalapb.descriptors.Descriptor cannot be compared with == or !=
```
(repeats, for different files)

using sbt-protoc 1.0.0-RC4 and compiler plugin 0.11.0-M4

please assist.

Thanks for all your work here btw!

**Comment by EmergentOrder** [comment]
My first thought is that it looks like conflicting ScalaPB versions, but that doesn't appear to be the case.

**Comment by EmergentOrder** [comment]
To be clear, I get this error on both JVM and js

**Comment by EmergentOrder** [comment]
Yeah, the only other versions of ScalaPB were evicted (per `sbt dependencyTree`), but even removing them entirely doesn't fix it.

**Comment by thesamet** [comment]
Are you compiling with `strictEquality` enabled? If so, currently the generated code isn't compatible with this option.

**Comment by EmergentOrder** [comment]
I was, looks like this fixed it. Thanks!
The build seems much slower now, but it looks unrelated, the ScalaPB part completed.
