### ISSUE TITLE
Code generated by ScalaPB breaks IntelliJ Scala 3 (Dotty) plugin from working

### ISSUE THREAD

**Issue by PhilAndrew** [scalapb/ScalaPB#985]
I'm not confident this is a bug on your side - but I don't like this problem as I want to code within IntelliJ in Scala 3 Dotty, but it does not work, please see the linked issue. I guess the Scala plugin needs to be changed to fix its behaviour but it maybe the case that the code outputted by this isn't syntactically correct for Scala 3?
If the code outputted isn't syntactically correct for Scala 3 then this would be a feature request to output to Scala 3 code.

https://youtrack.jetbrains.com/issue/SCL-18477

Alternatively, I have a question, could you output more simple code then it would work within Scala 3? The code generated seems fairly complex, I was originally just expecting basic case classes.

**Comment by thesamet** [comment]
Thanks for reporting. It's worthwhile to try and update to ScalaPB 0.11.0-M4 with Scala 3.0.0-M1, if IntelliJ supports it.

> Alternatively, I have a question, could you output more simple code then it would work within Scala 3? The code generated seems fairly complex, I was originally just expecting basic case classes.

ScalaPB generates the case classes but also code to serialize and deserialize them from binary representation, as well as lenses to enable easy updates of nested structures. The lenses are optional and can be disabled (see documentation). You are most likely looking at an IntelliJ bug as the code generated by ScalaPB is tested on all supported Scala versions including Dotty.

**Comment by PhilAndrew** [comment]
Just FYI, I tried Scala Metals in VSCode and that didn't work either.

**Comment by PhilAndrew** [comment]
Did more investigation.

The following code does not work with Scala IntelliJ Dotty.

```
package tutorial.addressbook

@SerialVersionUID(0L)
 case class Person(
    name: _root_.scala.Predef.String,
    id: _root_.scala.Int,
    email: _root_.scala.Option[_root_.scala.Predef.String] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = null
    ) 
```

The following code works with Scala IntelliJ Dotty.

```
@SerialVersionUID(0L)
 case class Person(
    name: _root_.scala.Predef.String,
    id: _root_.scala.Int,
    email: _root_.scala.Option[_root_.scala.Predef.String] = _root_.scala.None,
    unknownFields: String = null
    ) 
```

The difference being there is no reference to scalapb in the second one.

This is my build.sbt

```
val dottyVersion = "0.27.0-RC1"

lazy val root = project
  .in(file("."))
  .settings(
    name := "InsuranceDataSchema",
    version := "0.1.0",

    scalaVersion := dottyVersion,
    useScala3doc := true,

    libraryDependencies += "com.novocode" % "junit-interface" % "0.11" % "test",

    libraryDependencies -= "com.thesamet.scalapb" %% "scalapb-runtime" % "0.11.0-M4",
    
    libraryDependencies += ("com.thesamet.scalapb" %% "scalapb-runtime" % "0.11.0-M4").withDottyCompat(scalaVersion.value),

    PB.targets in Compile := Seq(
      scalapb.gen() -> (sourceManaged in Compile).value / "scalapb"
    )
  )
```

**Comment by PhilAndrew** [comment]
If I remove this line from build.sbt

libraryDependencies -= "com.thesamet.scalapb" %% "scalapb-runtime" % "0.11.0-M4",

Then only exist this

 libraryDependencies += ("com.thesamet.scalapb" %% "scalapb-runtime" % "0.11.0-M4").withDottyCompat(scalaVersion.value),

Cannot import project as it cannot find this.

**Comment by thesamet** [comment]
ScalaPB 0.11.0-M4 is published for Scala 3.0.0-M1, which doesn't match the scalaVersion you are using in your build.sbt. Once the Scala versions are aligned you wouldn't need the `withDottyCompat`. I created an [example project here](https://github.com/thesamet/sbt-protoc/tree/master/examples/scalapb-dotty) and verified that it builds and works (including code navigation) with VS Code/Metals.

**Comment by thesamet** [comment]
@PhilAndrew can you confirm it works in VSCode for you? Is it still not working in IntelliJ?

**Comment by PhilAndrew** [comment]
When I checked about 3 days ago the IntelliJ plugin doesn’t support Scala 3.0.0-M1, so it didn’t work in IntelliJ but it worked in vscode as described

**Comment by thesamet** [comment]
Thanks for the update. Sounds like the gap is on IntelliJ's side. You can try using ScalaPB 0.11.0-M3 which is compiled with Dotty 0.27.0-RC1. We can revisit this when IntelliJ supports Scala 3.0.0-M1
