### ISSUE TITLE
Proto generation bug

### ISSUE THREAD

**Issue by tampler** [scalapb/ScalaPB#989]
Hello

I'm getting an invalid generated code for my proto in `protoc 3.14.0`. Codegen generates `Option[UserId]` and `Option[UserInfo]` instead of `UserId` and `UserInfo`. Pls check my code below
```bash
syntax = "proto3";

message User {
  UserId id = 1;
  UserInfo info = 2;  
}
message UserId {
  string id = 1; 
}
message UserInfo {
  string first = 1;
}
```
This generates into:
```bash
final case class UserId(
    id: _root_.scala.Predef.String = "", //   <---------- OK
    ...) 

final case class UserInfo(
    first: _root_.scala.Predef.String = "", //   <---------- OK
    ....) 

// <---------- Definitely should NOT be an Option here !!!
final case class User(
    id: _root_.scala.Option[user.UserId] = _root_.scala.None,
    info: _root_.scala.Option[user.UserInfo] = _root_.scala.None,
    ... ) 
```
My setup

Ubuntu 20.04.1
OpenJDK 11
protoc 3.14.0
scala 2.13.3
sbt 1.3.13
sbt-protoc: 1.0.0-RC4

**Comment by ahjohannessen** [comment]
@tampler I believe that is the default for `proto3` syntax.

**Comment by thesamet** [comment]
@tampler , this is by design. I've just added an FAQ for this: https://scalapb.github.io/docs/faq#why-message-fields-are-wrapped-in-an-option-in-proto3
